setting_media_homepage:
    path:     /hello/{name}
    defaults: { _controller: SettingMediaBundle:Default:index }

SettingMediaBundle_gallery:
        resource: "@SettingMediaBundle/Resources/config/routing/photogallery.yml"
        prefix:   /website/gallery

SettingMediaBundle_galleryimage:
        resource: "@SettingMediaBundle/Resources/config/routing/galleryimage.yml"
        prefix:   /website/galleryimage
