parameters:
#    setting_media.example.class: Setting\Bundle\MediaBundle\Example

services:
#    setting_media.example:
#        class: %setting_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
