galleries:
    path:     /
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:index" }

galleries_delete_list:
    path:     /delete/lists
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:galleriesDelete" }

gallery:
    path:     /
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:gallery" }

gallery_delete_list:
    path:     /delete/lists
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:galleryDelete" }


gallery_show:
    path:     /{id}/show
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:show" }

gallery_new:
    path:     /new
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:new" }

gallery_create:
    path:     /create
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:create" }
    requirements: { _method: post }

gallery_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:edit" }

gallery_update:
    path:     /{id}/update
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:update" }
    requirements: { _method: post|put }

gallery_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:delete" }

gallery_status:
    path:     /{id}/status
    defaults: { _controller: "SettingMediaBundle:PhotoGallery:status" }
