<?php

namespace Appstore\Bundle\ProcurementBundle\Repository;
use Appstore\Bundle\InventoryBundle\Entity\InventoryConfig;
use Appstore\Bundle\InventoryBundle\Entity\Item;
use Appstore\Bundle\InventoryBundle\Entity\Purchase;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseItem;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseReturnItem;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseVendorItem;
use Appstore\Bundle\ProcurementBundle\Entity\PurchaseOrder;
use Appstore\Bundle\ProcurementBundle\Entity\PurchaseOrderItem;
use Appstore\Bundle\ProcurementBundle\Entity\PurchaseRequisitionItem;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;

/**
 * PurchaseOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrderItemRepository extends EntityRepository
{

    /**
     * @param $qb
     * @param $data
     */

    protected function handleWithSearch($qb,$data)
    {
        if(!empty($data))
        {

            $item = isset($data['item'])? $data['item'] :'';
            $color = isset($data['color'])? $data['color'] :'';
            $size = isset($data['size'])? $data['size'] :'';
            $vendor = isset($data['vendor'])? $data['vendor'] :'';
            $brand = isset($data['brand'])? $data['brand'] :'';
            $category = isset($data['category'])? $data['category'] :'';
            $barcode = isset($data['barcode'])? $data['barcode'] :'';

            if (!empty($barcode)) {
                $qb->andWhere("pi.barcode = :barcode");
                $qb->setParameter('barcode', $barcode);
            }

            if (!empty($item)) {
                $qb->join('item.masterItem', 'mProduct');
                $qb->andWhere("mProduct.name = :name");
                $qb->setParameter('name', $item);
            }

            if (!empty($color)) {
                $qb->join('item.color', 'c');
                $qb->andWhere("c.name = :color");
                $qb->setParameter('color', $color);
            }

            if (!empty($size)) {
                $qb->join('item.size', 's');
                $qb->andWhere("s.name = :size");
                $qb->setParameter('size', $size);
            }

            if (!empty($vendor)) {
                $qb->join('item.vendor', 'v');
                $qb->andWhere("v.companyName = :vendor");
                $qb->setParameter('vendor', $vendor);
            }

            if (!empty($brand)) {
                $qb->join('item.brand', 'b');
                $qb->andWhere("b.name = :brand");
                $qb->setParameter('brand', $brand);
            }

            if (!empty($category)) {
                $qb->join('item.masterItem', 'product');
                $qb->join('product.category','cat');
                $qb->andWhere("cat.name = :category");
                $qb->setParameter('category', $category);
            }
        }

    }

	public function listPoIssueItem($data = array())
	{
		$item = isset($data['item'])? $data['item'] :'';
		$grn = isset($data['grn'])? $data['grn'] :'';
		$brand = isset($data['brand'])? $data['brand'] :'';
		$barcode = isset($data['barcode'])? $data['barcode'] :'';

		$qb = $this->createQueryBuilder('pi');
		$qb->join("pi.purchase",'purchase');
		$qb->join("pi.item",'item');
		//$qb->where("purchase.approve = :approve")->setParameter('approve','approved' );
		//$qb->andWhere("purchase.process = :process")->setParameter('process','Po-issue' );
		if (!empty($item)) {
			$qb->join('item.masterItem', 'm');
			$qb->andWhere("m.name = :name");
			$qb->setParameter('name', $item);
		}
		if (!empty($brand)) {

			$qb->join('item.brand', 'b');
			$qb->andWhere("b.name = :brand");
			$qb->setParameter('brand', $brand);
		}

		if (!empty($grn)) {
			$qb->andWhere("purchase.grn = :grn");
			$qb->setParameter('grn', $grn);
		}
		if (!empty($barcode)) {
			$qb->andWhere("pi.barcode = :barcode");
			$qb->setParameter('barcode', $barcode);
		}
		$qb->orderBy('item.name','ASC');
		$sql = $qb->getQuery();
		return $sql;

	}

    public function findWithSearch($inventory,$data)
    {
        $item = isset($data['item'])? $data['item'] :'';
        $grn = isset($data['grn'])? $data['grn'] :'';
        $brand = isset($data['brand'])? $data['brand'] :'';
        $barcode = isset($data['barcode'])? $data['barcode'] :'';

        $qb = $this->createQueryBuilder('pi');
        $qb->join("pi.purchase",'purchase');
        $qb->join("pi.item",'item');
        $qb->where("purchase.inventoryConfig = :inventoryConfig");
        $qb->setParameter('inventoryConfig', $inventory);

        if (!empty($item)) {

            $qb->join('item.masterItem', 'm');
            $qb->andWhere("m.name = :name");
            $qb->setParameter('name', $item);
        }
        if (!empty($brand)) {

            $qb->join('item.brand', 'b');
            $qb->andWhere("b.name = :brand");
            $qb->setParameter('brand', $brand);
        }

        if (!empty($grn)) {
            $qb->andWhere("purchase.grn = :grn");
            $qb->setParameter('grn', $grn);
        }
        if (!empty($barcode)) {
            $qb->andWhere("pi.barcode = :barcode");
            $qb->setParameter('barcode', $barcode);
        }
        $qb->orderBy('item.name','ASC');
        $sql = $qb->getQuery();
        return $sql;

    }


    public function updateIssueItem(PurchaseOrder $entity){

    	$qb = $this->_em->createQueryBuilder();
	    $qb->from('InventoryBundle:PurchaseItem','e');
	    $qb->join('e.purchaseOrderItem','poi');
	    $qb->join('poi.purchase','po');
	    $qb->select('SUM(e.quantity) as issueQnt');
	    $qb->addSelect('poi.id as itemId');
	    $qb->where("po.id = :purchaseOrder");
	    $qb->setParameter('purchaseOrder', $entity->getId());
	    $qb->groupBy('po.id');
	    $result = $qb->getQuery()->getArrayResult();
	    foreach ($result as $item){
		    $orderItem = $this->find($item['itemId']);
		    $orderItem->setIssueQuantity($item['issueQnt']);
		    $this->_em->persist($orderItem);
		    $this->_em->flush();
	    }
    }

	public function insertPoItem(PurchaseOrder $entity,$data){

	    $qb = $this->_em->createQueryBuilder();
	    $qb->from('ProcurementBundle:PurchaseRequisitionItem','e');
	    $qb->join('e.item','i');
	    $qb->join('e.purchaseOrder','po');
	    $qb->select('SUM(e.issueQuantity) as issueQnt');
	    $qb->addSelect('i.id as itemId');
	    $qb->where("po.id = :purchaseOrder");
	    $qb->setParameter('purchaseOrder', $entity->getId());
	    $qb->groupBy('i.id');
	    $result = $qb->getQuery()->getArrayResult();
    	foreach ($result as $item){
    		$invItem = $this->_em->getRepository('InventoryBundle:Item')->find($item['itemId']);
			$orderItem = new PurchaseOrderItem();
		    $orderItem->setEstimateQuantity($item['issueQnt']);
		    $orderItem->setQuantity($item['issueQnt']);
		    $orderItem->setPurchase($entity);
		    $orderItem->setItem($invItem);
		    $orderItem->setEstimatePrice($invItem->getPurchasePrice());
		    $orderItem->setEstimateSubTotal($orderItem->getEstimatePrice() * $orderItem->getQuantity());
		    $this->_em->persist($orderItem);
		    $this->_em->flush();
	    }
    }



    public function getPurchaseItems(GlobalOption $globalOption , $data)
    {
        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.purchase','e');
        $qb->join('pi.item','item');
        $qb->select('pi.barcode');
        $qb->addSelect('pi.quantity');
        $qb->addSelect('item.name');
        $qb->where("e.inventoryConfig = :inventoryConfig");
        $qb->setParameter('inventoryConfig', $globalOption->getInventoryConfig()->getId());
        $this->handleWithSearch($qb,$data);
        $qb->orderBy('item.name','ASC');
        $result = $qb->getQuery();
        return $result;
    }

    public function getPurchaseItemCount($item)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(pi.id)');
        $qb->from('InventoryBundle:PurchaseItem','pi');
        $qb->where("pi.item = :item");
        $qb->setParameter('item', $item->getId());
        $count = $qb->getQuery()->getSingleScalarResult();
        if($count > 0 ){
            return $count+1;
        }else{
            return 1;
        }
        return $item;
    }


    public function getPurchaseItemQuantity($purchase,$purchaseVendorItem = 0 )
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('sum(e.quantity)  as totalQnt', 'count(e.id)  as totalItem');
        $qb->from('InventoryBundle:PurchaseItem', 'e');
        $qb->where("e.purchase = :purchase");
        $qb->setParameter('purchase', $purchase->getId());
        if ($purchaseVendorItem > 0){
            $qb->andWhere("e.purchaseVendorItem = :purchaseVendorItem");
            $qb->setParameter('purchaseVendorItem', $purchaseVendorItem );
        }
        $qb = $qb->getQuery()->getSingleResult();
        return $qb;
    }

    public function findBarcode($item)
    {
        $avg = $this->getItemAveragePrice($item->getItem());
        $data  = '';
        $data .='<div class="span4">';
        $data .='<ul class="unstyled">';
        $data .='<li><strong>Vendor #:</strong> '.$item->getPurchase()->getVendor()->getCompanyName().'</li>';
        $data .='<li><strong>Received:</strong> xxx</li>';
        $data .='</ul>';
        $data .='</div>';
        $data .='<div class="span4">';
        $data .='<ul class="unstyled">';
        $data .='<li><strong>Purchase:</strong> '.$item->getPurchasePrice().'</li>';
        $data .='<li><strong>Sales:</strong> '.$item->getSalesPrice().'</li>';
        $data .='</ul>';
        $data .='</div>';
        $data .='<div class="span4">';
        $data .='<ul class="unstyled">';
        $data .='<li><strong>Purse.average:</strong> '.number_format($avg['purchaseAvg']).'</li>';
        $data .='<li><strong>Sls.average:</strong> '.number_format($avg['salesAvg']).'</li>';
        $data .='</ul>';
        $data .='</div>';

        return $data;
    }

    public function getItemAveragePrice($item)
    {
             return $qbAvg = $this->createQueryBuilder('pi')
            ->select("avg(pi.salesPrice) as salesAvg, avg(pi.purchasePrice) as purchaseAvg")
            ->where('pi.item = :item')
            ->setParameter('item', $item->getId())
            ->getQuery()->getSingleResult();
    }

    public function getItemList($purchase)
    {
        $entities = $purchase->getPurchaseItems();
        $data = '';
        foreach( $entities as $entity){
           $data .=' <tr id="remove-'.$entity->getId().'">';
            $data .='<td class="numeric" >'.$entity->getName().'</td>';
            $data .='<td class="numeric" >'.$entity->getItem()->getSkuSlug().'</td>';
            $data .='<td class="numeric" >'.$entity->getQuantity().'</td>';
            $data .='<td class="numeric" >'.$entity->getPurchasePrice().'</td>';
            $data .='<td class="numeric" >'.$entity->getPurchaseSubTotal().'</td>';
            $data .='<td class="numeric" >'.$entity->getSalesPrice().'</td>';
            $data .='<td class="numeric" >'.$entity->getSalesSubTotal().'</td>';
            $data .='<td class="numeric" >'.$entity->getWebPrice().'</td>';
            $data .='<td class="numeric" >'.$entity->getWebSubTotal().'</td>';
            $data .='<td class="numeric" >
                     <a id="'.$entity->getId().'" title="Are you sure went to delete ?" rel="/inventory/purchaseitem/'.$entity->getId().'/delete" href="javascript:" class="btn red mini delete" ><i class="icon-trash"></i></a>
                     </td>';
            $data .='</tr>';
        }
        return $data;

    }

    public function getBarcodeForPrint($data)
    {
        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.item', 'item');
        $qb->select('pi');
        $qb->where($qb->expr()->in("pi.id", $data ));
        $qb->orderBy('item.name','ASC');
        return $qb->getQuery()->getResult();
    }

	public function getPoItem($data)
	{
		$qb = $this->createQueryBuilder('pi');
		$qb->join('pi.item', 'item');
		$qb->select('pi');
		$qb->where($qb->expr()->in("pi.id", $data ));
		$qb->orderBy('item.name','ASC');
		return $qb->getQuery()->getResult();
	}

    public function getManualSalesItem($inventory,$data)
    {

        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.item', 'item');
        $qb->join('pi.purchase', 'purchase');
        $qb->join('purchase.inventoryConfig', 'ic');
        $qb->select('pi');
        $qb->where($qb->expr()->in("pi.id", $data ));
        $qb->andWhere("ic.id = :inventory");
        $qb->setParameter('inventory', $inventory->getId());
        $qb->orderBy('item.name','ASC');
        return $qb->getQuery()->getResult();

    }

    public function returnPurchaseItemDetails($inventory,$barcode)
    {

        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.item', 'item');
        $qb->join('pi.purchase', 'p');
        $qb->select('pi');
        $qb->where("pi.barcode = :barcode" );;
        $qb->setParameter('barcode', $barcode);
        $qb->andWhere("p.inventoryConfig = :inventory");
        $qb->setParameter('inventory', $inventory->getId());
        return $qb->getQuery()->getSingleResult();

    }

    public function searchAutoComplete($item, InventoryConfig $inventory)
    {

        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.purchase', 'p');
        $qb->join('pi.stockItem', 'stockitem');
        $qb->select('pi.barcode as id');
        $qb->addSelect('pi.barcode as text');
        $qb->addSelect('SUM(stockitem.quantity) as item_name');
        $qb->where($qb->expr()->like("pi.barcode", "'$item%'"  ));
        $qb->andWhere("p.inventoryConfig = :inventory");
        $qb->setParameter('inventory', $inventory->getId());
        $qb->orderBy('p.updated', 'ASC');
        $qb->setMaxResults( '10' );
        return $qb->getQuery()->getResult();

    }

    public function generatePurchaseVendorItem(Purchase $purchase)
    {
        $qb = $this->createQueryBuilder('pi');
        $qb->join('pi.purchase', 'p');
        $qb->join('pi.item','item');
        $qb->join('item.masterItem','product');
        $qb->select('SUM(pi.quantity) as quantity');
        $qb->addSelect('product.id as productId');
        $qb->addSelect('product.name as productName');
        $qb->addSelect('AVG(pi.purchasePrice) as purchase');
        $qb->addSelect('AVG(pi.salesPrice) as sales');
        $qb->where("p.id = :id");
        $qb->setParameter('id', $purchase->getId());
        $qb->groupBy('item.masterItem');
        $data = $qb->getQuery()->getArrayResult();
        foreach ($data as $row){

           $purchaseVendorItem = $this->_em->getRepository('InventoryBundle:PurchaseVendorItem')->findOneBy(array('purchase' => $purchase ,'masterItem' => $row['productId']));
           $entity = new PurchaseVendorItem();
           if(!empty($purchaseVendorItem)){
               $entity = $purchaseVendorItem;
           }
           $product = $this->_em->getRepository('InventoryBundle:Product')->find($row['productId']);
           $entity->setPurchase($purchase);
           $entity->setInventoryConfig($purchase->getInventoryConfig());
           $entity->setMasterItem($product);
           $entity->setName($row['productName']);
           $entity->setPurchasePrice($row['purchase']);
           $entity->setSalesPrice($row['sales']);
           $entity->setWebPrice($row['sales']);
           $entity->setQuantity($row['quantity']);
           $entity->setMasterQuantity($row['quantity']);
           $this->_em->persist($entity);
           $this->_em->flush($entity);

       }

        /* @var PurchaseItem $item */

        foreach ($purchase->getPurchaseItems() as $item){

            $masterItem = $item->getItem()->getMasterItem();
            $purchaseVendorItem = $this->_em->getRepository('InventoryBundle:PurchaseVendorItem')->findOneBy(array('purchase' => $purchase ,'masterItem' => $masterItem));
            $item->setPurchaseVendorItem($purchaseVendorItem);
            $this->_em->persist($item);
            $this->_em->flush($item);
        }

    }

    public function updateSalesPrice(Item $item)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->update('InventoryBundle:PurchaseItem', 'e')
            ->set('e.salesPrice', $item->getSalesPrice())
            ->where('e.item = :item')
            ->setParameter('item', $item->getId())
            ->getQuery()
            ->execute();

    }

	public function prProcess($process,$data)
    {
        foreach ($data as $row){

	        $item = $this->find($row);
	        $item->setProcess($process);
	        $this->_em->persist($item);
	        $this->_em->flush();
        }

    }

    public function updatePurchaseOrderItem($data )
    {

	    foreach ($data['itemId'] as $key => $row){

		    /* @var $item PurchaseOrderItem */

		    $item = $this->find($row);
		    $item->setPurchasePrice($data['itemPurchasePrice'][$key]);
		    $item->setQuantity($data['itemQuantity'][$key]);
		    $item->setPurchaseSubTotal($item->getPurchasePrice() * $item->getQuantity());
		    $this->_em->persist($item);
		    $this->_em->flush();
	    }

    }



}
