<?php

namespace Appstore\Bundle\InventoryBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ItemAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemAttributeRepository extends EntityRepository
{

}
