<?php

namespace Appstore\Bundle\InventoryBundle\Repository;
use Appstore\Bundle\InventoryBundle\Entity\Item;
use Appstore\Bundle\InventoryBundle\Entity\Purchase;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseItem;
use Appstore\Bundle\InventoryBundle\Entity\PurchaseItemSerial;
use Doctrine\ORM\EntityRepository;


/**
 * PurchaseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseItemSerialRepository extends EntityRepository
{

    public function insertPurchaseItemSerial(Purchase $purchase){

        $em = $this->_em;

        /* @var $item PurchaseItem  */


        foreach ($purchase->getPurchaseItems() as $item ){
            if($item->getSerialNo()){
                $id = $item->getId();
                $stock = $em->createQuery("DELETE InventoryBundle:PurchaseItemSerial e WHERE e.purchaseItem = $id");
                if($stock){ $stock->execute(); }
            }
        }

        foreach($purchase->getPurchaseItems() as $item){
            if($item->getSerialNo()){
                $ids = explode(",", $item->getSerialNo());
                foreach ($ids as $id){
                  //  $barcode = TRIM(str_replace(str_replace(str_replace($id,'\t',''),'\n',''),'\r',''));
                    $barcode = TRIM(preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $id));
                    $entity = new PurchaseItemSerial();
                    $entity->setInventoryConfig($purchase->getInventoryConfig());
                    $entity->setItem($item->getItem());
                    $entity->setPurchaseItem($item);
                    $entity->setBarcode($barcode);
                    $entity->setStatus(0);
                    $em->persist($entity);
                    $em->flush();
                }

            }

        }

    }

    public function updatePurchaseItemSerial(PurchaseItem $item,$value){

        $em = $this->_em;

        /* @var $item PurchaseItem  */

        if($item->getSerialNo()){
            $id = $item->getId();
            $stock = $em->createQuery("DELETE InventoryBundle:PurchaseItemSerial e WHERE  e.status != 1 AND  e.purchaseItem = $id");
            if($stock){ $stock->execute(); }
        }

        if($value){
            $ids = explode(",", $value);
            foreach ($ids as $id){

                //  $barcode = TRIM(str_replace(str_replace(str_replace($id,'\t',''),'\n',''),'\r',''));
                $barcode = TRIM(preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $id));
                $empty = $this->findOneBy(array('purchaseItem' => $item,'barcode'=> $barcode));
                if(empty($empty)){
                    $entity = new PurchaseItemSerial();
                    $entity->setInventoryConfig($item->getPurchase()->getInventoryConfig());
                    $entity->setItem($item->getItem());
                    $entity->setPurchaseItem($item);
                    $entity->setBarcode($barcode);
                    $entity->setStatus(0);
                    $em->persist($entity);
                    $em->flush();
                }
            }

        }
        return $item;

    }

    public function sysncPurchaseItemSerial(PurchaseItem $item){

        $em = $this->_em;

        /* @var $item PurchaseItem  */

        if($item->getSerialNo()){
            $id = $item->getId();
            $stock = $em->createQuery("DELETE InventoryBundle:PurchaseItemSerial e WHERE  e.status != 1 AND  e.purchaseItem = $id");
            if($stock){ $stock->execute(); }
        }

        if($item->getSerialNo()){
            $ids = explode(",", $item->getSerialNo());
            foreach ($ids as $id){

                //  $barcode = TRIM(str_replace(str_replace(str_replace($id,'\t',''),'\n',''),'\r',''));
                $barcode = TRIM(preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $id));
                $empty = $this->findOneBy(array('purchaseItem' => $item,'barcode'=> $barcode));
                if(empty($empty)){
                    $entity = new PurchaseItemSerial();
                    $entity->setInventoryConfig($item->getPurchase()->getInventoryConfig());
                    $entity->setItem($item->getItem());
                    $entity->setPurchaseItem($item);
                    $entity->setBarcode($barcode);
                    $entity->setStatus(0);
                    $em->persist($entity);
                    $em->flush();
                }
            }
        }
    }


    public function returnPurchaseItemSerialDetails($inventory,$barcode)
    {
        $qb = $this->createQueryBuilder('pis');
        $qb->select('pis');
        $qb->where("pis.inventoryConfig = :inventory")->setParameter('inventory', $inventory->getId());
        $qb->andWhere("pis.barcode = :barcode" )->setParameter('barcode', $barcode);
        $row = $qb->getQuery()->getOneOrNullResult();
        if($row){
            return $row;
        }
        return false;
    }

    public function getSerialProducts(Item $entity)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('e.id  as id','e.barcode  as barcode','e.updated  as updated');
        $qb->where("e.item = :item");
        $qb->andWhere("e.status != 1");
        $qb->setParameter('item', $entity->getId());
        $result = $qb->getQuery()->getArrayResult();
        return $result;

    }

    public function removeSerialNo(Purchase $purchase){

        $em = $this->_em;
        /* @var $item PurchaseItem */
        foreach ($purchase->getPurchaseItems() as $item ){
            if($item->getSerialNo()){
                $id = $item->getId();
                $stock = $em->createQuery("DELETE InventoryBundle:PurchaseItemSerial e WHERE e.purchaseItem = $id");
                if($stock){ $stock->execute(); }
            }
        }
    }



}
