<?php

namespace Appstore\Bundle\HumanResourceBundle\Repository;

/**
 * LeavePolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayrollSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
