<?php

namespace Appstore\Bundle\AssetsBundle\Repository;
use \Doctrine\ORM\EntityRepository;

/**
 * ProductDistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionRepository extends EntityRepository
{
	public function findWithSearch($data)
	{


		$item = isset($data['item'])? $data['item'] :'';
		$branch = isset($data['branch'])? $data['branch'] :'';
		$category = isset($data['category'])? $data['category'] :'';
		$parent = isset($data['parent'])? $data['parent'] :'';
		$depreciation = isset($data['depreciation'])? $data['depreciation'] :'';
		$qb = $this->createQueryBuilder('e');
		$qb->join('e.product', 'item');
	//	$qb->join('item.item', 'm');
		/*if (!empty($item)) {
			$qb->andWhere("m.name = :name");
			$qb->setParameter('name', $item);
		}

		if (!empty($category)) {
			$qb->join('item.category', 'c');
			$qb->andWhere("c.name = :category");
			$qb->setParameter('category', $category);
		}

		if (!empty($parent)) {
			$qb->join('item.parentCategory', 'pc');
			$qb->andWhere("pc.name = :parent");
			$qb->setParameter('parent', $parent);
		}

		if (!empty($depreciation)) {
			$qb->join('m.depreciation', 'd');
			$qb->andWhere("d.name = :depreciation");
			$qb->setParameter('depreciation', $depreciation);
		}

		if (!empty($vendor)) {
			$qb->join('item.vendor', 'v');
			$qb->andWhere("v.companyName = :vendor");
			$qb->setParameter('vendor', $vendor);
		}

		if (!empty($branch)) {

			$qb->join('item.branch', 'b');
			$qb->andWhere("b.name = :branch");
			$qb->setParameter('branch', $branch);

		}*/
		$qb->getQuery();
		return  $qb;

	}
}
