<?php

namespace Appstore\Bundle\DoctorPrescriptionBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * DpsPrescriptionAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DpsPrescriptionAttributeRepository extends EntityRepository
{

}
