stock_adjustment:
    path:     /
    defaults: { _controller: "MedicineBundle:StockAdjustment:index" }

stock_adjustment_summary:
    path:     /summary
    defaults: { _controller: "MedicineBundle:StockAdjustment:stockSummary" }

stock_adjustment_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:StockAdjustment:new" }

stock_adjustment_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:StockAdjustment:create" }
    methods:  POST

stock_adjustment_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:StockAdjustment:edit" }

stock_adjustment_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:StockAdjustment:update" }
    methods:  [POST, PUT]

stock_adjustment_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:StockAdjustment:delete" }

stock_adjustment_approved:
    path:     /{id}/approved
    defaults: { _controller: "MedicineBundle:StockAdjustment:approved" }