medicine_config_manage:
    path:     /manage
    defaults: { _controller: "MedicineBundle:MedicineConfig:manage" }

medicine_config_update:
    path:     /update
    defaults: { _controller: "MedicineBundle:MedicineConfig:update" }
    methods:  [POST, PUT]

medicine_user_search:
    path:     /search
    defaults: { _controller: "DomainUserBundle:DomainUser:autoSearch" }
    options:
            expose: true




