medicine_damage:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineDamage:index" }

medicine_damage_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineDamage:new" }

medicine_damage_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineDamage:create" }
    methods:  POST

medicine_damage_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineDamage:edit" }

medicine_damage_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineDamage:update" }
    methods:  [POST, PUT]

medicine_damage_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineDamage:delete" }

medicine_damage_approved:
    path:     /{id}/approved
    defaults: { _controller: "MedicineBundle:MedicineDamage:approved" }