dental_investigation:
    path:     /
    defaults: { _controller: "MedicineBundle:DentalInvestigation:index" }

dental_investigation_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:DentalInvestigation:create" }
    methods:  POST

dental_investigation_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:DentalInvestigation:edit" }

dental_investigation_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:DentalInvestigation:update" }
    methods:  [POST, PUT]

dental_investigation_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:DentalInvestigation:delete" }

dental_investigation_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:DentalInvestigation:status" }