medicine_instantpurchase:
    path:     /
    defaults: { _controller: "MedicineBundle:InstantPurchase:index" }

medicine_instant_purchase_load:
    path:     /{sales}/medicine-instant-purchase-load
    defaults: { _controller: "MedicineBundle:InstantPurchase:instantPurchaseLoad" }
    options:
            expose: true

medicine_instant_purchase_add:
    path:     /medicine-instant-purchase-add
    defaults: { _controller: "MedicineBundle:InstantPurchase:instantPurchaseAdd" }
    options:
            expose: true


medicine_instant_purchase_delete:
    path:     /{id}/medicine-instant-purchase-delete
    defaults: { _controller: "MedicineBundle:InstantPurchase:instantPurchaseDelete" }

medicine_instantpurchase_particular_add:
    path:     /instant-purchase-particular-add
    defaults: { _controller: "MedicineBundle:InstantPurchase:addParticular" }
    methods:  POST
    options:
            expose: true

medicine_instantpurchase_item_add:
    path:     /instant-purchase-item-add
    defaults: { _controller: "MedicineBundle:InstantPurchase:addInstantPurchaseItem" }
    methods:  POST
    options:
            expose: true

