medicinestock_import:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineImport:index" }

medicinestock_import_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "MedicineBundle:MedicineImport:excelDataImport" }

medicinestock_import_stock_migration:
    path:     /{id}/data-stock-migration
    defaults: { _controller: "MedicineBundle:MedicineImport:excelDataImportStock" }

medicinestock_import_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineImport:new" }

medicinestock_import_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineImport:create" }
    methods:  POST

medicinestock_import_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineImport:delete" }


medicinestock_file_upload:
    path:     /medicine/upload
    defaults: { _controller: "MedicineBundle:MedicineImport:upload" }

medicinestock_upload_create:
    path:     /medicine/upload/create
    defaults: { _controller: "MedicineBundle:MedicineImport:uploadCreate" }

