medicine_company:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineCompany:index" }

medicine_company_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicineCompany:show" }

medicine_company_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineCompany:new" }

medicine_company_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineCompany:create" }
    methods:  POST

medicine_company_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineCompany:edit" }

medicine_company_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineCompany:update" }
    methods:  [POST, PUT]

medicine_company_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineCompany:delete" }
    methods:  [POST, DELETE]
