medicine_minimum:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:index" }

medicine_minimum_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:create" }
    methods:  POST

medicine_minimum_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:edit" }

medicine_minimum_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:update" }
    methods:  [POST, PUT]

medicine_minimum_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:status" }

medicine_minimum_process:
    path:     /{id}/process
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:process" }

medicine_minimum_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineMinimumStock:delete" }
