medicine:
    path:     /
    defaults: { _controller: "MedicineBundle:Medicine:index" }

medicine_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:Medicine:create" }
    methods:  POST

medicine_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:Medicine:edit" }

medicine_copy:
    path:     /{id}/copy
    defaults: { _controller: "MedicineBundle:Medicine:copy" }

medicine_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:Medicine:update" }
    methods:  [POST, PUT]

medicine_select_search:
    path:     /select-medicine-search
    defaults: { _controller: "MedicineBundle:MedicineBrand:selectSearchMedicine" }
    options:
            expose: true

medicine_search:
    path:     /medicine-search
    defaults: { _controller: "MedicineBundle:MedicineBrand:autoSearchMedicine" }
    options:
            expose: true

medicine_details:
    path:     /medicine-details
    defaults: { _controller: "MedicineBundle:MedicineBrand:medicineDetails" }
    options:
            expose: true

generic_search:
    path:     /generic-search
    defaults: { _controller: "MedicineBundle:MedicineBrand:autoSearchGeneric" }
    options:
            expose: true

medicine_name:
    path:      /{medicine}/medicine-name
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchProductName" }
    options:
            expose: true

medicine_user:
    path:     /medicine-user
    defaults: { _controller: "MedicineBundle:Medicine:index" }

medicine_search_brand_name_complete:
    path:     /search-brand-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchBrandNameAutoComplete" }
    options:
            expose: true

medicine_search_company_name_complete:
    path:     /search-company-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchCompanyNameAutoComplete" }
    options:
            expose: true

medicine_search_generic_name_complete:
    path:     /search-generic-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchGenericNameAutoComplete" }
    options:
            expose: true

medicine_search_pack_size_name_complete:
    path:     /search-pack-size-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchPackSizeAutoComplete" }
    options:
            expose: true

medicine_search_strength_name_complete:
    path:     /search-strength-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchStrengthAutoComplete" }
    options:
            expose: true

medicine_search_form_name_complete:
    path:     /search-form-name-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchMedicineFormAutoComplete" }
    options:
            expose: true

medicine_search_medicine_generic_complete:
    path:     /search-generic-medicine-auto-complete
    defaults: { _controller: "MedicineBundle:MedicineBrand:searchMedicineGenericNameAutoComplete" }
    options:
            expose: true


