medicine_transfer:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineTransfer:index" }

medicine_transfer_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineTransfer:new" }

medicine_transfer_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineTransfer:create" }
    methods:  POST

medicine_transfer_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineTransfer:edit" }

medicine_transfer_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicineTransfer:show" }

medicine_transfer_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineTransfer:update" }
    methods:  [POST]

medicine_transfer_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineTransfer:delete" }

medicine_transfer_item_delete:
    path:     /{purchase}/{id}/item-delete
    defaults: { _controller: "MedicineBundle:MedicineTransfer:deleteItem" }

medicine_transfer_approve:
    path:     /{id}/approve
    defaults: { _controller: "MedicineBundle:MedicineTransfer:approve" }

medicine_transfer_discount_update:
    path:     /dicount-update
    defaults: { _controller: "MedicineBundle:MedicineTransfer:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true