medicine_particular:
    path:     /
    defaults: { _controller: "MedicineBundle:Particular:index" }

medicine_particular_search:
    path:     /search
    defaults: { _controller: "MedicineBundle:Particular:autoSearch" }
    options:
            expose: true

medicine_particular_name:
    path:      /{particular}/particular-name
    defaults: { _controller: "MedicineBundle:Particular:searchParticularName" }
    options:
            expose: true

medicine_particular_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:Particular:create" }
    methods:  POST

medicine_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:Particular:edit" }

medicine_particular_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:Particular:update" }
    methods:  [POST, PUT]

medicine_particular_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:Particular:status" }

medicine_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:Particular:delete" }
