medicine_prepurchase:
    path:     /
    defaults: { _controller: "MedicineBundle:Prepurchase:index" }


medicine_prepurchase_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:Prepurchase:show" }

medicine_prepurchase_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:Prepurchase:new" }

medicine_prepurchase_create:
    path:     /short-list-to-pre-purchase
    defaults: { _controller: "MedicineBundle:Prepurchase:create" }

medicine_prepurchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:Prepurchase:edit" }

medicine_prepurchase_process:
    path:     /{id}/purchase-process
    defaults: { _controller: "MedicineBundle:Prepurchase:process" }

medicine_prepurchase_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:Prepurchase:update" }
    methods:  [POST, PUT]

medicine_prepurchase_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:Prepurchase:edit" }


medicine_prepurchase_approve:
    path:     /{id}/approve
    defaults: { _controller: "MedicineBundle:Prepurchase:approved" }

medicine_prepurchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:Prepurchase:delete" }

medicine_prepurchase_particular_search:
    path:     /{id}/medicine-stock-search
    defaults: { _controller: "MedicineBundle:Prepurchase:particularSearch" }
    options:
            expose: true




medicine_prestock_item_create:
    path:     /{id}/pre-stock-item-create
    defaults: { _controller: "MedicineBundle:Prepurchase:stockItemCreate" }
    methods:  POST
    options:
            expose: true

medicine_prepurchase_discount_update:
    path:     /purchase/dicount-update
    defaults: { _controller: "MedicineBundle:Prepurchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true


medicine_prepurchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "MedicineBundle:Prepurchase:invoiceParticularDelete" }

medicine_prepurchase_item_update:
    path:     /item-update
    defaults: { _controller: "MedicineBundle:Prepurchase:purchaseItemUpdate" }
    methods:  POST
    options:
            expose: true

medicine_prepurchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "MedicineBundle:Prepurchase:approved" }

medicine_prepurchase_download:
    path:     /{id}/pdf-download
    defaults: { _controller: "MedicineBundle:Prepurchase:downloadPdf" }


medicine_prepurchase_update_brand:
    path:     /{id}/invoice-update-brand
    defaults: { _controller: "MedicineBundle:Prepurchase:updateBrand" }
    options:
        expose: true

medicine_prepurchase_stock_item_search:
    path:     /medicine-stock-item-search
    defaults: { _controller: "MedicineBundle:Prepurchase:autoPurchaseStockItemSearch" }
    options:
        expose: true


