medicine_purchase_return:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:index" }

medicine_purchase_return_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:new" }

medicine_purchase_return_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:create" }
    methods:  POST

medicine_purchase_return_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:edit" }

medicine_purchase_return_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:show" }

medicine_purchase_return_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:update" }
    methods:  [POST]

medicine_purchase_return_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:delete" }

medicine_purchase_return_item_delete:
    path:     /{purchase}/{id}/item-delete
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:deleteItem" }

medicine_purchase_return_approve:
    path:     /{id}/approve
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:approve" }

medicine_purchase_return_discount_update:
    path:     /dicount-update
    defaults: { _controller: "MedicineBundle:MedicinePurchaseReturn:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true