medicine_report_purchase_summary:
    path:     /purchase-overview
    defaults: { _controller: "MedicineBundle:Report:purchaseOverview" }

medicine_report_purchase_vendor:
    path:     /purchase-vendor-outstanding
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }

medicine_report_monthly_sales_purchase:
    path:     /monthly-sales-purchase-chart
    defaults: { _controller: "MedicineBundle:Report:salesPurchaseChart" }

medicine_report_daily_hourly_sales:
    path:     /daily-sales-chart
    defaults: { _controller: "MedicineBundle:Report:dailySalesChart" }

medicine_report_top_sales_item:
    path:     /top-sales-item
    defaults: { _controller: "MedicineBundle:Report:topSalesItem" }

medicine_report_low_sales_item:
    path:     /low-sales-item
    defaults: { _controller: "MedicineBundle:Report:lowSalesItem" }

medicine_report_purchase_vendor_details:
    path:     /purchase-vendor-details
    defaults: { _controller: "MedicineBundle:Report:purchaseVendorDetails" }

medicine_report_purchase_vendor_sales:
    path:     /purchase-vendor-sales
    defaults: { _controller: "MedicineBundle:Report:purchaseVendorSales" }

medicine_report_sales_vendor_customer:
    path:     /vendor-base-sales
    defaults: { _controller: "MedicineBundle:Report:salesVendorCustomer" }

medicine_report_purchase_brand_sales:
    path:     /purchase-brand-sales
    defaults: { _controller: "MedicineBundle:Report:purchaseBrandSales" }


medicine_report_purchase_brand_sales_details:
    path:     /purchase-brand-sales-details
    defaults: { _controller: "MedicineBundle:Report:purchaseBrandSalesDetails" }


medicine_report_product_stock_sales:
    path:     /product-vendor-stock-sales
    defaults: { _controller: "MedicineBundle:Report:productPurchaseStockSales" }

medicine_report_product_stock_sales_price:
    path:     /product-brand-stock-sales-price
    defaults: { _controller: "MedicineBundle:Report:productPurchaseStockSalesPrice" }


medicine_report_purchase_details:
    path:     /purchase-vendor
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }

medicine_report_purchase_item:
    path:     /purchase-item-report
    defaults: { _controller: "MedicineBundle:Report:purchaseItemReport" }


medicine_report_remaining_stock:
    path:     /remaining-stock-report
    defaults: { _controller: "MedicineBundle:Report:remainingStockReport" }

medicine_report_purchase_stock:
    path:     /purchase-vendor
    defaults: { _controller: "MedicineBundle:Report:purchaseVendor" }

medicine_system_overview:
    path:     /system-overview
    defaults: { _controller: "MedicineBundle:Report:systemOverview" }

medicine_system_overview_pdf:
    path:     /system-overview-pdf
    defaults: { _controller: "MedicineBundle:Report:systemOverviewPdf" }

medicine_report_sales_summary:
    path:     /sales-overview
    defaults: { _controller: "MedicineBundle:Report:salesOverview" }

medicine_report_sales_details:
    path:     /sales-details
    defaults: { _controller: "MedicineBundle:Report:salesDetails" }

medicine_report_sales_daily:
    path:     /sales-daily-wise
    defaults: { _controller: "MedicineBundle:Report:salesDayBase" }

medicine_report_sales_stock:
    path:     /sales-stock
    defaults: { _controller: "MedicineBundle:Report:salesStockItem" }

medicine_report_brand_stock:
    path:     /brand-stock
    defaults: { _controller: "MedicineBundle:Report:brandStock" }

medicine_report_brand_stock_pdf:
    path:     /brand-stock-pdf
    defaults: { _controller: "MedicineBundle:Report:brandStockPdf" }

medicine_report_sales_user:
    path:     /sales-user
    defaults: { _controller: "MedicineBundle:Report:salesUser" }

medicine_report_sales_user_monthly:
    path:     /sales-user-monthly
    defaults: { _controller: "MedicineBundle:Report:monthlyUserSales" }



