medicine_reverse:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineReverse:index" }

medicine_purchase_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "MedicineBundle:Purchase:reverse" }

medicine_reverse_purchase_show:
    path:     /{id}/purchase
    defaults: { _controller: "MedicineBundle:Purchase:reversePurchase" }

medicine_sales_reverse:
    path:     /{id}/
    defaults: { _controller: "MedicineBundle:Sales:reverse" }

medicine_reverse_sales_show:
    path:     /{id}/sales
    defaults: { _controller: "MedicineBundle:MedicineReverse:reverseSales" }

