medicine_sales_return:
    path:     /
    defaults: { _controller: "MedicineBundle:SalesReturn:index" }

medicine_sales_customer_item:
    path:     /customer-sales-item
    defaults: { _controller: "MedicineBundle:SalesReturn:customerItem" }

medicine_sales_customer_return_invoice:
    path:     /sales-return-invoice
    defaults: { _controller: "MedicineBundle:SalesReturn:salesReturnInvoice" }


medicine_sales_return_group_item:
    path:     /group-item-new
    defaults: { _controller: "MedicineBundle:SalesReturn:groupItemNew" }
    methods:  POST

medicine_sales_return_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:SalesReturn:create" }
    methods:  POST

medicine_sales_return_new:
    path:     /{id}/new
    defaults: { _controller: "MedicineBundle:SalesReturn:new" }


medicine_sales_return_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:SalesReturn:delete" }

medicine_sales_return_approve:
    path:     /{id}/approve
    defaults: { _controller: "MedicineBundle:SalesReturn:approve" }

medicine_sales_return_invoice_show:
    path:     /{id}/show-invoice
    defaults: { _controller: "MedicineBundle:SalesReturn:showInvoice" }

medicine_sales_return_invoice_print:
    path:     /{id}/print-invoice
    defaults: { _controller: "MedicineBundle:SalesReturn:printInvoice" }

medicine_sales_return_invoice_delete:
    path:     /{id}/delete-invoice
    defaults: { _controller: "MedicineBundle:SalesReturn:deleteInvoice" }

medicine_sales_return_invoice_approve:
    path:     /{id}/approve-invoice
    defaults: { _controller: "MedicineBundle:SalesReturn:approveInvoice" }