medicine_sales_temporary_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:new" }
    options:
            expose: true

medicine_sales_temporary_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:create" }
    methods:  POST


medicine_sales_temporary_item_add:
    path:     /medicine-add
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:addParticular" }
    methods:  POST
    options:
            expose: true

medicine_sales_temporary_item_ajax:
    path:     /{id}/medicine-add-ajax
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:addAjaxLive" }
    methods:  POST
    options:
            expose: true

medicine_stock_item_sales_create:
    path:     /medicine-stock-create
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:stockItemCreate" }
    methods:  POST
    options:
            expose: true

medicine_sales_barcode_search:
    path:     /barcode-add
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:addBarcode" }
    methods:  GET
    options:
            expose: true

medicine_sales_temporary_search:
    path:     /live-search-add-stock
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:liveSearchSales" }
    options:
            expose: true

medicine_sales_generic_stock:
    path:     /{id}/generic-stock-item
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:addGenericStock" }
    methods:  GET
    options:
            expose: true

medicine_sales_temporary_generic_item:
    path:     /{id}/generic-stock-item-add
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:addGenericStockItem" }
    methods:  POST
    options:
            expose: true


medicine_sales_temporary_discount_update:
    path:     /dicount-update
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

medicine_sales_temporary_item_update:
    path:     /sales-item-update
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:invoiceItemUpdate" }
    methods:  POST
    options:
            expose: true

medicine_sales_temporary_item_delete:
    path:     /{id}/item-delete
    defaults: { _controller: "MedicineBundle:MedicineSalesTemporary:invoiceParticularDelete" }

