medicine_stock:
    path:     /
    defaults: { _controller: "MedicineBundle:MedicineStock:index" }

medicine_stock_selected_preview:
    path:     /stock-selected-preview
    defaults: { _controller: "MedicineBundle:MedicineStock:selectedPreview" }
    options:
            expose: true

medicine_stock_refresh:
    path:     /stock-global-search
    defaults: { _controller: "MedicineBundle:MedicineStock:selectedRefresh" }

medicine_stock_global:
    path:     /stock-global-search
    defaults: { _controller: "MedicineBundle:MedicineStock:stockSearch" }

medicine_stock_short_item:
    path:     /item-short-list
    defaults: { _controller: "MedicineBundle:MedicineStock:itemShortList" }

medicine_stock_current_short_item:
    path:     /daily-item-short-list
    defaults: { _controller: "MedicineBundle:MedicineStock:currentShortList" }

medicine_stock_adjustment_close:
    path:     /{id}/item-short-close
    defaults: { _controller: "MedicineBundle:MedicineStock:shortItemClose" }

medicine_stock_item_history:
    path:     /item-history
    defaults: { _controller: "MedicineBundle:MedicineStock:stockItemHistory" }

medicine_stock_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:MedicineStock:show" }

medicine_stock_rack:
    path:     /rack-no
    defaults: { _controller: "MedicineBundle:MedicineStock:rackSelect" }

medicine_stock_select_brand:
    path:     /select-brand
    defaults: { _controller: "MedicineBundle:MedicineStock:brandSelect" }

medicine_stock_new:
    path:     /new
    defaults: { _controller: "MedicineBundle:MedicineStock:new" }

medicine_stock_create:
    path:     /create
    defaults: { _controller: "MedicineBundle:MedicineStock:create" }
    methods:  POST

medicine_stock_accesories_new:
    path:     /new-accessories
    defaults: { _controller: "MedicineBundle:MedicineStock:accessories" }

medicine_stock_accessories_create:
    path:     /create-accessories
    defaults: { _controller: "MedicineBundle:MedicineStock:accessoriesCreate" }
    methods:  POST

medicine_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "MedicineBundle:MedicineStock:edit" }


medicine_stock_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineStock:update" }
    methods:  [POST, PUT]

medicine_stock_accessories_update:
    path:     /{id}/update
    defaults: { _controller: "MedicineBundle:MedicineStock:update" }
    methods:  [POST, PUT]

medicine_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:MedicineStock:delete" }
    options:
            expose: true

medicine_stock_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:MedicineStock:status" }

medicine_stock_inline:
    path:     /inline-update
    defaults: { _controller: "MedicineBundle:MedicineStock:inlineUpdate" }

medicine_stock_price:
    path:     /stock-update-price
    defaults: { _controller: "MedicineBundle:MedicineStock:stockPriceUpdate" }

medicine_stock_update_quantity:
    path:     /stock-update-quantity
    defaults: { _controller: "MedicineBundle:MedicineStock:stockQuantityUpdate" }

medicine_stock_details:
    path:     /{sku}/stock-details
    defaults: { _controller: "MedicineBundle:MedicineStock:inlineUpdate" }

medicine_stock_web:
    path:     /{id}/web-item
    defaults: { _controller: "MedicineBundle:MedicineStock:isWeb" }

medicine_stock_search:
    path:     /search
    defaults: { _controller: "MedicineBundle:MedicineStock:autoSearch" }
    options:
            expose: true

medicine_stock_purchase_search:
    path:     /purchase-search
    defaults: { _controller: "MedicineBundle:MedicineStock:autoPurchaseStockSearch" }
    options:
            expose: true

medicine_stock_name_search:
    path:     /search-name
    defaults: { _controller: "MedicineBundle:MedicineStock:autoNameSearch" }
    options:
            expose: true

medicine_generic_stock_search:
    path:     /generic-stock-item
    defaults: { _controller: "MedicineBundle:MedicineStock:autoGenericSearch" }
    options:
            expose: true

medicine_stock_select2_item:
    path:      /{stock}/select2-item
    defaults: { _controller: "MedicineBundle:MedicineStock:searchStockItem" }
    options:
            expose: true

medicine_stock_name:
    path:      /{stock}/name
    defaults: { _controller: "MedicineBundle:MedicineStock:searchName" }
    options:
            expose: true

medicine_stock_brand_search:
    path:     /search-brand
    defaults: { _controller: "MedicineBundle:MedicineStock:autoSearchBrand" }
    options:
            expose: true

medicine_stock_brand_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "MedicineBundle:MedicineStock:searchBrandName" }
    options:
            expose: true