medicine_stockhouse:
    path:     /
    defaults: { _controller: "MedicineBundle:StockHouse:index" }

medicine_stockhouse_details:
    path:     /stock-house-details
    defaults: { _controller: "MedicineBundle:StockHouse:stockDetails" }

medicine_stockhouse_search:
    path:     /search
    defaults: { _controller: "MedicineBundle:StockHouse:autoSearch" }
    options:
            expose: true

medicine_stockhouse_in:
    path:     /stock-in
    defaults: { _controller: "MedicineBundle:StockHouse:stockIn" }

medicine_stockhouse_out:
    path:     /stock-out
    defaults: { _controller: "MedicineBundle:StockHouse:stockOut" }

medicine_stockhouse_in_create:
    path:     /create-stock-in
    defaults: { _controller: "MedicineBundle:StockHouse:createIn" }
    methods:  POST

medicine_stockhouse_out_create:
    path:     /create-stock-out
    defaults: { _controller: "MedicineBundle:StockHouse:createOut" }
    methods:  POST

medicine_stockhouse_show:
    path:     /{id}/show
    defaults: { _controller: "MedicineBundle:StockHouse:show" }

medicine_stockhouse_status:
    path:     /{id}/status
    defaults: { _controller: "MedicineBundle:StockHouse:status" }

medicine_stockhouse_delete:
    path:     /{id}/delete
    defaults: { _controller: "MedicineBundle:StockHouse:delete" }
