adstool:
    path:     /
    defaults: { _controller: "SettingToolBundle:AdsTool:index" }

adstool_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:AdsTool:show" }

adstool_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:AdsTool:new" }

adstool_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:AdsTool:create" }
    methods:  POST

adstool_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:AdsTool:edit" }

adstool_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:AdsTool:update" }
    methods:  [POST, PUT]

adstool_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:AdsTool:delete" }
    methods:  [POST, DELETE]
