applicationpricing:
    path:     /
    defaults: { _controller: "SettingToolBundle:ApplicationPricing:index" }

applicationpricing_inline_app:
    path:     /inline-app
    defaults: { _controller: "SettingToolBundle:ApplicationPricing:inlineApp" }
    methods:  POST

applicationpricing_inline_syndicate:
    path:     /inline-syndicate
    defaults: { _controller: "SettingToolBundle:ApplicationPricing:inlineSyndicate" }
    methods:  POST

applicationpricing_inline_module:
    path:     /inline-module
    defaults: { _controller: "SettingToolBundle:ApplicationPricing:inlineModule" }
    methods:  POST

