applicationtestimonial:
    path:     /
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:index" }

applicationtestimonial_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:show" }

applicationtestimonial_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:new" }

applicationtestimonial_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:create" }
    methods:  POST

applicationtestimonial_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:status" }

applicationtestimonial_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:edit" }

applicationtestimonial_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:update" }
    methods:  [POST, PUT]

applicationtestimonial_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:ApplicationTestimonial:delete" }
