appmodule:
    path:     /
    defaults: { _controller: "SettingToolBundle:AppModule:index" }

appmodule_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:AppModule:show" }

appmodule_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:AppModule:new" }

appmodule_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:AppModule:create" }
    methods:  POST

appmodule_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:AppModule:edit" }

appmodule_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:AppModule:update" }
    methods:  [POST, PUT]

appmodule_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:AppModule:delete" }

appmodule_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:AppModule:status" }

