barcode:
    path:     /
    defaults: { _controller: "SettingToolBundle:BarCode:barcode" }

barcode_image:
    path:     /{id}/barcode-image
    defaults: { _controller: "SettingToolBundle:BarCode:barcodeImage" }

barcode_html:
    path:     /{id}/barcode-html
    defaults: { _controller: "SettingToolBundle:BarCode:barcodeHtml" }

barcode_text:
    path:     /{id}/barcode-text
    defaults: { _controller: "SettingToolBundle:BarCode:barcodeText" }


