branding:
    path:     /
    defaults: { _controller: "SettingToolBundle:Branding:index" }

branding_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:Branding:show" }

branding_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Branding:new" }

branding_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Branding:create" }
    methods:  POST

branding_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Branding:edit" }

branding_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:Branding:status" }

branding_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Branding:update" }
    methods:  [POST, PUT]

branding_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Branding:delete" }
    methods:  [POST, DELETE]

branding_search:
    path:     /search
    defaults: { _controller: "SettingToolBundle:Branding:autoSearch" }
    options:
            expose: true

branding_search_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "SettingToolBundle:Branding:searchBrandName" }
    options:
            expose: true