hms_category:
    path:     /
    defaults: { _controller: "HospitalBundle:Category:index" }

hms_category_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:Category:show" }

hms_category_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:Category:new" }

hms_category_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Category:create" }
    requirements: { _method: post }

hms_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Category:edit" }

hms_category_sorting:
    path:     /sorting
    defaults: { _controller: "HospitalBundle:Category:sorting" }

hms_category_sorted:
    path:     /sorted
    defaults: { _controller: "HospitalBundle:Category:sorted" }

hms_category_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Category:update" }
    requirements: { _method: post|put }

hms_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Category:delete" }

hms_category_feature:
   path:     /feature
   defaults: { _controller: "HospitalBundle:Category:feature" }
   requirements: { _method: post }

hms_category_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Category:status" }