designation:
    path:     /
    defaults: { _controller: "SettingToolBundle:Designation:index" }

designation_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:Designation:show" }

designation_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Designation:new" }

designation_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Designation:create" }
    methods:  POST

designation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Designation:edit" }

designation_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Designation:update" }
    methods:  [POST, PUT]

designation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Designation:delete" }
    methods:  [POST, DELETE]


