footersetting:
    path:     /
    defaults: { _controller: "SettingToolBundle:FooterSetting:index" }

footersetting_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:FooterSetting:show" }

footersetting_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:FooterSetting:new" }

footersetting_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:FooterSetting:create" }
    methods:  POST

footersetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:FooterSetting:edit" }

footersetting_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:FooterSetting:update" }
    methods:  [POST, PUT]

footersetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:FooterSetting:delete" }
    methods:  [POST, DELETE]
