globaloption:
    path:     /
    defaults: { _controller: "SettingToolBundle:GlobalOption:index" }

globaloption_vendor_search:
    path:     /vendor/search
    defaults: { _controller: "SettingToolBundle:GlobalOption:vendorSearch" }
    options:
            expose: true

globaloption_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:GlobalOption:show" }

globaloption_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:GlobalOption:new" }

globaloption_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:GlobalOption:create" }
    requirements: { _method: post }

globaloption_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:GlobalOption:edit" }

globaloption_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:GlobalOption:update" }
    requirements: { _method: post|put }

globaloption_modify_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:GlobalOption:update" }
    requirements: { _method: post|put }

globaloption_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:GlobalOption:delete" }

globaloption_modify:
    path:     /modify
    defaults: { _controller: "SettingToolBundle:GlobalOption:modify" }


globaloption_webmail:
    path:     /webmail
    defaults: { _controller: "SettingToolBundle:GlobalOption:webmail" }


