institutelevel:
    path:     /
    defaults: { _controller: "SettingToolBundle:InstituteLevel:index" }

institutelevel_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:InstituteLevel:show" }

institutelevel_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:InstituteLevel:new" }

institutelevel_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:InstituteLevel:create" }
    methods:  POST

institutelevel_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:InstituteLevel:edit" }

institutelevel_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:InstituteLevel:status" }

institutelevel_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:InstituteLevel:update" }
    methods:  [POST, PUT]

institutelevel_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:InstituteLevel:delete" }
    methods:  [POST, DELETE]
