invoicemodule:
    path:     /
    defaults: { _controller: "SettingToolBundle:InvoiceModule:index" }

invoicemodule_domain:
    path:     /domain-invoice
    defaults: { _controller: "SettingToolBundle:InvoiceModule:domain" }

invoicemodule_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:InvoiceModule:show" }

invoicemodule_add:
    path:      /add-invoice
    defaults: { _controller: "SettingToolBundle:InvoiceModule:addInvoice" }

invoicemodule_new:
    path:      /{option}/new
    defaults: { _controller: "SettingToolBundle:InvoiceModule:new" }


invoicemodule_edit:
    path:     /{invoice}/edit
    defaults: { _controller: "SettingToolBundle:InvoiceModule:edit" }

invoicemodule_modify:
    path:     /{id}/modify
    defaults: { _controller: "SettingToolBundle:InvoiceModule:modify" }

invoicemodule_print:
    path:     /{id}/print
    defaults: { _controller: "SettingToolBundle:InvoiceModule:print" }

invoicemodule_generate:
    path:     /{invoice}/generate-invoice
    defaults: { _controller: "SettingToolBundle:InvoiceModule:generateInvoice" }

invoicemodule_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:InvoiceModule:update" }
    methods:  [POST, PUT]

invoicemodule_ajax_payment:
    path:     /{id}/payment
    defaults: { _controller: "SettingToolBundle:InvoiceModule:payment" }
    methods:  [POST, PUT]

invoicemodule_delete:
    path:     /{invoice}/delete
    defaults: { _controller: "SettingToolBundle:InvoiceModule:delete" }

invoicemodule_item_delete:
    path:     /{invoice}/{item}/delete
    defaults: { _controller: "SettingToolBundle:InvoiceModule:deleteItem" }

invoicemodule_approve:
    path:     /{id}/invoice-approve
    defaults: { _controller: "SettingToolBundle:InvoiceModule:approve" }

invoicemodule_inline_upate:
    path:     /inline-invoice-module
    defaults: { _controller: "SettingToolBundle:InvoiceModule:inlineUpdate" }
    methods:  POST