invoicesmsemail:
    path:     /
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:index" }

invoicesmsemail_domain:
    path:     /domain-invoice
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:domain" }

invoicesmsemail_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:show" }

invoicesmsemail_new:
    path:      /{option}/new
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:new" }

invoicesmsemail_edit:
    path:     /{invoice}/edit
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:edit" }

invoicesmsemail_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:update" }
    methods:  [POST, PUT]

invoicesmsemail_ajax_payment:
    path:     /{id}/payment
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:payment" }
    methods:  [POST, PUT]

invoicesmsemail_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:delete" }

invoicesmsemail_item_delete:
    path:     /{invoice}/{package}/item-delete
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:deleteItem" }

invoicesmsemail_approve:
    path:     /{id}/invoice-approve
    defaults: { _controller: "SettingToolBundle:InvoiceSmsEmail:approve" }

