medicinebrand:
    path:     /
    defaults: { _controller: "SettingToolBundle:Medicine:index" }

medicinebrand_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Medicine:new" }

medicinebrand_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Medicine:create" }
    methods:  POST

medicinebrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Medicine:edit" }

medicinebrand_copy:
    path:     /{id}/copy
    defaults: { _controller: "SettingToolBundle:Medicine:copy" }

medicinebrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Medicine:delete" }

medicinebrand_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:Medicine:status" }

medicinebrand_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Medicine:update" }
    methods:  [POST, PUT]

medicinebrand_select_search:
    path:     /select-medicine-search
    defaults: { _controller: "SettingToolBundle:Medicine:selectSearchMedicine" }
    options:
            expose: true

medicinebrand_search:
    path:     /medicine-search
    defaults: { _controller: "SettingToolBundle:Medicine:autoSearchMedicine" }
    options:
            expose: true

medicinebrand_details:
    path:     /medicine-details
    defaults: { _controller: "SettingToolBundle:Medicine:medicineDetails" }
    options:
            expose: true

medicinebrand_generic_search:
    path:     /generic-search
    defaults: { _controller: "SettingToolBundle:Medicine:autoSearchGeneric" }
    options:
            expose: true

medicinebrand_name:
    path:      /{medicine}/medicine-name
    defaults: { _controller: "SettingToolBundle:Medicine:searchProductName" }
    options:
            expose: true


medicinebrand_search_brand_name_complete:
    path:     /search-brand-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchBrandNameAutoComplete" }
    options:
            expose: true

medicinebrand_search_company_name_complete:
    path:     /search-company-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchCompanyNameAutoComplete" }
    options:
            expose: true

medicinebrand_search_generic_name_complete:
    path:     /search-generic-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchGenericNameAutoComplete" }
    options:
            expose: true

medicinebrand_search_pack_size_name_complete:
    path:     /search-pack-size-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchPackSizeAutoComplete" }
    options:
            expose: true

medicinebrand_search_strength_name_complete:
    path:     /search-strength-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchStrengthAutoComplete" }
    options:
            expose: true

medicinebrand_search_form_name_complete:
    path:     /search-form-name-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchMedicineFormAutoComplete" }
    options:
            expose: true

medicinebrand_search_medicine_generic_complete:
    path:     /search-generic-medicine-auto-complete
    defaults: { _controller: "SettingToolBundle:Medicine:searchMedicineGenericNameAutoComplete" }
    options:
            expose: true


medicinebrand_select_medicine_form:
    path:     /inline-select-medicine-form
    defaults: { _controller: "SettingToolBundle:Medicine:selectMedicineForm" }
    options:
           expose: true

medicinebrand_select_strength:
    path:     /inline-select-strength
    defaults: { _controller: "SettingToolBundle:Medicine:selectStrength" }
    options:
           expose: true

medicinebrand_item_inline_update:
    path:     /inline-product-update
    defaults: { _controller: "SettingToolBundle:Medicine:inlineItemUpdate" }
    methods:  POST
    options:
            expose: true
