medicine_import:
    path:     /
    defaults: { _controller: "SettingToolBundle:MedicineImport:index" }

medicine_import_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "SettingToolBundle:MedicineImport:excelDataImport" }

medicine_import_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:MedicineImport:new" }

medicine_import_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:MedicineImport:create" }
    methods:  POST

medicine_import_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:MedicineImport:delete" }


medicine_file_upload:
    path:     /medicine/upload
    defaults: { _controller: "SettingToolBundle:MedicineImport:upload" }

medicine_upload_create:
    path:     /medicine/upload/create
    defaults: { _controller: "SettingToolBundle:MedicineImport:uploadCreate" }

