mobileicon:
    path:     /
    defaults: { _controller: "SettingToolBundle:MobileIcon:index" }

mobileicon_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:MobileIcon:show" }

mobileicon_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:MobileIcon:new" }

mobileicon_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:MobileIcon:create" }
    methods:  POST

mobileicon_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:MobileIcon:edit" }

mobileicon_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:MobileIcon:update" }
    methods:  [POST, PUT]

mobileicon_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:MobileIcon:delete" }
    methods:  [POST, DELETE]
