mobiletheme:
    path:     /
    defaults: { _controller: "SettingToolBundle:MobileTheme:index" }

mobiletheme_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:MobileTheme:show" }

mobiletheme_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:MobileTheme:new" }

mobiletheme_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:MobileTheme:create" }
    requirements: { _method: post }

mobiletheme_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:MobileTheme:edit" }

mobiletheme_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:MobileTheme:update" }
    requirements: { _method: post|put }

mobiletheme_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:MobileTheme:delete" }
    requirements: { _method: post|delete }

mobiletheme_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:MobileTheme:status" }

