module:
    path:     /
    defaults: { _controller: "SettingToolBundle:Module:index" }

module_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:Module:show" }

module_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Module:new" }

module_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Module:create" }
    requirements: { _method: post }


module_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Module:edit" }

module_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Module:update" }
    requirements: { _method: post|put }

module_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Module:delete" }
    requirements: { _method: post|delete }

module_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:Module:status" }

