bankaccount:
    path:     /
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:index" }

bankaccount_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:show" }

bankaccount_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:new" }

bankaccount_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:create" }
    methods:  POST

bankaccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:edit" }

bankaccount_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:status" }

bankaccount_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:update" }
    methods:  [POST, PUT]

bankaccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:PortalBankAccount:delete" }

