mobilebankaccount:
    path:     /
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:index" }

mobilebankaccount_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:show" }

mobilebankaccount_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:new" }

mobilebankaccount_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:create" }
    methods:  POST

mobilebankaccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:edit" }

mobilebankaccount_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:status" }


mobilebankaccount_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:update" }
    methods:  [POST, PUT]

mobilebankaccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:PortalMobileBankAccount:delete" }
