sidebar_widget:
    path:     /
    defaults: { _controller: "SettingToolBundle:SidebarWidget:index" }

sidebar_widget_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:SidebarWidget:show" }

sidebar_widget_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SidebarWidget:new" }

sidebar_widget_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SidebarWidget:create" }
    methods:  POST

sidebar_widget_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SidebarWidget:edit" }

sidebar_widget_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SidebarWidget:update" }
    methods:  [POST, PUT]

sidebar_widget_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:SidebarWidget:delete" }
    methods:  [POST, DELETE]
