sitesetting:
    path:     /
    defaults: { _controller: "SettingToolBundle:SiteSetting:index" }

sitesetting_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:SiteSetting:show" }

sitesetting_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SiteSetting:new" }

sitesetting_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SiteSetting:create" }
    requirements: { _method: post }

sitesetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SiteSetting:edit" }

sitesetting_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SiteSetting:update" }
    requirements: { _method: post|put }

sitesetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:SiteSetting:delete" }
    requirements: { _method: post|delete }

sitesetting_modify:
    path:     /modify
    defaults: { _controller: "SettingToolBundle:SiteSetting:modify" }