smsbulk:
    path:     /
    defaults: { _controller: "SettingToolBundle:SmsBulk:index" }

smsbulk_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:SmsBulk:show" }

smsbulk_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SmsBulk:new" }

smsbulk_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SmsBulk:create" }
    requirements: { _method: post }

smsbulk_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SmsBulk:edit" }

smsbulk_send_msg:
    path:     /{id}/send-msg
    defaults: { _controller: "SettingToolBundle:SmsBulk:sending" }

smsbulk_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SmsBulk:update" }
    requirements: { _method: post|put }

smsbulk_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:SmsBulk:delete" }

smsbulk_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:SmsBulk:status" }

