smspricing:
    path:     /
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:index" }

smspricing_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:show" }

smspricing_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:new" }

smspricing_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:create" }
    methods:  POST

smspricing_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:edit" }

smspricing_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:update" }
    methods:  [POST, PUT]

smspricing_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:delete" }

smspricing_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:SmsEmailPricing:status" }

