smssender:
    path:     /
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }

smssender_delete:
    path:     /delete
    defaults: { _controller: "SettingToolBundle:SmsSender:delete" }

smssender_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }

smssender_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }
    requirements: { _method: post }

smssender_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }

smssender_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SmsSender:index" }
    requirements: { _method: post|put }




