syndicatemodule:
    path:     /
    defaults: { _controller: "SettingToolBundle:SyndicateModule:index" }

syndicatemodule_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:SyndicateModule:show" }

syndicatemodule_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:SyndicateModule:new" }

syndicatemodule_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:SyndicateModule:create" }
    requirements: { _method: post }

syndicatemodule_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:SyndicateModule:edit" }

syndicatemodule_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:SyndicateModule:update" }
    requirements: { _method: post|put }

syndicatemodule_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:SyndicateModule:delete" }
    requirements: { _method: post|delete }

syndicatemodule_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:SyndicateModule:status" }


