syndicate:
    path:     /
    defaults: { _controller: "SettingToolBundle:Syndicate:index" }

syndicate_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:Syndicate:show" }

syndicate_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Syndicate:new" }

syndicate_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Syndicate:create" }
    requirements: { _method: post }

syndicate_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Syndicate:edit" }

syndicate_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Syndicate:update" }
    requirements: { _method: post|put }

syndicate_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Syndicate:delete" }

syndicate_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:Syndicate:status" }

