taxtariff:
    path:     /
    defaults: { _controller: "TallyBundle:TaxTariff:index" }

taxtariff_show:
    path:     /{id}/show
    defaults: { _controller: "TallyBundle:TaxTariff:show" }

taxtariff_new:
    path:     /new
    defaults: { _controller: "TallyBundle:TaxTariff:new" }

taxtariff_create:
    path:     /create
    defaults: { _controller: "TallyBundle:TaxTariff:create" }
    methods:  POST

taxtariff_edit:
    path:     /{id}/edit
    defaults: { _controller: "TallyBundle:TaxTariff:edit" }


taxtariff_update:
    path:     /{id}/update
    defaults: { _controller: "TallyBundle:TaxTariff:update" }
    methods:  [POST, PUT]


taxtariff_inline_update:
    path:     /{id}/inline-update
    defaults: { _controller: "TallyBundle:TaxTariff:inlineUpdate" }
    methods:  POST
    options:
            expose: true

taxtariff_delete:
    path:     /{id}/delete
    defaults: { _controller: "TallyBundle:TaxTariff:delete" }

taxtariff_status:
    path:     /{id}/status
    defaults: { _controller: "TallyBundle:TaxTariff:status" }


tallyitem_item_search:
    path:     /search-tariff
    defaults: { _controller: "TallyBundle:TaxTariff:autoSearch" }
    options:
            expose: true

tallyitem_item_name:
    path:      /{name}/tariff-name
    defaults: { _controller: "TallyBundle:TaxTariff:searchName" }
    options:
            expose: true