tarrif_upload:
    path:     /
    defaults: { _controller: "SettingToolBundle:TaxUpload:index" }

tarrif_upload_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:TaxUpload:new" }

tarrif_upload_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:TaxUpload:create" }
    requirements: { _method: post }

tarrif_upload_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:TaxUpload:delete" }

tarrif_upload_migration:
    path:     /{id}/migration
    defaults: { _controller: "SettingToolBundle:TaxUpload:excelDataImport" }

