templating:
    path:     /
    defaults: { _controller: "SettingToolBundle:Templating:index" }

templating_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:Templating:show" }

templating_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:Templating:new" }

templating_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:Templating:create" }
    methods:  POST

templating_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:Templating:edit" }

templating_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:Templating:update" }
    methods:  [POST, PUT]

templating_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:Templating:delete" }
    methods:  [POST, DELETE]
