transactionmethod:
    path:     /
    defaults: { _controller: "SettingToolBundle:TransactionMethod:index" }

transactionmethod_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:TransactionMethod:show" }

transactionmethod_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:TransactionMethod:new" }

transactionmethod_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:TransactionMethod:create" }
    methods:  POST

transactionmethod_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:TransactionMethod:edit" }

transactionmethod_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:TransactionMethod:status" }

transactionmethod_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:TransactionMethod:update" }
    methods:  [POST, PUT]

transactionmethod_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:TransactionMethod:delete" }
    methods:  [POST, DELETE]
