webtheme:
    path:     /
    defaults: { _controller: "SettingToolBundle:WebTheme:index" }

webtheme_show:
    path:     /{id}/show
    defaults: { _controller: "SettingToolBundle:WebTheme:show" }

webtheme_new:
    path:     /new
    defaults: { _controller: "SettingToolBundle:WebTheme:new" }

webtheme_create:
    path:     /create
    defaults: { _controller: "SettingToolBundle:WebTheme:create" }
    requirements: { _method: post }

webtheme_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingToolBundle:WebTheme:edit" }

webtheme_update:
    path:     /{id}/update
    defaults: { _controller: "SettingToolBundle:WebTheme:update" }
    requirements: { _method: post|put }

webtheme_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingToolBundle:WebTheme:delete" }
    requirements: { _method: post|delete }

webtheme_status:
    path:     /{id}/status
    defaults: { _controller: "SettingToolBundle:WebTheme:status" }


