<?php

namespace Appstore\Bundle\MedicineBundle\Service;


/**
 * RequestManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class HtmlToImage {

    public function __construct($name = '', $quantity = '', $price = '', $dollarSign = false) {
        $this -> name = $name;
        $this -> quantity = $quantity;
        $this -> price = $price;
        $this -> dollarSign = $dollarSign;
    }

}
