dps_expense:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/expenditure.yml"
    prefix:   /dps-expense

dps_expensecategory:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/expensecategory.yml"
    prefix:   /dps-expense-category

dps_report:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/report.yml"
    prefix:   /report

dps_treatment_accessories:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/treatmentaccessories.yml"
    prefix:   /treatment-accessories


dps_invoice:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

dps_prescription:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/prescription.yml"
    prefix:   /prescription

dps_particular:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

dps_service:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/service.yml"
    prefix:   /service

dps_treatment:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/treatment.yml"
    prefix:   /treatment-plan

dps_doctor:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/doctor.yml"
    prefix:   /doctor

dps_diseases:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/diseases.yml"
    prefix:   /diseases

dps_config:
    resource: "@DoctorPrescriptionBundle/Resources/config/routing/config.yml"
    prefix:   /config

dps_homepage:
    path:     /dashoard
    defaults: { _controller: DoctorPrescriptionBundle:Default:index }
