hotel_purchase:
    path:     /
    defaults: { _controller: "HotelBundle:Purchase:index" }

hotel_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "HotelBundle:Purchase:show" }

hotel_purchase_new:
    path:     /new
    defaults: { _controller: "HotelBundle:Purchase:new" }

hotel_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "HotelBundle:Purchase:edit" }

hotel_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "HotelBundle:Purchase:update" }
    methods:  [POST, PUT]

hotel_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "HotelBundle:Purchase:edit" }


hotel_purchase_approve:
    path:     /{id}/approve
    defaults: { _controller: "HotelBundle:Purchase:approve" }

hotel_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "HotelBundle:Purchase:delete" }

hotel_purchase_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "HotelBundle:Purchase:particularSearch" }


hotel_purchase_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "HotelBundle:Purchase:addParticular" }
    methods:  POST
    options:
            expose: true

hotel_purchase_discount_update:
    path:     /purchase/dicount-update
    defaults: { _controller: "HotelBundle:Purchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

hotel_purchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "HotelBundle:Purchase:approved" }


hotel_purchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "HotelBundle:Purchase:invoiceParticularDelete" }

hotel_purchase_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "HotelBundle:Purchase:invoicePrint" }