location:
    path:     /
    defaults: { _controller: "SettingLocationBundle:Location:index" }

location_show:
    path:     /{id}/show
    defaults: { _controller: "SettingLocationBundle:Location:show" }

location_new:
    path:     /new
    defaults: { _controller: "SettingLocationBundle:Location:new" }

location_create:
    path:     /create
    defaults: { _controller: "SettingLocationBundle:Location:create" }
    methods:  POST

location_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingLocationBundle:Location:edit" }

location_update:
    path:     /{id}/update
    defaults: { _controller: "SettingLocationBundle:Location:update" }
    methods:  [POST, PUT]

location_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingLocationBundle:Location:delete" }
    methods:  [POST, DELETE]

location_search:
    path:     /location-auto-search
    defaults: { _controller: "SettingLocationBundle:Location:autoSearch" }
    options:
           expose: true

