parameters:
#    setting_appearance.example.class: Setting\Bundle\AppearanceBundle\Example

services:
#    setting_appearance.example:
#        class: %setting_appearance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


 setting.menuSettingRepo:
        class: Setting\Bundle\AppearanceBundle\Service\MenuManager
        arguments: [@doctrine]

 setting.menuGroupingRepo:
        class: Setting\Bundle\AppearanceBundle\Service\MenuGroupingManager
        arguments: [@doctrine]

 setting.moduleSetupRepo:
        class: Setting\Bundle\AppearanceBundle\Service\ModuleManager
        arguments: [@doctrine]
