# FOS User Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Core\UserBundle\Entity\User
    group:
          group_class: Core\UserBundle\Entity\Group
    registration:
            form:
                type: Core_userbundle_user