stof_doctrine_extensions:
    default_locale: en_US
    uploadable: ~
    class:
        uploadable:     Core\UserBundle\Listener\UploadableListener
    orm:
        default:
            tree: true
            timestampable: true
            blameable:      true
            sluggable:      true
            softdeleteable:      true
            uploadable:      true