restaurant_category:
    path:     /
    defaults: { _controller: "RestaurantBundle:Category:index" }

restaurant_category_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Category:create" }
    methods:  POST

restaurant_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Category:edit" }

restaurant_category_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Category:update" }
    methods:  [POST, PUT]

restaurant_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Category:delete" }

restaurant_category_status:
    path:     /{id}/status
    defaults: { _controller: "RestaurantBundle:Category:status" }

restaurant_category_sorted:
    path:     /category-sorted
    defaults: { _controller: "RestaurantBundle:Category:sorted" }

