restaurant_config_manage:
    path:     /manage
    defaults: { _controller: "RestaurantBundle:RestaurantConfig:manage" }

restaurant_config_update:
    path:     /update
    defaults: { _controller: "RestaurantBundle:RestaurantConfig:update" }
    methods:  [POST, PUT]

