restaurant_damage:
    path:     /
    defaults: { _controller: "RestaurantBundle:Damage:index" }

restaurant_damage_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:Damage:new" }

restaurant_damage_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Damage:create" }
    methods:  POST

restaurant_damage_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Damage:edit" }

restaurant_damage_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Damage:update" }
    methods:  [POST, PUT]

restaurant_damage_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Damage:delete" }

restaurant_damage_approve:
    path:     /{id}/approved
    defaults: { _controller: "RestaurantBundle:Damage:approved" }


