restaurant_itemimporter:
    path:     /
    defaults: { _controller: "RestaurantBundle:ItemImporter:index" }

restaurant_itemimporter_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "RestaurantBundle:ItemImporter:excelDataImport" }

restaurant_itemimporter_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:ItemImporter:new" }

restaurant_itemimporter_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:ItemImporter:create" }
    methods:  POST

restaurant_itemimporter_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:ItemImporter:edit" }

restaurant_itemimporter_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:ItemImporter:update" }
    methods:  [POST, PUT]

restaurant_itemimporter_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:ItemImporter:delete" }


restaurant_itemimporter_updated:
    path:     /{id}/data-updated
    defaults: { _controller: "RestaurantBundle:ItemImporter:updated" }

restaurant_itemimporter_reset:
    path:     /{ic}/data-reseted
    defaults: { _controller: "RestaurantBundle:ItemImporter:reseted" }

restaurant_itemimporter_restore:
    path:     /{ic}/data-restored
    defaults: { _controller: "RestaurantBundle:ItemImporter:restored" }
