restaurant_particular:
    path:     /
    defaults: { _controller: "RestaurantBundle:Particular:index" }

restaurant_particular_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Particular:create" }
    methods:  POST

restaurant_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Particular:edit" }

restaurant_particular_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Particular:update" }
    methods:  [POST, PUT]

restaurant_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Particular:delete" }

restaurant_particular_status:
    path:     /{id}/status
    defaults: { _controller: "RestaurantBundle:Particular:status" }

restaurant_particular_sorted:
    path:     /product-sorted
    defaults: { _controller: "RestaurantBundle:Particular:sorted" }

