restaurant_product:
    path:     /
    defaults: { _controller: "RestaurantBundle:Product:index" }

restaurant_product_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Product:create" }
    methods:  POST

restaurant_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Product:edit" }

restaurant_product_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Product:update" }
    methods:  [POST, PUT]

restaurant_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Product:delete" }

restaurant_product_status:
    path:     /{id}/status
    defaults: { _controller: "RestaurantBundle:Product:status" }

restaurant_product_sorting:
    path:     /product-sorting
    defaults: { _controller: "RestaurantBundle:Product:sorting" }

restaurant_product_sorted:
    path:     /product-sorted
    defaults: { _controller: "RestaurantBundle:Product:sorted" }

