restaurant_production:
    path:     /
    defaults: { _controller: "RestaurantBundle:Production:index" }

restaurant_production_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:Production:new" }

restaurant_production_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Production:create" }
    methods:  POST

restaurant_production_edit:
    path:     /recipe/{id}/
    defaults: { _controller: "RestaurantBundle:Production:production" }

restaurant_production_approve:
    path:     /{id}/approve
    defaults: { _controller: "RestaurantBundle:Production:approve" }

restaurant_production_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Production:productionUpdate" }
    methods:  [POST, PUT]


restaurant_production_delete:
    path:     /{product}/{id}/delete
    defaults: { _controller: "RestaurantBundle:Production:productionElementDelete" }

restaurant_production_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:Production:particularSearch" }


restaurant_production_particular_add:
    path:     /{id}/particular-add
    defaults: { _controller: "RestaurantBundle:Production:addParticular" }
    methods:  POST
    options:
            expose: true

restaurant_production_valueadded:
    path:     /{id}/item-value-add
    defaults: { _controller: "RestaurantBundle:Production:itemValueAdd" }
    methods:  GET
    options:
            expose: true

