restaurant_purchase:
    path:     /
    defaults: { _controller: "RestaurantBundle:Purchase:index" }

restaurant_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "RestaurantBundle:Purchase:show" }

restaurant_purchase_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:Purchase:new" }

restaurant_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Purchase:edit" }

restaurant_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Purchase:update" }
    methods:  [POST, PUT]

restaurant_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "RestaurantBundle:Purchase:edit" }


restaurant_purchase_approve:
    path:     /{id}/approve
    defaults: { _controller: "RestaurantBundle:Purchase:approve" }

restaurant_purchase_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "RestaurantBundle:Purchase:reverse" }

restaurant_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Purchase:delete" }

restaurant_purchase_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:Purchase:particularSearch" }


restaurant_purchase_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "RestaurantBundle:Purchase:addParticular" }
    methods:  POST
    options:
            expose: true

restaurant_purchase_discount_update:
    path:     /purchase/dicount-update
    defaults: { _controller: "RestaurantBundle:Purchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

restaurant_purchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "RestaurantBundle:Purchase:approved" }


restaurant_purchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "RestaurantBundle:Purchase:invoiceParticularDelete" }

restaurant_purchase_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "RestaurantBundle:Purchase:invoicePrint" }