restaurant_report_sales_summary:
    path:     /sales-summary
    defaults: { _controller: "RestaurantBundle:Report:salesSummary" }

restaurant_report_sales_details:
    path:     /sales-details
    defaults: { _controller: "RestaurantBundle:Report:salesDetails" }

restaurant_report_sales_user:
    path:     /user-wise-sales
    defaults: { _controller: "RestaurantBundle:Report:userBaseSalesSummary" }

restaurant_report_sales_category:
    path:     /category-wise-sales
    defaults: { _controller: "RestaurantBundle:Report:categoryBaseSalesSummary" }

restaurant_report_sales_group:
    path:     /group-wise-sales
    defaults: { _controller: "RestaurantBundle:Report:productGroupBaseSalesSummary" }

restaurant_report_sales_product:
    path:     /product-wise-sales
    defaults: { _controller: "RestaurantBundle:Report:productBaseSalesSummary" }

restaurant_report_purchase_summary:
    path:     /purchase-summary
    defaults: { _controller: "RestaurantBundle:Report:purchaseSummary" }

restaurant_report_stock:
    path:     /stock-summary
    defaults: { _controller: "RestaurantBundle:Report:stock" }

