restaurant_stock:
    path:     /
    defaults: { _controller: "RestaurantBundle:Stock:index" }

restaurant_stock_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:Stock:create" }
    methods:  POST

restaurant_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "RestaurantBundle:Stock:edit" }

restaurant_stock_copy:
    path:     /{id}/copy
    defaults: { _controller: "RestaurantBundle:Stock:copy" }

restaurant_stock_update:
    path:     /{id}/update
    defaults: { _controller: "RestaurantBundle:Stock:update" }
    methods:  [POST, PUT]

restaurant_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "RestaurantBundle:Stock:delete" }

restaurant_stock_status:
    path:     /{id}/status
    defaults: { _controller: "RestaurantBundle:Stock:status" }

restaurant_stock_inline:
    path:     /inline-update
    defaults: { _controller: "RestaurantBundle:Stock:inlineUpdate" }

restaurant_stock_update_price:
    path:     /production-price-update
    defaults: { _controller: "RestaurantBundle:Stock:productionUpdate" }