restaurant_tableinvoice:
    path:     /
    defaults: { _controller: "RestaurantBundle:TableInvoice:index" }

restaurant_tableinvoice_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:TableInvoice:new" }
    options:
            expose: true

restaurant_invoice_load:
    path:     /{id}/invoice-load
    defaults: { _controller: "RestaurantBundle:TableInvoice:invoiceLoad" }
    options:
            expose: true

restaurant_tableinvoice_create:
    path:    /create
    defaults: { _controller: "RestaurantBundle:TableInvoice:create" }
    methods:  POST
    options:
            expose: true

restaurant_tableinvoice_update:
    path:    /update
    defaults: { _controller: "RestaurantBundle:TableInvoice:update" }
    methods:  POST
    options:
            expose: true


restaurant_tableinvoice_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:TableInvoice:particularSearch" }
    methods:  GET
    options:
            expose: true

restaurant_tableinvoice_kitchen_print:
    path:     /{id}/kitchen-print
    defaults: { _controller: "RestaurantBundle:TableInvoice:kitchenPrint" }
    methods:  GET
    options:
            expose: true


restaurant_tableinvoice_process:
    path:     /{id}/invoice-prcess
    defaults: { _controller: "RestaurantBundle:TableInvoice:invoiceProcess" }
    methods:  GET
    options:
            expose: true


restaurant_tableinvoice_product_add:
    path:     /{product}/product-add
    defaults: { _controller: "RestaurantBundle:TableInvoice:addProduct" }


restaurant_tableinvoice_product_update:
    path:     /{product}/product-update
    defaults: { _controller: "RestaurantBundle:TableInvoice:updateProduct" }


restaurant_tableinvoice_discount_update:
    path:     /dicount-update
    defaults: { _controller: "RestaurantBundle:TableInvoice:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

restaurant_tableinvoice_discount_coupon:
    path:     /dicount-coupon
    defaults: { _controller: "RestaurantBundle:TableInvoice:invoiceDiscountCoupon" }
    methods:  POST
    options:
            expose: true

restaurant_tableinvoice_particular_delete:
    path:    /{invoice}/{id}/particular-delete
    defaults: { _controller: "RestaurantBundle:TableInvoice:invoiceParticularDelete" }

