restaurant_temporary_new:
    path:     /new
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:new" }
    options:
            expose: true

restaurant_temporary_create:
    path:     /create
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:create" }
    methods:  POST
    options:
            expose: true


restaurant_temporary_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:particularSearch" }
    methods:  GET
    options:
            expose: true


restaurant_temporary_particular_add:
    path:     /particular-add
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:addParticular" }
    methods:  POST
    options:
            expose: true

restaurant_temporary_product_add:
    path:     /{product}/product-add
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:addProduct" }


restaurant_temporary_product_update:
    path:     /{product}/product-update
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:updateProduct" }


restaurant_temporary_discount_update:
    path:     /dicount-update
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

restaurant_temporary_discount_coupon:
    path:     /dicount-coupon
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:invoiceDiscountCoupon" }
    methods:  POST
    options:
            expose: true

restaurant_temporary_particular_delete:
    path:     /{id}/particular-delete
    defaults: { _controller: "RestaurantBundle:RestaurantTemporary:invoiceParticularDelete" }

