attendance:
    path:     /
    defaults: { _controller: "HumanResourceBundle:Attendance:index" }

attendance_user:
    path:     /{user}/employee
    defaults: { _controller: "HumanResourceBundle:Attendance:employeeDetails" }

attendance_user_create:
    path:     /{user}/employee-create
    defaults: { _controller: "HumanResourceBundle:Attendance:employeeLeaveCreate" }

attendance_leave_approve:
    path:     /{id}/employee-leave-approve
    defaults: { _controller: "HumanResourceBundle:Attendance:employeeLeaveApprove" }

attendance_leave_delete:
    path:     /{id}/employee-leave-delete
    defaults: { _controller: "HumanResourceBundle:Attendance:employeeLeaveDelete" }

weekend_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:Weekend:update" }
    methods:  [POST, PUT]

