daily_attendance:
    path:     /
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:index" }

daily_attendance_show:
    path:     /{month}/{year}/show
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:show" }

daily_attendance_month:
    path:     /current-month
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:attendance" }

daily_attendance_menual:
    path:     /attendance-menual
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:manualAttendance" }

daily_attendance_menual_create:
    path:     /attendance-menual-create
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:manualAttendanceCreate" }
    methods:  POST

daily_attendance_add:
    path:     /{id}/add
    defaults: { _controller: "HumanResourceBundle:DailyAttendance:addAttendance" }
    options:
           expose: true

