employee_payroll:
    path:     /
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:index" }

employee_payroll_new:
    path:     /new
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:new" }

employee_payroll_create:
    path:     /create
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:create" }
    methods:  [POST]

employee_payroll_edit:
    path:     /{user}/edit
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:edit" }

employee_payroll_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:update" }
    methods:  [POST, PUT]

employee_payroll_setting:
    path:     /{user}/payroll-setting
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:payrollSetting" }

employee_payroll_setting_update:
    path:     /{id}/payroll-setting-update
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:payrollSettingUpdate" }
    methods:  [POST, PUT]

employee_payroll_approve:
    path:     /{id}/approve
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:approve" }
    options:
        expose: true

employee_payroll_particular_delete:
    path:     /{id}/particular-delete
    defaults: { _controller: "HumanResourceBundle:EmployeePayroll:particularDelete" }
    options:
        expose: true

