hrdepartment:
    path:     /
    defaults: { _controller: "HumanResourceBundle:Department:index" }

hrdepartment_create:
    path:     /create
    defaults: { _controller: "HumanResourceBundle:Department:create" }
    methods:  POST

hrdepartment_edit:
    path:     /{id}/edit
    defaults: { _controller: "HumanResourceBundle:Department:edit" }

hrdepartment_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:Department:update" }
    methods:  [POST, PUT]

hrdepartment_delete:
    path:     /{id}/delete
    defaults: { _controller: "HumanResourceBundle:Department:delete" }
    methods:  [POST, DELETE]
