leave:
    path:      /{user}
    defaults: { _controller: "DomainUserBundle:Agent:index" }

leave_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Agent:show" }

leave_user_new:
    path:     /{user}/new
    defaults: { _controller: "DomainUserBundle:Agent:new" }

leave_create:
    path:     /{user}/create
    defaults: { _controller: "DomainUserBundle:Agent:create" }
    methods:  POST

leave_edit:
    path:     /{user}/{id}/edit
    defaults: { _controller: "DomainUserBundle:Agent:edit" }

leave_update:
    path:     /{user}/{id}/update
    defaults: { _controller: "DomainUserBundle:Agent:update" }
    methods:  [POST, PUT]

leave_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Agent:delete" }
    methods:  [POST, DELETE]

leave_search:
    path:     /customer-search
    defaults: { _controller: "DomainUserBundle:Agent:autoSearch" }
    options:
            expose: true

leave_name:
    path:      /{customer}/customer-name
    defaults: { _controller: "DomainUserBundle:Agent:searchCustomerName" }
    options:
           expose: true

domain_location_search:
    path:     /location-search
    defaults: { _controller: "DomainUserBundle:Agent:autoLocationSearch" }
    options:
            expose: true

domain_location_name:
    path:      /{location}/location-name
    defaults: { _controller: "DomainUserBundle:Agent:searchLocationName" }
    options:
           expose: true