leave_setup:
    path:     /
    defaults: { _controller: "HumanResourceBundle:LeaveSetup:leaveSetup" }

leave_setup_update:
    path:     /update
    defaults: { _controller: "HumanResourceBundle:LeaveSetup:update" }
    methods:  [POST, PUT]
