leavepolicy:
    path:     /
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:index" }

leavepolicy_show:
    path:     /{id}/show
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:show" }

leavepolicy_new:
    path:     /new
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:new" }

leavepolicy_create:
    path:     /create
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:create" }
    methods:  POST

leavepolicy_edit:
    path:     /{id}/edit
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:edit" }

leavepolicy_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:update" }
    methods:  [POST, PUT]

leavepolicy_delete:
    path:     /{id}/delete
    defaults: { _controller: "HumanResourceBundle:LeavePolicy:delete" }
    methods:  [POST, DELETE]
