payrollsetting:
    path:     /
    defaults: { _controller: "HumanResourceBundle:Setting:index" }

payrollsetting_create:
    path:     /create
    defaults: { _controller: "HumanResourceBundle:Setting:create" }
    methods:  POST

payrollsetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "HumanResourceBundle:Setting:edit" }

payrollsetting_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:Setting:update" }
    methods:  [POST, PUT]

payrollsetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "HumanResourceBundle:Setting:delete" }
    methods:  [POST, DELETE]
