weekend:
    path:     /
    defaults: { _controller: "HumanResourceBundle:Weekend:index" }

weekend_update:
    path:     /{id}/update
    defaults: { _controller: "HumanResourceBundle:Weekend:update" }
    methods:  [POST, PUT]

