<?php

namespace Appstore\Bundle\MedicineBundle\Repository;
use Appstore\Bundle\DomainUserBundle\Entity\Customer;
use Appstore\Bundle\MedicineBundle\Entity\MedicineSalesReturnInvoice;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;


/**
 * HmsVendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineSalesReturnInvoiceRepository extends EntityRepository
{

    /**
     * @param $qb
     * @param $data
     */

    protected function handleSearchBetween($qb,$data)
    {

        $invoice = isset($data['invoice'])? $data['invoice'] :'';
        $transactionMethod = isset($data['transactionMethod'])? $data['transactionMethod'] :'';
        $salesBy = isset($data['salesBy'])? $data['salesBy'] :'';
        $paymentStatus = isset($data['paymentStatus'])? $data['paymentStatus'] :'';
        $bank = isset($data['bank'])? $data['bank'] :'';
        $mobileBank = isset($data['mobileBank'])? $data['mobileBank'] :'';
        $device = isset($data['device'])? $data['device'] :'';
        $customer = isset($data['customer'])? $data['customer'] :'';
        $customerName = isset($data['name'])? $data['name'] :'';
        $customerMobile = isset($data['mobile'])? $data['mobile'] :'';
        $createdStart = isset($data['startDate'])? $data['startDate'] :'';
        $createdEnd = isset($data['endDate'])? $data['endDate'] :'';
        $amount = isset($data['amount'])? $data['amount'] :'';
        $process = isset($data['process'])? $data['process'] :'';
        $due = isset($data['due'])? $data['due'] :'';
        if (!empty($invoice)) {
            $qb->andWhere($qb->expr()->like("s.invoice", "'%$invoice%'"  ));
        }
        if (!empty($customerName)) {
            $qb->join('s.customer','c');
            $qb->andWhere($qb->expr()->like("c.name", "'$customerName%'"  ));
        }
        if (!empty($due)) {
            $qb->andWhere("s.due >= :due")->setParameter('due', $due);
        }
        if (!empty($process)) {
            $qb->andWhere($qb->expr()->like("s.process", "'$process%'"  ));
        }
        if (!empty($customerMobile)) {
            $qb->join('s.customer','c');
            $qb->andWhere($qb->expr()->like("c.mobile", "'%$customerMobile%'"  ));
        }

        if (!empty($customer)) {
            $qb->join('s.customer','c');
            $qb->andWhere($qb->expr()->like("c.mobile", "'%$customer%'"  ));
        }

        if (!empty($amount)) {
            $qb->andWhere($qb->expr()->like("s.netTotal", "'%$amount%'"  ));
        }

        if (!empty($createdStart)) {
            $compareTo = new \DateTime($createdStart);
            $created =  $compareTo->format('Y-m-d 00:00:00');
            $qb->andWhere("s.created >= :createdStart");
            $qb->setParameter('createdStart', $created);
        }

        if (!empty($createdEnd)) {
            $compareTo = new \DateTime($createdEnd);
            $createdEnd =  $compareTo->format('Y-m-d 23:59:59');
            $qb->andWhere("s.created <= :createdEnd");
            $qb->setParameter('createdEnd', $createdEnd);
        }
        if(!empty($salesBy)){
            $qb->join("s.salesBy",'un');
            $qb->andWhere("un.username = :username");
            $qb->setParameter('username', $salesBy);
        }
        if(!empty($paymentStatus)){
            $qb->andWhere("s.paymentStatus = :status");
            $qb->setParameter('status', $paymentStatus);
        }
        if(!empty($transactionMethod)){
            $qb->andWhere("s.transactionMethod = :method");
            $qb->setParameter('method', $transactionMethod);
        }
        if(!empty($bank)){
            $qb->join("s.accountBank","bank");
            $qb->andWhere("bank.id = :bankId");
            $qb->setParameter('bankId', $bank);
        }
        if(!empty($mobileBank)){
            $qb->join("s.accountMobileBank","mobile");
            $qb->andWhere("mobile.id = :mobileId");
            $qb->setParameter('mobileId', $mobileBank);
        }
        if(!empty($device)){
            $qb->andWhere("s.androidProcess = :device");
            $qb->setParameter('device', $device);
        }


    }

    public function invoiceLists($config, $data)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('s.medicineConfig = :config')->setParameter('config', $config) ;
        $this->handleSearchBetween($qb,$data);
        $qb->orderBy('s.created','DESC');
        $qb->getQuery();
        return  $qb;
    }

    public function insertMedicineSalesReturn(GlobalOption $option , $data = [])
    {
        $config = $option->getMedicineConfig();
        $em = $this->_em;
        $customerId = $data['customer'];
        $total = (isset($data['total']) and $data['total']) ? round($data['total']):0;
        $payment = (isset($data['payment']) and $data['payment']) ? round($data['payment']):0;
        $remark = (isset($data['comment']) and $data['comment']) ? $data['comment']:'';
        $adjustment = round($total - $payment);
        $customer = $em->getRepository(Customer::class)->findOneBy(array('globalOption' => $option,'id'=>$customerId));
        $entity = new MedicineSalesReturnInvoice();
        $entity->setMedicineConfig($config);
        $entity->setCustomer($customer);
        $entity->setSubTotal($total);
        $entity->setPayment($payment);
        $entity->setComment($remark);
        $entity->setAdjustment($adjustment);
        $em->persist($entity);
        $em->flush();
        return $entity;
    }

    public function updateTotalAmountMismatch()
    {
        $sql = "Update medicine_sales_return_invoice as sales
            inner join (
              select ele.medicineSalesReturnInvoice_id, ROUND(COALESCE(SUM(ele.quantity * ele.salesPrice),0),2) as subTotal
              from medicine_sales_return as ele
              where ele.medicineSalesReturnInvoice_id is not NULL
              group by ele.medicineSalesReturnInvoice_id
            ) as pa on sales.id = pa.medicineSalesReturnInvoice_id
            set sales.subTotal = pa.subTotal";
        $qb = $this->getEntityManager()->getConnection()->prepare($sql);
        $qb->execute();

    }
}
