<?php

namespace Appstore\Bundle\MedicineBundle\Repository;
use Doctrine\ORM\EntityRepository;


/**
 * MedicineSalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineSalesArchiveRepository extends EntityRepository
{
}
