imports:
    - { resource: bundles/fos_user.yml }
    - { resource: bundles/gregwar_image.yml }
    - { resource: bundles/knp_time.yml }
    - { resource: bundles/knp_paginator.yml }
    - { resource: bundles/knp_menu.yml }
    - { resource: bundles/doctrine.yml }
    - { resource: bundles/stof_doctrine.yml }