pos_android_sales:
    path:     /
    defaults: { _controller: "PosBundle:PosAndroid:index" }

pos_android_duplicate_delete:
    path:     /{android}/android-duplicate-delete
    defaults: { _controller: "PosBundle:PosAndroid:androidDuplicateSalesDelete" }

pos_android_process:
    path:     /{android}/android-process
    defaults: { _controller: "PosBundle:PosAndroid:insertGroupApiSalesImport" }
    options:
            expose: true
