pos_desktop:
    path:     /
    defaults: { _controller: "PosBundle:Pos:index" }

pos_create:
    path:     /create
    defaults: { _controller: "PosBundle:Pos:create" }
    methods:  [POST, PUT]
    options:
        expose: true

pos_update_method:
    path:     /update-method
    defaults: { _controller: "PosBundle:Pos:updateTransactionMethod" }
    methods:  [GET]
    options:
        expose: true

pos_update:
    path:     /update
    defaults: { _controller: "PosBundle:Pos:update" }
    methods:  [POST, PUT]
    options:
        expose: true

pos_cancel:
    path:     /remove-cart
    defaults: { _controller: "PosBundle:Pos:cartCancel" }

pos_order:
    path:     /order
    defaults: { _controller: "PosBundle:Pos:order" }

pos_hold:
    path:     /hold-order
    defaults: { _controller: "PosBundle:Pos:hold" }


pos_hold_reorder:
    path:     /{id}/hold-reorder
    defaults: { _controller: "PosBundle:Pos:holdReorder" }

pos_print:
    path:     /{id}/print
    defaults: { _controller: "PosBundle:Pos:print" }


pos_stock_item:
    path:     /pos-stock-item
    defaults: { _controller: "PosBundle:Pos:posItems" }
    methods:  GET
    options:
        expose: true

pos_category_stock_item:
    path:     /{id}/pos-category-stock-item
    defaults: { _controller: "PosBundle:Pos:posCategoryItems" }
    methods:  GET
    options:
        expose: true

pos_stock_item_serialno:
    path:     /{id}/pos-stock-item-serial-no
    defaults: { _controller: "PosBundle:Pos:posSerialNo" }
    methods:  GET
    options:
        expose: true

pos_item_add:
    path:     /{product}/add-to-cart
    defaults: { _controller: "PosBundle:Pos:productCart" }

pos_item_barcode_search:
    path:     /add-barcode-item
    defaults: { _controller: "PosBundle:Pos:searchBarcode" }
    methods:  POST
    options:
        expose: true

pos_item_barcode_info:
    path:     /add-barcode-item-info
    defaults: { _controller: "PosBundle:Pos:searchBarcodeInfo" }
    methods:  POST
    options:
        expose: true

pos_item_create:
    path:     /create-item
    defaults: { _controller: "PosBundle:Pos:createItem" }
    methods:  POST
    options:
        expose: true

pos_item_search:
    path:     /pos-item-search
    defaults: { _controller: "PosBundle:Pos:searchItem" }
    methods:  GET
    options:
        expose: true

pos_item_update:
    path:     /{product}/update-to-cart
    defaults: { _controller: "PosBundle:Pos:productUpdateCart" }

pos_invoice_mode:
    path:     /{mode}/invoice-mode
    defaults: { _controller: "PosBundle:Pos:invoiceMode" }
    options:
        expose: true


pos_item_remove:
    path:     /{product}/remove-to-cart
    defaults: { _controller: "PosBundle:Pos:productRemoveCart" }

pos_item:
    path:     /sales-item
    defaults: { _controller: "PosBundle:Pos:salesItem" }


pos_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "PosBundle:Pos:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

pos_show:
    path:     /{id}/show
    defaults: { _controller: "PosBundle:Pos:show" }

pos_new:
    path:     /new
    defaults: { _controller: "PosBundle:Pos:new" }


pos_edit:
    path:     /{code}/pos
    defaults: { _controller: "PosBundle:Pos:edit" }

pos_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "PosBundle:Pos:invoicePrint" }

pos_print_chalan:
    path:     /{invoice}/chalan
    defaults: { _controller: "PosBundle:Pos:chalanPrint" }

pos_discount_update:
    path:     /sales/discount-update
    defaults: { _controller: "PosBundle:Pos:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true

pos_approve:
    path:     /{id}/approve
    defaults: { _controller: "PosBundle:Pos:approve" }
    options:
           expose: true

pos_reset:
    path:     /{id}/reset
    defaults: { _controller: "PosBundle:Pos:reset" }

pos_delete:
    path:     /{id}/delete
    defaults: { _controller: "PosBundle:Pos:delete" }

pos_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "PosBundle:Pos:deleteEmptyInvoice" }

pos_desktopitem_delete:
    path:     /{sales}/{salesItem}/delete
    defaults: { _controller: "PosBundle:Pos:itemDelete" }

pos_item_serial_update:
    path:     /{salesItem}/update-serial-no
    defaults: { _controller: "PosBundle:Pos:itemSerialNoUpdate" }

pos_inline_update:
    path:     /sales/inline-update
    defaults: { _controller: "PosBundle:Pos:salesInlineUpdate" }
    methods:  POST
    options:
            expose: true

pos_inline_process_update:
    path:     /sales/inline-process-update
    defaults: { _controller: "PosBundle:Pos:salesInlineProcessUpdate" }
    methods:  POST
    options:
            expose: true

pos_inline_status_select:
    path:     /inline-status-select
    defaults: { _controller: "PosBundle:Pos:salesSelect" }
    options:
           expose: true

pos_mobile_update:
    path:     /sales/mobile-update
    defaults: { _controller: "PosBundle:Pos:salesInlineMobileUpdate" }
    methods:  POST
    options:
            expose: true

pos_invoice_search:
    path:     /sales-invoice-sesrch
    defaults: { _controller: "PosBundle:Pos:salesInvoiceSearch" }
    options:
           expose: true

pos_invoice_name:
    path:      /{invoice}/sales-invoice
    defaults: { _controller: "PosBundle:Pos:searchSalesInvoiceName" }
    options:
            expose: true