<?php

namespace Setting\Bundle\ToolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SyndicateModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyndicateModuleRepository extends EntityRepository
{
    public function getSpecificModule($globalOption)
    {

        if($globalOption->getSyndicate()){
            $syndicateId = $globalOption->getSyndicate()->getParent()->getId();
            $em = $this->_em;
            $db = $em->createQueryBuilder();
            $db->select('sm');
            $db->from('SettingToolBundle:SyndicateModule', 'sm');
            $db->innerJoin('sm.syndicates', 's');
            $db->where($db->expr()->andX(
                $db->expr()->eq('sm.status', 1),
                $db->expr()->eq('s.id',$syndicateId)
            ));
            //$db->andWhere(':syndicate MEMBER OF sm.syndicates',$syndicateId);
            return $db->getQuery()->getResult();

        }




    }


}
