hospital_report:
    resource: "@HospitalBundle/Resources/config/routing/report.yml"
    prefix:   /report

hospital_prescription:
    resource: "@HospitalBundle/Resources/config/routing/prescription.yml"
    prefix:   /prescription

hospital_purchase:
    resource: "@HospitalBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

hospital_stockout:
    resource: "@HospitalBundle/Resources/config/routing/stockout.yml"
    prefix:   /stock-out

hospital_accessories_purchase:
    resource: "@HospitalBundle/Resources/config/routing/accessoriesPurchase.yml"
    prefix:   /accessories-purchase

hospital_accessories:
    resource: "@HospitalBundle/Resources/config/routing/accessories.yml"
    prefix:   /accessories

hospital_commission:
    resource: "@HospitalBundle/Resources/config/routing/commission.yml"
    prefix:   /commission

hospital_invoice_return:
    resource: "@HospitalBundle/Resources/config/routing/invoicereturn.yml"
    prefix:   /invoice-return

hospital_vendor:
    resource: "@HospitalBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

hospital_invoice:
    resource: "@HospitalBundle/Resources/config/routing/invoice.yml"
    prefix:   /invoice

hospital_invoice_temporary:
    resource: "@HospitalBundle/Resources/config/routing/invoicetemporary.yml"
    prefix:   /invoice-temporary

hospital_doctor_invoice:
    resource: "@HospitalBundle/Resources/config/routing/doctorinvoice.yml"
    prefix:   /doctor-invoice

hospital_invoice_admission:
    resource: "@HospitalBundle/Resources/config/routing/invoiceadmission.yml"
    prefix:   /invoice-admission

hospital_admission_patient:
    resource: "@HospitalBundle/Resources/config/routing/patient.yml"
    prefix:   /patient

hospital_invoice_particular:
    resource: "@HospitalBundle/Resources/config/routing/invoiceparticular.yml"
    prefix:   /report-process

hospital_particular:
    resource: "@HospitalBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

hospital_pathology:
    resource: "@HospitalBundle/Resources/config/routing/pathology.yml"
    prefix:   /pathology

hospital_pathologicalreport:
    resource: "@HospitalBundle/Resources/config/routing/pathologicalreport.yml"
    prefix:    /pathological-report

hospital_doctor:
    resource: "@HospitalBundle/Resources/config/routing/doctor.yml"
    prefix:   /doctor

hospital_marketing_executive:
    resource: "@HospitalBundle/Resources/config/routing/marketing_executive.yml"
    prefix:   /marketing-executive

hospital_labuser:
    resource: "@HospitalBundle/Resources/config/routing/labuser.yml"
    prefix:   /lab-user

hospital_cabin:
    resource: "@HospitalBundle/Resources/config/routing/cabin.yml"
    prefix:   /cabin-ward

hospital_servicegroup:
    resource: "@HospitalBundle/Resources/config/routing/servicegroup.yml"
    prefix:   /service-group

hospital_surgery:
    resource: "@HospitalBundle/Resources/config/routing/surgery.yml"
    prefix:   /surgery-operation

hospital_stock:
    resource: "@HospitalBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

hospital_other_service:
    resource: "@HospitalBundle/Resources/config/routing/otherservice.yml"
    prefix:   /other-service

hospital_referred_doctor:
    resource: "@HospitalBundle/Resources/config/routing/referreddoctor.yml"
    prefix:   /referred-doctor

hospital_config:
    resource: "@HospitalBundle/Resources/config/routing/config.yml"
    prefix:   /config

hospital_homepage:
    path:     /
    defaults: { _controller: HospitalBundle:Default:index }

hospital_patient_idcard:
    path:     /{id}/patient/idcard
    defaults: { _controller: "HospitalBundle:Default:idcard" }

hospital_group_approved:
    path:      /group/invoice/approved
    defaults: { _controller: "HospitalBundle:Invoice:invoiceGroupApproved" }

hospital_group_revised:
    path:     /group/invoice/revised
    defaults: { _controller: "HospitalBundle:Invoice:invoiceGroupReverse" }

hospital_group_commission_approved:
    path:     /group/doctor/commission
    defaults: { _controller: "HospitalBundle:Invoice:doctorInvoiceGroupApproved" }