<?php

namespace Setting\Bundle\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoGalleryRepository extends EntityRepository
{
}
