parameters:
    docudex.user.permission.security_provider.class: Core\UserBundle\Permission\Provider\SecurityPermissionProvider
    docudex.user.permission_builder.class: Core\UserBundle\Permission\PermissionBuilder



services:
    Core_user.registration.form.type:
        class: Core\UserBundle\Form\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: Core_userbundle_user }


    Core.user.permission.security_provider:
        class: %docudex.user.permission.security_provider.class%
        tags:
            - { name: docudex.user.permission_provider, alias: user }

    Core.user_manager:
        class: Core\UserBundle\Manager\UserManager
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - %fos_user.model.user.class%

    docudex.user.permission_builder:
        class: %docudex.user.permission_builder.class%

    fos_user.group.form.type:
        class: Core\UserBundle\Form\Type\GroupFormType
        arguments: [%fos_user.model.group.class%, @docudex.user.permission_builder]
        tags:
            - { name: form.type, alias: fos_user_group }

    app.listener.redirect_404_to_homepage:
        class: Core\UserBundle\EventListener\Redirect404ToHomepageListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

