dps_config_manage:
    path:     /manage
    defaults: { _controller: "DoctorPrescriptionBundle:DpsConfig:manage" }

dps_default_service:
    path:     /reset-default-service
    defaults: { _controller: "DoctorPrescriptionBundle:DpsConfig:resetDefaultService" }

dps_config_update:
    path:     /update
    defaults: { _controller: "DoctorPrescriptionBundle:DpsConfig:update" }
    methods:  [POST, PUT]

