dps_diseases:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:index" }

dps_diseases_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:create" }
    methods:  POST

dps_diseases_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:edit" }

dps_diseases_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:update" }
    methods:  [POST, PUT]

dps_diseases_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:delete" }

dps_diseases_status:
    path:     /{id}/status
    defaults: { _controller: "DoctorPrescriptionBundle:Diseases:status" }