dps_doctor:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:index" }

dps_doctor_show:
    path:     /{id}/show
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:show" }

dps_doctor_new:
    path:     /new
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:new" }

dps_doctor_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:create" }
    methods:  POST

dps_doctor_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:edit" }

dps_doctor_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:update" }
    methods:  [POST, PUT]

dps_doctor_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:delete" }

dps_doctor_status:
    path:     /{id}/status
    defaults: { _controller: "DoctorPrescriptionBundle:Doctor:status" }