dps_account_expenditure:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:index" }

dps_account_expenditure_new:
    path:     /new
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:new" }

dps_account_expenditure_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:create" }
    methods:  POST

dps_account_expenditure_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:approve" }
    options:
           expose: true

dps_account_expenditure_inline:
    path:     /inline-update
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:inlineUpdate" }


dps_account_expenditure_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Expenditure:delete" }
    options:
           expose: true
