dps_expensecategory:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:index" }

dps_expensecategory_show:
    path:     /{id}/show
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:show" }

dps_expensecategory_new:
    path:     /new
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:new" }

dps_expensecategory_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:create" }
    requirements: { _method: post }

dps_expensecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:edit" }

dps_expensecategory_sorting:
    path:     /sorting
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:sorting" }


dps_expensecategory_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:update" }
    requirements: { _method: post|put }

dps_expensecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:ExpenseCategory:delete" }
    requirements: { _method: post|delete }


