dps_particular:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:index" }

dps_particular_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:create" }
    methods:  POST

dps_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:edit" }

dps_particular_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:update" }
    methods:  [POST, PUT]

dps_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:delete" }

dps_particular_status:
    path:     /{id}/status
    defaults: { _controller: "DoctorPrescriptionBundle:Particular:status" }