dps_prescription:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:index" }

dps_prescription_show:
    path:     /{id}/show
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:show" }

dps_prescription_new:
    path:     /new
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:new" }
    options:
            expose: true

dps_prescription_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:create" }
    methods:  POST

dps_prescription_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:edit" }

dps_prescription_particular_procedure:
    path:     /{Prescription}/{service}/particular-procedure
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:particularProcedure" }
    methods:  POST
    options:
            expose: true

dps_prescription_treatment_search:
    path:     /{id}/treatment-search
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:treatmentParticularSearch" }

dps_prescription_treatment_add:
    path:     /{Prescription}/add-treatment-particular
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:treatmentParticularAdd" }
    methods:  POST
    options:
            expose: true


dps_prescription_treatment_payment:
    path:     /{id}/Prescription-treatment-payment
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:treatmentPayment" }
    methods:  POST
    options:
            expose: true

dps_prescription_treatment_delete:
    path:     /{Prescription}/{id}/treatment-delete
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:treatmentDelete" }

dps_prescription_appointment_datetime_check:
    path:     /treatment-appointment-datetime-check
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:treatmentAppointmentDatetime" }
    methods:  POST
    options:
            expose: true

dps_prescription_appointment_datetime_select:
    path:     /inline-appointment-datetime-select
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:appointmentTime" }
    options:
           expose: true

dps_prescription_medicine_add:
    path:     /{Prescription}/medicine-add
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:addMedicine" }
    methods:  POST
    options:
            expose: true

dps_prescription_medicine_delete:
    path:     /{id}/medicine-delete
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:deleteMedicine" }

dps_description_preview:
    path:     /{id}/preview
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:preview" }

dps_prescription_print:
    path:     /{id}/print
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:invoicePrint" }


dps_prescription_accessories_add:
    path:     /{Prescription}/accessories-add
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:addAccessories" }
    methods:  POST
    options:
            expose: true

dps_prescription_approved:
    path:     /{id}/Prescription-approved
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:approve" }
    methods:  POST
    options:
            expose: true

dps_prescription_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:update" }
    methods:  [POST, PUT]

dps_prescription_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:delete" }





dps_prescription_patient_load:
    path:     /{id}/patient-load
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:patientLoad" }


dps_prescription_status_select:
    path:     /Prescription-status-select
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:statusSelect" }
    options:
           expose: true



dps_prescription_customer_details:
    path:     /Prescription-patient-details
    defaults: { _controller: "DomainUserBundle:CustomerHms:details" }
    methods:  POST
    options:
           expose: true


dps_treatment_inline_update:
    path:     /inline-update
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:inlineUpdate" }


dps_prescription_procedure_search:
    path:     /procedure-search
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:procedureSearch" }
    options:
            expose: true

dps_prescription_procedure_diseases_search:
    path:     /procedure-diseases-search
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:procedureDiseasesSearch" }
    options:
            expose: true

dps_prescription_auto_particular_search:
    path:     /auto-particular-search
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:autoParticularSearch" }
    options:
            expose: true

dps_prescription_investigation_search:
    path:     /auto-investigation-search
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:autoInvestigationSearch" }
    options:
            expose: true

dps_prescription_investigation_procedure:
    path:     /{Prescription}/investigation-file-procedure
    defaults: { _controller: "DoctorPrescriptionBundle:Prescription:investigationProcedure" }
    methods:  POST
    options:
           expose: true

dps_treatment_plan:
    path:     /treatment-plan
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentPlan:index" }

dps_treatment_appointment_schedule:
    path:     /treatment-appointment-date
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentPlan:appointmentDateSchedule" }
    methods:  POST
    options:
           expose: true

dps_prescription_appointment_schedule_time:
    path:     /treatment-appointment-free-time
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentPlan:appointmentFreeTimeSchedule" }
    options:
           expose: true

dps_treatment_date_wise_schedule:
    path:     /treatment-appointment-date-wise-schedule
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentPlan:dateWiseSchedule" }
    methods:  POST
    options:
           expose: true

dps_treatment_plan_sms:
    path:     /{patient}/{id}/send-sms
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentPlan:sendSmsPlan" }

