dps_report_cash:
    path:     /report-cash
    defaults: { _controller: "DoctorPrescriptionBundle:Report:cash" }

dps_report_cash_pdf:
    path:     /report-cash-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:cashPdf" }

dps_report_expenditure:
    path:     /expenditure
    defaults: { _controller: "DoctorPrescriptionBundle:Report:expenditure" }

dps_report_expenditure_pdf:
    path:     /expenditure-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:expenditurePdf" }

dps_report_income:
    path:     /report-income
    defaults: { _controller: "DoctorPrescriptionBundle:Report:income" }

dps_report_income_pdf:
    path:     /report-income-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:incomePdf" }

dps_report_balance_sheet:
    path:     /sales-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:salesSummary" }

dps_report_stock:
    path:     /report-stock
    defaults: { _controller: "DoctorPrescriptionBundle:Report:stock" }

dps_report_stock_pdf:
    path:     /report-stock-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:stockPdf" }

dps_report_stock_out:
    path:     /report-stock-out
    defaults: { _controller: "DoctorPrescriptionBundle:Report:stockOut" }

dps_report_stock_out_pdf:
    path:     /report-stock-out-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:stockOutPdf" }

dps_report_today_sales_summary_pdf:
    path:     /daily-sales-summary-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Default:pdfTodaySales" }

dps_report_sales_summary:
    path:     /sales-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:salesSummary" }

dps_report_sales_summary_pdf:
    path:     /sales-summary-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:salesSummaryPdf" }

dps_report_sales:
    path:     /sales-details
    defaults: { _controller: "DoctorPrescriptionBundle:Report:sales" }

dps_report_sales_pdf:
    path:     /sales-details-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:salesPdf" }

dps_report_sales_monthly:
    path:     /monthly-sales-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:monthlySales" }

dps_report_sales_monthly_pdf:
    path:     /monthly-sales-summary-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:monthlySalesPdf" }

dps_report_sales_all_yearly:
    path:     /all-year-sales-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:allYearSales" }

dps_report_sales_all_yearly_pdf:
    path:     /all-year-sales-summary-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:allYearSalesPdf" }

dps_report_sales_yearly:
    path:     /yearly-sales-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:yearlySales" }

dps_report_sales_yearly_pdf:
    path:     /yearly-sales-summary-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:yearlySalesPdf" }

dps_report_sales_treatment:
    path:     /treatment-wise-sales
    defaults: { _controller: "DoctorPrescriptionBundle:Report:treatmentWiseSales" }

dps_report_sales_treatment_pdf:
    path:     /treatment-wise-sales-pdf
    defaults: { _controller: "DoctorPrescriptionBundle:Report:treatmentWiseSalesPdf" }

dps_report_purchase_summary:
    path:     /purchase-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:purchaseSummary" }

dps_report_purchase:
    path:     /purchase-summary
    defaults: { _controller: "DoctorPrescriptionBundle:Report:purchaseSummary" }

