dps_service:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Service:index" }

dps_service_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Service:create" }
    methods:  POST

dps_service_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Service:edit" }

dps_service_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Service:update" }
    methods:  [POST, PUT]

dps_service_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Service:delete" }

dps_service_status:
    path:     /{id}/status
    defaults: { _controller: "DoctorPrescriptionBundle:Service:status" }

dps_service_sorted:
    path:     /{fieldName}/service-sorted
    defaults: { _controller: "DoctorPrescriptionBundle:Service:sorted" }

