dps_treatment:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:index" }

dps_treatment_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:create" }
    methods:  POST

dps_treatment_edit:
    path:     /{id}/edit
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:edit" }

dps_treatment_update:
    path:     /{id}/update
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:update" }
    methods:  [POST, PUT]

dps_treatment_delete:
    path:     /{id}/delete
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:delete" }

dps_treatment_status:
    path:     /{id}/status
    defaults: { _controller: "DoctorPrescriptionBundle:Treatment:status" }