dps_treatment_accessories:
    path:     /
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentAccessories:index" }

dps_treatment_accessories_create:
    path:     /create
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentAccessories:create" }
    methods:  POST

dps_treatment_accessories_delete:
    path:     /{id}/treatment-accessories-delete
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentAccessories:deleteAccessories" }

dps_treatment_accessories_approved:
    path:     /{id}/treatment-accessories-approved
    defaults: { _controller: "DoctorPrescriptionBundle:TreatmentAccessories:approvedAccessories" }

