hms_cabin:
    path:     /
    defaults: { _controller: "HospitalBundle:Cabin:index" }

hms_cabin_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Cabin:create" }
    methods:  POST

hms_cabin_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Cabin:edit" }

hms_cabin_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Cabin:update" }
    methods:  [POST, PUT]

hms_cabin_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Cabin:delete" }

hms_cabin_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Cabin:status" }