hms_commission:
    path:     /
    defaults: { _controller: "HospitalBundle:Commission:index" }

hms_commission_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Commission:create" }
    methods:  POST

hms_commission_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Commission:edit" }

hms_commission_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Commission:update" }
    methods:  [POST, PUT]

hms_commission_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Commission:status" }

hms_commission_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Commission:delete" }
