hms_config_manage:
    path:     /manage
    defaults: { _controller: "HospitalBundle:HospitalConfig:manage" }

hms_config_update:
    path:     /update
    defaults: { _controller: "HospitalBundle:HospitalConfig:update" }
    methods:  [POST, PUT]

