hms_doctor:
    path:     /
    defaults: { _controller: "HospitalBundle:Doctor:index" }

hms_doctor_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:Doctor:show" }

hms_doctor_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:Doctor:new" }

hms_doctor_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Doctor:create" }
    methods:  POST

hms_doctor_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Doctor:edit" }

hms_doctor_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Doctor:update" }
    methods:  [POST, PUT]

hms_doctor_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Doctor:delete" }

hms_doctor_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Doctor:status" }