hms_invoicereturn:
    path:     /
    defaults: { _controller: "HospitalBundle:InvoiceReturn:index" }

hms_invoicereturn_create:
    path:     /{id}/create
    defaults: { _controller: "HospitalBundle:InvoiceReturn:create" }

hms_invoicereturn_payment:
    path:     /{id}/payment
    defaults: { _controller: "HospitalBundle:InvoiceReturn:payment" }

hms_invoicereturn_canceled:
    path:     /{id}/canceled
    defaults: { _controller: "HospitalBundle:InvoiceReturn:canceled" }

hms_invoicereturn_approve:
    path:     /{id}/approve
    defaults: { _controller: "HospitalBundle:InvoiceReturn:approve" }

hms_invoicereturn_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:InvoiceReturn:status" }

hms_invoicereturn_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:InvoiceReturn:delete" }
