hms_invoice_particular:
    path:     /
    defaults: { _controller: "HospitalBundle:InvoiceParticular:index" }

hms_invoice_report_process:
    path:     /collection-process
    defaults: { _controller: "HospitalBundle:InvoiceParticular:reportProcess" }

hms_invoice_particular_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:InvoiceParticular:show" }

hms_invoice_particular_preparation:
    path:     /{id}/preparation
    defaults: { _controller: "HospitalBundle:InvoiceParticular:preparation" }

hms_invoice_particular_machine_format:
    path:     /{id}/machine-format
    defaults: { _controller: "HospitalBundle:InvoiceParticular:machineFormat" }

hms_invoice_particular_collection:
    path:     /{id}/sample-collection
    defaults: { _controller: "HospitalBundle:InvoiceParticular:sampleCollection" }

hms_invoice_particular_collection_confirm:
    path:     /{id}/sample-collection-confirm
    defaults: { _controller: "HospitalBundle:InvoiceParticular:sampleCollectionConfirm" }

hms_invoice_particular_collection_barcode:
    path:     /{id}/sample-collection-barcode
    defaults: { _controller: "HospitalBundle:InvoiceParticular:sampleCollectionBarcode" }

hms_invoice_particular_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:InvoiceParticular:update" }
    methods:  [POST, PUT]

hms_invoice_particular_delivery:
    path:     /{id}/delivery
    defaults: { _controller: "HospitalBundle:InvoiceParticular:delivery" }

hms_invoice_particular_report_print:
    path:     /{id}/pathological-report-print
    defaults: { _controller: "HospitalBundle:InvoiceParticular:pathologicalReportPrint" }

hms_invoice_particular_report_reverse:
    path:     /{id}/pathological-report-reverse
    defaults: { _controller: "HospitalBundle:InvoiceParticular:reportReverse" }


hms_invoice_pathological_report_delete:
    path:     /{id}/pathological-report-delete
    defaults: { _controller: "HospitalBundle:InvoiceParticular:pathologicalReportDelete" }




