hms_invoice_temporary_new:
    path:     /diagonestic-new
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:new" }
    options:
            expose: true

hms_invoice_temporary_create:
    path:     /diagonestic-create
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:create" }
    methods:  POST

hms_doctor_visit_new:
    path:     /appointment-new
    defaults: { _controller: "HospitalBundle:DoctorAppointment:new" }
    options:
            expose: true

hms_doctor_visit_amount:
    path:     /{id}/appointment-doctor-visit
    defaults: { _controller: "HospitalBundle:DoctorAppointment:doctorVisitAmount" }
    options:
            expose: true

hms_doctor_visit_create:
    path:     /appointment-create
    defaults: { _controller: "HospitalBundle:DoctorAppointment:create" }
    methods:  POST


hms_invoice_temporary_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:particularSearch" }


hms_invoice_temporary_particular_search_add:
    path:     /{id}/particular-search-add
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:searchAddParticular" }
    methods:  GET
    options:
            expose: true

hms_invoice_temporary_particular_add:
    path:     /particular-add
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:addParticular" }
    methods:  POST
    options:
            expose: true


hms_invoice_temporary_discount_update:
    path:     /dicount-update
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

hms_invoice_temporary_particular_delete:
    path:     /{id}/particular-delete
    defaults: { _controller: "HospitalBundle:HmsInvoiceTemporaryParticular:invoiceParticularDelete" }

