hms_labuser:
    path:     /
    defaults: { _controller: "HospitalBundle:LabUser:index" }

hms_labuser_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:LabUser:show" }

hms_labuser_generate:
    path:     /generate
    defaults: { _controller: "HospitalBundle:LabUser:generateLabUser" }

hms_labuser_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:LabUser:new" }

hms_labuser_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:LabUser:create" }
    methods:  POST

hms_labuser_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:LabUser:edit" }

hms_labuser_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:LabUser:update" }
    methods:  [POST, PUT]

hms_labuser_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:LabUser:delete" }

hms_labuser_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:LabUser:status" }