hms_marketing_executive:
    path:     /
    defaults: { _controller: "HospitalBundle:MarketingExecutive:index" }

hms_marketing_executive_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:MarketingExecutive:new" }

hms_marketing_executive_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:MarketingExecutive:create" }
    methods:  POST

hms_marketing_executive_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:MarketingExecutive:edit" }

hms_marketing_executive_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:MarketingExecutive:update" }
    methods:  [POST, PUT]

hms_marketing_executive_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:MarketingExecutive:delete" }

hms_marketing_executive_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:MarketingExecutive:status" }