hms_medicine:
    path:     /
    defaults: { _controller: "HospitalBundle:Medicine:index" }

hms_medicine_shortlist:
    path:     /short-list
    defaults: { _controller: "HospitalBundle:Medicine:shortList" }

hms_medicine_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Medicine:create" }
    methods:  POST

hms_medicine_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Medicine:edit" }

hms_medicine_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Medicine:update" }
    methods:  [POST, PUT]

hms_medicine_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Medicine:delete" }

hms_medicine_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Medicine:status" }

hms_medicine_inline:
    path:     /inline-update
    defaults: { _controller: "HospitalBundle:Medicine:inlineUpdate" }