hms_other_service:
    path:     /
    defaults: { _controller: "HospitalBundle:OtherService:index" }

hms_other_service_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:OtherService:create" }
    methods:  POST

hms_other_service_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:OtherService:edit" }

hms_other_service_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:OtherService:update" }
    methods:  [POST, PUT]

hms_other_service_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:OtherService:delete" }

hms_other_service_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:OtherService:status" }