hms_particular:
    path:     /
    defaults: { _controller: "HospitalBundle:Particular:index" }

hms_particular_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:Particular:show" }

hms_particular_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:Particular:new" }

hms_particular_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Particular:create" }
    methods:  POST

hms_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Particular:edit" }

hms_particular_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Particular:update" }
    methods:  [POST, PUT]

hms_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Particular:delete" }

hms_particular_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Particular:status" }