hms_prescription:
    path:     /
    defaults: { _controller: "HospitalBundle:Prescription:index" }

hms_appoionment:
    path:     /appoionment
    defaults: { _controller: "HospitalBundle:DoctorAppointment:appointmentInvoice" }

hms_prescription_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:Prescription:show" }

hms_prescription_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:Prescription:new" }

hms_prescription_old_patient:
    path:     /old-patient
    defaults: { _controller: "HospitalBundle:Prescription:oldPatient" }
    methods:  [POST, PUT]


hms_prescription_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Prescription:edit" }

hms_prescription_generate:
    path:     /{id}/generate
    defaults: { _controller: "HospitalBundle:Prescription:generate" }

hms_prescription_particular_search:
    path:     /particular-search
    defaults: { _controller: "HospitalBundle:Prescription:particularSearch" }
    methods:  GET
    options:
        expose: true

hms_prescription_inline_update:
    path:     /inline-update
    defaults: { _controller: "HospitalBundle:Prescription:inlineUpdate" }
    methods:  [POST, PUT]
    options:
        expose: true

hms_prescription_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Prescription:update" }
    methods:  [POST, PUT]

hms_prescription_approve:
    path:     /{id}/invoice-approve
    defaults: { _controller: "HospitalBundle:Prescription:invoiceApprove" }

hms_prescription_reverse:
    path:     /{id}/prescription-reverse
    defaults: { _controller: "HospitalBundle:Prescription:prescriptionReverse" }

hms_prescription_print:
    path:     /{id}/invoice-print
    defaults: { _controller: "HospitalBundle:Prescription:print" }

hms_prescription_doctor_print:
    path:     /{id}/doctor-print
    defaults: { _controller: "HospitalBundle:Prescription:doctorPrescriptionPrint" }

hms_prescription_delete:
    path:     /delete
    defaults: { _controller: "HospitalBundle:Prescription:delete" }


