hms_referreddoctor:
    path:     /
    defaults: { _controller: "HospitalBundle:ReferredDoctor:index" }

hms_referreddoctor_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:ReferredDoctor:show" }

hms_referreddoctor_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:ReferredDoctor:new" }

hms_referreddoctor_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:ReferredDoctor:create" }
    methods:  POST

hms_referreddoctor_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:ReferredDoctor:edit" }

hms_referreddoctor_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:ReferredDoctor:update" }
    methods:  [POST, PUT]

hms_referreddoctor_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:ReferredDoctor:delete" }

hms_referreddoctor_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:ReferredDoctor:status" }