hms_service_group:
    path:     /
    defaults: { _controller: "HospitalBundle:ServiceGroup:index" }

hms_service_group_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:ServiceGroup:create" }
    methods:  POST

hms_service_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:ServiceGroup:edit" }

hms_service_group_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:ServiceGroup:update" }
    methods:  [POST, PUT]

hms_service_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:ServiceGroup:delete" }

hms_service_group_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:ServiceGroup:status" }