hms_stock:
    path:     /
    defaults: { _controller: "HospitalBundle:MedicineStock:index" }

hms_stock_global:
    path:     /stock-global-search
    defaults: { _controller: "HospitalBundle:MedicineStock:stockSearch" }

hms_stock_short_item:
    path:     /item-short-list
    defaults: { _controller: "HospitalBundle:MedicineStock:itemShortList" }

hms_stock_current_short_item:
    path:     /daily-item-short-list
    defaults: { _controller: "HospitalBundle:MedicineStock:currentShortList" }

hms_stock_adjustment_close:
    path:     /{id}/item-short-close
    defaults: { _controller: "HospitalBundle:MedicineStock:shortItemClose" }

hms_stock_item_history:
    path:     /item-history
    defaults: { _controller: "HospitalBundle:MedicineStock:stockItemHistory" }

hms_stock_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:MedicineStock:show" }

hms_stock_rack:
    path:     /rack-no
    defaults: { _controller: "HospitalBundle:MedicineStock:rackSelect" }

hms_stock_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:MedicineStock:new" }

hms_stock_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:MedicineStock:create" }
    methods:  POST

hms_stock_accesories_new:
    path:     /new-accessories
    defaults: { _controller: "HospitalBundle:MedicineStock:accessories" }

hms_stock_accessories_create:
    path:     /create-accessories
    defaults: { _controller: "HospitalBundle:MedicineStock:accessoriesCreate" }
    methods:  POST

hms_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:MedicineStock:edit" }


hms_stock_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:MedicineStock:update" }
    methods:  [POST, PUT]

hms_stock_accessories_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:MedicineStock:update" }
    methods:  [POST, PUT]

hms_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:MedicineStock:delete" }
    options:
            expose: true

hms_stock_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:MedicineStock:status" }

hms_stock_inline:
    path:     /inline-update
    defaults: { _controller: "HospitalBundle:MedicineStock:inlineUpdate" }

hms_stock_price:
    path:     /stock-update-price
    defaults: { _controller: "HospitalBundle:MedicineStock:stockPriceUpdate" }

hms_stock_update_quantity:
    path:     /stock-update-quantity
    defaults: { _controller: "HospitalBundle:MedicineStock:stockQuantityUpdate" }

hms_stock_details:
    path:     /{sku}/stock-details
    defaults: { _controller: "HospitalBundle:MedicineStock:inlineUpdate" }

hms_stock_web:
    path:     /{id}/web-item
    defaults: { _controller: "HospitalBundle:MedicineStock:isWeb" }

hms_stock_search:
    path:     /search
    defaults: { _controller: "HospitalBundle:MedicineStock:autoSearch" }
    options:
            expose: true

hms_stock_purchase_search:
    path:     /purchase-search
    defaults: { _controller: "HospitalBundle:MedicineStock:autoPurchaseStockSearch" }
    options:
            expose: true

hms_stock_name_search:
    path:     /search-name
    defaults: { _controller: "HospitalBundle:MedicineStock:autoNameSearch" }
    options:
            expose: true

hms_generic_stock_search:
    path:     /generic-stock-item
    defaults: { _controller: "HospitalBundle:MedicineStock:autoGenericSearch" }
    options:
            expose: true

hms_stock_select2_item:
    path:      /{stock}/select2-item
    defaults: { _controller: "HospitalBundle:MedicineStock:searchStockItem" }
    options:
            expose: true

hms_stock_name:
    path:      /{stock}/name
    defaults: { _controller: "HospitalBundle:MedicineStock:searchName" }
    options:
            expose: true

hms_stock_brand_search:
    path:     /search-brand
    defaults: { _controller: "HospitalBundle:MedicineStock:autoSearchBrand" }
    options:
            expose: true

hms_stock_brand_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "HospitalBundle:MedicineStock:searchBrandName" }
    options:
            expose: true