hms_surgery:
    path:     /
    defaults: { _controller: "HospitalBundle:Surgery:index" }

hms_surgery_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Surgery:create" }
    methods:  POST

hms_surgery_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Surgery:edit" }

hms_surgery_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Surgery:update" }
    methods:  [POST, PUT]

hms_surgery_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Surgery:delete" }

hms_surgery_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Surgery:status" }