appsetting_bank:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountBank:index" }

appsetting_bank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountBank:show" }

appsetting_bank_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountBank:new" }

appsetting_bank_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountBank:create" }
    methods:  POST

appsetting_bank_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountBank:edit" }

appsetting_bank_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountBank:update" }
    methods:  [POST, PUT]

appsetting_bank_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountBank:delete" }

appsetting_bank_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:AccountBank:status" }

