appsetting_branchshop:
    path:     /
    defaults: { _controller: "DomainUserBundle:BranchShop:index" }

appsetting_branchshop_employee:
    path:     /{id}/branches-employee
    defaults: { _controller: "DomainUserBundle:BranchShop:branchesEmployee" }


appsetting_branchshop_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:BranchShop:new" }


appsetting_branchshop_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:BranchShop:create" }
    methods:  POST

appsetting_branchshop_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:BranchShop:edit" }

appsetting_branchshop_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:BranchShop:update" }
    methods:  [POST, PUT]

appsetting_branchshop_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:BranchShop:delete" }



