appsetting_mobile_bank:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountMobileBank:index" }

appsetting_mobile_bank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountMobileBank:show" }

appsetting_mobile_bank_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountMobileBank:new" }

appsetting_mobile_bank_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountMobileBank:create" }
    methods:  POST

appsetting_mobile_bank_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountMobileBank:edit" }

appsetting_mobile_bank_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountMobileBank:update" }
    methods:  [POST, PUT]

appsetting_mobile_bank_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountMobileBank:delete" }

appsetting_mobile_bank_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:AccountMobileBank:status" }

