<?php

namespace Setting\Bundle\ToolBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\AndroidDeviceSetup;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;

/**
 * IconRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AndroidDeviceSetupRepository extends EntityRepository
{
    public function insert(GlobalOption $option, $device)
    {

        /* @var $exist AndroidDeviceSetup */
        $exist = $this->findOneBy(array('globalOption' => $option , 'device' => $device));
        if ($exist) {
            return $exist->getId();
        }else{
            $head = new AndroidDeviceSetup();
            $head->setGlobalOption($option);
            $head->setDevice($device);
            $this->_em->persist($head);
            $this->_em->flush();
            return $head->getId();
        }
    }
}
