<?php

namespace Setting\Bundle\ToolBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ProductUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationTestimonialRepository extends EntityRepository
{
    public function findToTestimonials($app)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->join('e.appModules','app');
        $qb->where('app.id ='.$app);
        $qb->setMaxResults(2);
        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
