<?php

namespace Setting\Bundle\ToolBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\InvoiceSmsEmail;

/**
 * InvoiceSmsEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceSmsEmailRepository extends EntityRepository
{
    public function updateInvoice(InvoiceSmsEmail $invoice)
    {

        $qb = $this->_em->createQueryBuilder();
        $qb->select('SUM(ii.amount) as amount , SUM(ii.quantity) as smsQuantity');
        $qb->from('SettingToolBundle:InvoiceSmsEmailItem','i');
        $qb->join('i.smsEmailPricing','ii' );
        $qb->where("i.invoiceSmsEmail = :invoice");
        $qb->setParameter('invoice', $invoice->getId());
        $res = $qb->getQuery()->getSingleResult();
        $sum = $res['amount'];
        $smsQuantity = $res['smsQuantity'];
        $invoice->setTotalAmount($sum);
        $invoice->setPaidAmount($sum);
        $invoice->setSmsQuantity($smsQuantity);
        $this->_em->persist($invoice);
        $this->_em->flush();

    }
}
