agentclient:
    path:     /
    defaults: { _controller: "CustomerBundle:AgentClient:index" }

agentclient_show:
    path:     /{id}/show
    defaults: { _controller: "CustomerBundle:AgentClient:show" }

agentclient_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:AgentClient:new" }

agentclient_create:
    path:     /create
    defaults: { _controller: "CustomerBundle:AgentClient:create" }
    methods:  POST

agentclient_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomerBundle:AgentClient:edit" }

agentclient_invoice:
    path:     /invoice
    defaults: { _controller: "CustomerBundle:AgentClient:edit" }

agentclient_update:
    path:     /{id}/update
    defaults: { _controller: "CustomerBundle:AgentClient:update" }
    methods:  [POST, PUT]
