customer_business_dashboard:
    path:     /
    defaults: { _controller: "CustomerBundle:Business:index" }

student_invoice_create:
       path:     /invoice-create
       defaults: { _controller: "CustomerBundle:Business:create" }
       methods:  [POST]

customer_self_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:AgentClient:new" }

customer_self_create:
    path:     /create
    defaults: { _controller: "CustomerBundle:AgentClient:create" }
    methods:  POST

