customer_self:
    path:     /
    defaults: { _controller: "CustomerBundle:AgentClient:index" }

customer_self_show:
    path:     /{id}/show
    defaults: { _controller: "CustomerBundle:AgentClient:show" }

customer_self_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:AgentClient:new" }

customer_self_create:
    path:     /create
    defaults: { _controller: "CustomerBundle:AgentClient:create" }
    methods:  POST

customer_self_edit_profile:
    path:     /edit-profile
    defaults: { _controller: "CustomerBundle:AgentClient:edit" }

customer_self_update_profile:
    path:     /update-profile
    defaults: { _controller: "CustomerBundle:AgentClient:profileUpdate" }
    methods:  [POST, PUT]

customer_self_change_password:
    path:     /change-password
    defaults: { _controller: "UserBundle:ChangePassword:customerChangePassword" }

customer_self_forget_password:
    path:     /{id}/forget-user-password
    defaults: { _controller: "DomainUserBundle:DomainUser:forgetPassword" }