customerweb:
    path:     /{module}/module
    defaults: { _controller: "CustomerBundle:Customer:module" }

customerweb_payment:
    path:     /payment
    defaults: { _controller: "CustomerBundle:WebContent:payment" }

customerweb_ticket:
    path:     /ticket
    defaults: { _controller: "CustomerBundle:WebContent:ticket" }

customerweb_report_ledger:
    path:     /ledger
    defaults: { _controller: "CustomerBundle:WebContent:create" }

customerweb_report_cashoverview:
    path:     /ledger
    defaults: { _controller: "CustomerBundle:WebContent:create" }

