customerweb_invoice:
    path:     /
    defaults: { _controller: "CustomerBundle:Invoice:index" }

customerweb_invoice_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:Invoice:new" }

customerweb_invoice_create:
    path:     /invoice-create
    defaults: { _controller: "CustomerBundle:Invoice:create" }
    methods:  [POST]

customerweb_invoice_delete:
    path:     /{id}/invoice
    defaults: { _controller: "CustomerBundle:Invoice:invoiceDelete" }

customerweb_invoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomerBundle:Invoice:edit" }

customer_invoice_inline_update:
    path:     /invoice-inline-update
    defaults: { _controller: "CustomerBundle:Invoice:inlineOrderUpdate" }
    methods:  POST
    options:
            expose: true

customerweb_invoice_show:
    path:     /{id}/edit
    defaults: { _controller: "CustomerBundle:Invoice:show" }

customerweb_invoice_update:
    path:     /{id}/invoice-update
    defaults: { _controller: "CustomerBundle:Invoice:update" }
    methods:  [PUT,POST]

customerweb_report_ledger:
    path:     /ledger
    defaults: { _controller: "CustomerBundle:Invoice:create" }

customerweb_report_cashoverview:
    path:     /ledger
    defaults: { _controller: "CustomerBundle:Invoice:create" }

