customer_dashboard:
    path:     /dashboard
    defaults: { _controller: "CustomerBundle:Default:dashboard" }

customer_domain:
    path:     /domain
    defaults: { _controller: "CustomerBundle:Domain:index" }

customer_domain_bookmark:
    path:     /bookmark
    defaults: { _controller: "CustomerBundle:Domain:domainBookmark" }

allproduct:
    path:      /all-products
    defaults: { _controller: "CustomerBundle:Product:allProduct" }