inbox:
    path:     /
    defaults: { _controller: "CustomerBundle:Order:index" }

inbox_sms:
    path:     /customer-sms
    defaults: { _controller: "CustomerBundle:Notification:sms" }

inbox_email:
    path:     /customer-email
    defaults: { _controller: "CustomerBundle:Notification:email" }
