customer_medicine_dashboard:
    path:     /
    defaults: { _controller: "CustomerBundle:Business:index" }

customer_medicine_show:
    path:     /{id}/show
    defaults: { _controller: "CustomerBundle:AgentClient:show" }

customer_medicine_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:AgentClient:new" }

customer_medicine_create:
    path:     /create
    defaults: { _controller: "CustomerBundle:AgentClient:create" }
    methods:  POST

