member_index:
    path:     /
    defaults: { _controller: "CustomerBundle:Member:index" }

member_show_profile:
    path:     /show-profile
    defaults: { _controller: "CustomerBundle:Member:show" }

member_profile:
    path:     /{customer}/show-profile
    defaults: { _controller: "CustomerBundle:Member:memberProfile" }

member_edit_profile:
    path:     /edit-profile
    defaults: { _controller: "CustomerBundle:Member:edit" }

member_profile_update:
    path:     /update-profile
    defaults: { _controller: "CustomerBundle:Member:update" }
    methods:  [POST, PUT]
