preorder:
    path:     /
    defaults: { _controller: "CustomerBundle:PreOrder:index" }

preorder_show:
    path:     /{id}/show
    defaults: { _controller: "CustomerBundle:PreOrder:show" }

preorder_new:
    path:     /new
    defaults: { _controller: "CustomerBundle:PreOrder:new" }

preorder_create:
    path:     /create
    defaults: { _controller: "CustomerBundle:PreOrder:create" }
    methods:  POST

preorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "CustomerBundle:PreOrder:edit" }

preorder_update:
    path:     /{id}/update
    defaults: { _controller: "CustomerBundle:PreOrder:update" }
    methods:  [POST, PUT]

preorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "CustomerBundle:PreOrder:delete" }

preorder_item:
    path:     /{id}/add-item
    defaults: { _controller: "CustomerBundle:PreOrder:item" }

preorder_item_create:
    path:      /{id}/create-item
    defaults: { _controller: "CustomerBundle:PreOrder:createItem" }
    methods:  POST

preorder_approve:
    path:      /{id}/pre-order-process
    defaults: { _controller: "CustomerBundle:PreOrder:approve" }

preorder_process:
    path:      /{id}/order-process
    defaults: { _controller: "CustomerBundle:PreOrder:process" }
    methods:  [GET, PUT]

preorder_item_delete:
    path:     /{preOrder}/{id}/delete-item
    defaults: { _controller: "CustomerBundle:PreOrder:deleteItem" }

preorder_item_confirm:
    path:     /{preOrder}/{id}/confirm-item
    defaults: { _controller: "CustomerBundle:PreOrder:confirmItem" }

preorder_ajax_payment:
    path:      /{id}/pre-order-payment
    defaults: { _controller: "CustomerBundle:PreOrder:payment" }
    methods:  [POST]

preorder_payment_delete:
    path:     /{id}/payment-delete
    defaults: { _controller: "CustomerBundle:PreOrder:paymentDelete" }

preorder_invoice:
    path:      /{id}/preorder-invoice
    defaults: { _controller: "CustomerBundle:PreOrder:invoice" }