wishlist:
    path:     /
    defaults: { _controller: "CustomerBundle:Order:index" }

wishlist_to_cart:
    path:     /cart-to-order
    defaults: { _controller: "CustomerBundle:Order:cartToOrder" }

wishlist_checkout:
    path:     /cart-to-order
    defaults: { _controller: "CustomerBundle:Order:cartToOrder" }

wishlist_cart:
    path:     /order-cart
    defaults: { _controller: "CustomerBundle:Order:cart" }

wishlist_payment:
    path:     /payment/{id}
    defaults: { _controller: "CustomerBundle:Order:payment" }

wishlist_process:
    path:      /{id}/order-process
    defaults: { _controller: "CustomerBundle:Order:process" }

wishlist_show:
    path:      /{id}/order-show
    defaults: { _controller: "CustomerBundle:Order:show" }

wishlist_delete:
    path:      /{id}/order-delete
    defaults: { _controller: "CustomerBundle:Order:delete" }

wishlist_item_delete:
    path:      /{id}/order-item-delete
    defaults: { _controller: "CustomerBundle:Order:itemDelete" }

wishlist_print_invoice:
    path:     /{invoice}/invoice-print
    defaults: { _controller: "CustomerBundle:Order:print" }