hms_accessories:
    path:     /
    defaults: { _controller: "HospitalBundle:Accessories:index" }

hms_accessories_create:
    path:     /create
    defaults: { _controller: "HospitalBundle:Accessories:create" }
    methods:  POST

hms_accessories_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:Accessories:edit" }

hms_accessories_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:Accessories:update" }
    methods:  [POST, PUT]

hms_accessories_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:Accessories:delete" }

hms_accessories_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:Accessories:status" }

hms_accessories_inline:
    path:     /inline-update
    defaults: { _controller: "HospitalBundle:Accessories:inlineUpdate" }