dms_expensecategory:
    path:     /
    defaults: { _controller: "DmsBundle:ExpenseCategory:index" }

dms_expensecategory_show:
    path:     /{id}/show
    defaults: { _controller: "DmsBundle:ExpenseCategory:show" }

dms_expensecategory_new:
    path:     /new
    defaults: { _controller: "DmsBundle:ExpenseCategory:new" }

dms_expensecategory_create:
    path:     /create
    defaults: { _controller: "DmsBundle:ExpenseCategory:create" }
    requirements: { _method: post }

dms_expensecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "DmsBundle:ExpenseCategory:edit" }

dms_expensecategory_sorting:
    path:     /sorting
    defaults: { _controller: "DmsBundle:ExpenseCategory:sorting" }


dms_expensecategory_update:
    path:     /{id}/update
    defaults: { _controller: "DmsBundle:ExpenseCategory:update" }
    requirements: { _method: post|put }

dms_expensecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "DmsBundle:ExpenseCategory:delete" }
    requirements: { _method: post|delete }


