hms_invoice_admission:
    path:     /
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:index" }

hms_invoice_admission_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:show" }

hms_invoice_admission_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:new" }

hms_invoice_admission_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:edit" }

hms_invoice_admission_reverse:
    path:     /{invoice}/reverse
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:admissionInvoiceReverse" }

hms_invoice_admission_reverse_show:
    path:     /{invoice}/reverse-show
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:admissionInvoiceReverseShow" }

hms_invoice_admission_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:particularSearch" }

hms_invoice_admission_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:update" }
    methods:  [POST, PUT]

hms_invoice_admission_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:invoicePrint" }

hms_invoice_admission_delete:
    path:     /delete/admission-invoice
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:delete" }

hms_invoice_admission_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:deleteEmptyInvoice" }

hms_invoice_admission_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:approve" }
    methods:  POST
    options:
            expose: true

hms_invoice_admission_patient_release:
    path:     /{invoice}/{process}/invoice-confirm
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:release" }

hms_invoice_print_for:
    path:     /{id}/invoice-patient-add
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:invoicePrintFor" }
    methods:  [POST]
    options:
            expose: true

hms_invoice_admission_patint_cabin:
    path:      /admitted-patient-cabin-check
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:checkPatientCabinBooking" }
    methods:  [POST]
    options:
            expose: true

hms_invoice_admission_admitted:
    path:     /admitted-patient
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:admitted" }


hms_invoice_admission_confirm:
    path:     /{id}/manage-admitted-patient
    defaults: { _controller: "HospitalBundle:InvoiceAdmission:confirm" }

hms_invoice_admission_daily_invoice:
    path:     /{invoice}/manage-admitted-patient-invoice
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:admittedInvoice" }

hms_invoice_admission_daily_invoice_create:
    path:     /{invoice}/{id}/manage-admitted-patient-invoice
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:dailyAdmittedInvoice" }


hms_invoice_admission_daily_invoice_add:
    path:     /{id}/admitted-patient-particular-add
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:addParticular" }
    options:
            expose: true

hms_invoice_admission_daily_delete:
    path:      /{invoice}/{id}/admitted-patient-daily-invoice-delete
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:invoiceTransactionDelete" }
    options:
            expose: true

hms_invoice_admission_daily_approve:
    path:      /{id}/admitted-patient-daily-invoice-particular-approve
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:invoiceTransactionApprove" }
    options:
            expose: true

hms_invoice_admission_daily_particular_delete:
    path:      /{transaction}/{id}/admitted-patient-daily-invoice-particular-delete
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:invoiceParticularDelete" }
    options:
            expose: true



hms_invoice_admission_daily_invoice_transaction_submit:
    path:     /{id}/admitted-patient-particular-submit
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:submitTransaction" }
    methods:  [POST]

hms_invoice_admission_transaction_print_single:
    path:     /{invoice}/{id}/admitted-patient-transaction-invoice-single-print
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:singleTransactionInvoicePrint" }

hms_invoice_admission_transaction_print:
    path:      /{invoice}/admitted-patient-transaction-invoice-print
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:transactionInvoicePrint" }

hms_invoice_admission_particular_print:
    path:      /{invoice}/admitted-patient-transaction-invoice-particular
    defaults: { _controller: "HospitalBundle:AdmissionPatientParticular:invoiceParticularPrint" }

