inventory_report:
    resource: "@InventoryBundle/Resources/config/routing/report.yml"
    prefix:   /report

inventory_branch_report:
    resource: "@InventoryBundle/Resources/config/routing/branchreport.yml"
    prefix:   /branch-report

app_setting_bank:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/bankaccount.yml"
    prefix:   /appsetting/bank-account

app_setting_mobile:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/mobileaccount.yml"
    prefix:   /appsetting/mobile-account

inventory_stock_adjustment:
    resource: "@InventoryBundle/Resources/config/routing/adjustment.yml"
    prefix:   /stock-adjustment

app_setting_barnch_shop:
    resource: "@InventoryBundle/Resources/config/routing/appsetting/branchshop.yml"
    prefix:   /branch-shop

inventory_excelimproter:
    resource: "@InventoryBundle/Resources/config/routing/excelimporter.yml"
    prefix:   /excelimproter

inventory_delivery:
    resource: "@InventoryBundle/Resources/config/routing/delivery.yml"
    prefix:   /delivery

inventory_branch_invoice:
    resource: "@InventoryBundle/Resources/config/routing/branchinvoice.yml"
    prefix:   /branch-invoice

inventory_salesimport:
    resource: "@InventoryBundle/Resources/config/routing/salesimport.yml"
    prefix:   /sales-improt

inventory_food_product:
    resource: "@InventoryBundle/Resources/config/routing/foodproduct.yml"
    prefix:   /food/product

inventory_service_item:
    resource: "@InventoryBundle/Resources/config/routing/serviceitem.yml"
    prefix:   /service/item

inventory_service_sales:
    resource: "@InventoryBundle/Resources/config/routing/servicesales.yml"
    prefix:   /service/sales

inventory_goods:
    resource: "@InventoryBundle/Resources/config/routing/goods.yml"
    prefix:   /ecommerce/product

inventory_purchasevendoritem:
    resource: "@InventoryBundle/Resources/config/routing/purchasevendoritem.yml"
    prefix:   /purchasevendoritem

inventory_salesreturn:
    resource: "@InventoryBundle/Resources/config/routing/salesreturn.yml"
    prefix:   /salesreturn

inventory_purchasereturn:
    resource: "@InventoryBundle/Resources/config/routing/purchasereturn.yml"
    prefix:   /purchase/return

inventory_itemattribute:
    resource: "@InventoryBundle/Resources/config/routing/itemattribute.yml"
    prefix:    /item-attribute

inventory_itembrand:
    resource: "@InventoryBundle/Resources/config/routing/itembrand.yml"
    prefix:    /brand

inventory_colorsize:
    resource: "@InventoryBundle/Resources/config/routing/colorsize.yml"
    prefix:    /colorsize

inventory_itemsize:
    resource: "@InventoryBundle/Resources/config/routing/itemsize.yml"
    prefix:    /item-size

inventory_prepurchaseitem:
    resource: "@InventoryBundle/Resources/config/routing/prepurchaseitem.yml"
    prefix:    /pre-purchase-item

inventory_itemunit:
    resource: "@InventoryBundle/Resources/config/routing/itemunit.yml"
    prefix:    /item-unit

inventory_itemcolor:
    resource: "@InventoryBundle/Resources/config/routing/itemcolor.yml"
    prefix:    /item-color

inventory_inventory_product:
    resource: "@InventoryBundle/Resources/config/routing/product.yml"
    prefix:    /product

inventory_sales:
    resource: "@InventoryBundle/Resources/config/routing/sales.yml"
    prefix:    /sales

inventory_manual:
    resource: "@InventoryBundle/Resources/config/routing/salesmanual.yml"
    prefix:    /sales-manual

inventory_salesgeneral:
    resource: "@InventoryBundle/Resources/config/routing/salesgeneral.yml"
    prefix:   /sales-general

inventory_salescustomer:
    resource: "@InventoryBundle/Resources/config/routing/salesonline.yml"
    prefix:   /sales-online

inventory_stockitem:
    resource: "@InventoryBundle/Resources/config/routing/stockitem.yml"
    prefix:   /stockitem

inventory_delivery_return:
    resource: "@InventoryBundle/Resources/config/routing/deliveryreturn.yml"
    prefix:   /delivery-return

inventory_damage:
    resource: "@InventoryBundle/Resources/config/routing/damage.yml"
    prefix:   /damage

inventory_purchaseitem:
    resource: "@InventoryBundle/Resources/config/routing/purchaseitem.yml"
    prefix:   /purchaseitem

inventory_category:
    resource: "@InventoryBundle/Resources/config/routing/category.yml"
    prefix:   /category

inventory_purchaseorder:
    resource: "@InventoryBundle/Resources/config/routing/purchaseorder.yml"
    prefix:   /purchaseorder

inventory_purchase:
    resource: "@InventoryBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

inventory_purchasesimple:
    resource: "@InventoryBundle/Resources/config/routing/purchasesimple.yml"
    prefix:   /purchase-simple

inventory_vendor:
    resource: "@InventoryBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

inventory_warehouse:
    resource: "@InventoryBundle/Resources/config/routing/warehouse.yml"
    prefix:   /warehouse

inventory_item:
    resource: "@InventoryBundle/Resources/config/routing/item.yml"
    prefix:   /item

inventory_simple_item:
    resource: "@InventoryBundle/Resources/config/routing/inventoy_simple_item.yml"
    prefix:   /simple-stock

inventory_barcode:
    resource: "@InventoryBundle/Resources/config/routing/barcode.yml"
    prefix:   /barcode

inventory_itemtypegrouping:
    resource: "@InventoryBundle/Resources/config/routing/itemtypegrouping.yml"
    prefix:   /itemtypegrouping

inventory_inventoryconfig:
    resource: "@InventoryBundle/Resources/config/routing/inventoryconfig.yml"
    prefix:   /config

stockitem_results:
    path:     /results
    defaults: { _controller: "InventoryBundle:StockItem:indexResults" }

inventory_reverse:
    resource: "@InventoryBundle/Resources/config/routing/reverse.yml"
    prefix:   /reverse

inventory_sales_user:
    resource: "@InventoryBundle/Resources/config/routing/salesuser.yml"
    prefix:   /sales-user

inventory_homepage:
    path:     /dashoard
    defaults: { _controller: InventoryBundle:Default:index }


inventory_stock_reset:
    path:     /stock-reset
    defaults: { _controller: InventoryBundle:Default:stockReset }

inventory_sales_reset:
    path:     /sales-reset
    defaults: { _controller: InventoryBundle:Default:salesReset }

inventory_group_approved:
    path:      /group/invoice/approved
    defaults: { _controller: "InventoryBundle:SalesOnline:invoiceGroupApproved" }

inventory_group_revised:
    path:     /group/invoice/revised
    defaults: { _controller: "InventoryBundle:SalesOnline:invoiceGroupReverse" }

inventory_item_to_ecommerce:
    path:     /master/item-to-ecommerce
    defaults: { _controller: InventoryBundle:Default:itemToecommerce }

inventory_category_master_delete:
    path:     /master/master-category
    defaults: { _controller: InventoryBundle:Default:categoryDelete }

inventory_master_delete:
    path:     /master-item-delete
    defaults: { _controller: InventoryBundle:Default:masterItemDelete }

inventory_stock_delete:
    path:     /master-stock-deleete
    defaults: { _controller: InventoryBundle:Default:stockItemDelete }