<?php

namespace Appstore\Bundle\AccountingBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Proxies\__CG__\Appstore\Bundle\DomainUserBundle\Entity\PaymentSalary;
use Setting\Bundle\ToolBundle\Service\DatabaseArchive;

/**
 * AccountBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountBankRepository extends EntityRepository
{

    public function selectBankRecords(){

        $DbBackup = new DatabaseArchive();

        //  $DbBackup->insertSalesData();
        $conn = $DbBackup->backupDatabaseConnection();

        $servername = "127.0.0.1";
        $username = "root";
        $password = "dhaka123";

        try {
            $conn = new \PDO("mysql:host=$servername;dbname=alexabd",  $username, $password);
            // set the PDO error mode to exception
            $conn->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
        }
        catch(\PDOException $e)
        {
            return "failed";
        }

        if (!$conn) {
            die("Connection failed: " . mysqli_connect_error());
        }
        $stmt = "SELECT id FROM account_bank";
        $result = mysqli_query($conn, $stmt);
        var_dump($result);
        exit;
        if (mysqli_num_rows($result) > 0) {
            // output data of each row
            while($row = mysqli_fetch_assoc($result)) {
                echo "id: " . $row["id"]. "<br>";
            }
        } else {
            echo "0 results";
        }

        exit;
    }

    public function findWithSearch($globalOption,$data = '')
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where("e.globalOption = :globalOption");
        $qb->setParameter('globalOption', $globalOption);
       // $this->handleSearchBetween($qb,$data);
        $qb->orderBy('e.bank','ASC');
        $result = $qb->getQuery()->getResult();
        return $result;

    }

    public function entityOverview($globalOption,$data)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->select('SUM(e.debit) AS debit, SUM(e.credit) AS credit');
        $qb->where("e.globalOption = :globalOption");
        $qb->setParameter('globalOption', $globalOption);
        $this->handleSearchBetween($qb,$data);
        $result = $qb->getQuery()->getSingleResult();
        $data =  array('debit'=> $result['debit'],'credit'=> $result['credit']);
        return $data;
    }

    public function getBankOverview($globalOption,$process,$data)
    {

        $qb = $this->createQueryBuilder('e');
        $qb->select('SUM(e.amount) AS amount ');
        $qb->where("e.globalOption = :globalOption");
        $qb->setParameter('globalOption', $globalOption);
        $qb->andWhere("e.process = :process");
        $qb->setParameter('process', 'approved');
        $qb->andWhere("e.toIncrease = :toIncrease");
        $qb->setParameter('toIncrease', $process);
        $this->handleSearchBetween($qb,$data);
        $data = $qb->getQuery()->getSingleResult();
        return $data['amount'];

    }

    /**
     * @param $qb
     * @param $data
     */

    protected function handleSearchBetween($qb,$data)
    {
        if(empty($data))
        {
           /* $datetime = new \DateTime("now");
            $startDate = $datetime->format('Y-m-d 00:00:00');
            $endDate = $datetime->format('Y-m-d 23:59:59');

            $qb->andWhere("e.updated >= :startDate");
            $qb->setParameter('startDate', $startDate);
            $qb->andWhere("e.updated <= :endDate");
            $qb->setParameter('endDate', $endDate);*/

        }else{

            $startDate = isset($data['startDate'])  ? $data['startDate'] : '';
            $endDate =   isset($data['endDate'])  ? $data['endDate'] : '';
            $toUser =    isset($data['toUser'])? $data['toUser'] :'';
            $account =    isset($data['accountHead'])? $data['accountHead'] :'';

            if (!empty($data['startDate']) and !empty($data['endDate']) ) {

                $qb->andWhere("e.updated >= :startDate");
                $qb->setParameter('startDate', $startDate.' 00:00:00');
            }
            if (!empty($data['endDate']) and !empty($data['startDate'])) {

                $qb->andWhere("e.updated <= :endDate");
                $qb->setParameter('endDate', $endDate.' 23:59:59');
            }
            if (!empty($toUser)) {
                $qb->join('e.toUser','u');
                $qb->andWhere("u.username = :user");
                $qb->setParameter('user', $toUser);
            }
            if (!empty($account)) {
                $qb->join('e.accountHead','a');
                $qb->andWhere("a.id = :account");
                $qb->setParameter('account', $account);
            }
        }

    }

}
