<?php

namespace Appstore\Bundle\AccountingBundle\Repository;
use Appstore\Bundle\AccountingBundle\Entity\ExpenseAndroidProcess;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;


/**
 * ExpenseAndroidProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseAndroidProcessRepository extends EntityRepository
{

    public function getAndroidSalesList( $config){

        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.androidDevice','a');
        $qb->select('e.id as id','e.created as created','e.itemCount as itemCount','e.status as status');
        $qb->addSelect('a.device as device');
        $qb->where('e.globalOption = :config')->setParameter('config', $config);
        $qb->orderBy('e.created',"DESC");
        $result = $qb->getQuery();
        return $result;

    }

    public function insertAndroidProcess(GlobalOption $option,$ipAddress,$device,$process,$data)
    {
        $em =  $this->_em;

        $device = $em->getRepository('SettingToolBundle:AndroidDeviceSetup')->findOneBy(array('globalOption'=> $option,'id' => $device));

        $entity = new ExpenseAndroidProcess();
        $entity->setGlobalOption($option);
        $entity->setIpAddress($ipAddress);
        $entity->setAndroidDevice($device);
        $entity->setProcess($process);
        $entity->setJsonItem($data['item']);
        $entity->setStatus(false);
        $em->persist($entity);
        $em->flush();
        return $entity;

    }


}
