human_resource_leavepolicy:
    resource: "@HumanResourceBundle/Resources/config/routing/leavepolicy.yml"
    prefix:   /leave-policy

human_resource_leave:
    resource: "@HumanResourceBundle/Resources/config/routing/leave.yml"
    prefix:   /leave

human_resource_blackout:
    resource: "@HumanResourceBundle/Resources/config/routing/weekend.yml"
    prefix:   /weekend-leave

human_resource_attendance:
    resource: "@HumanResourceBundle/Resources/config/routing/attendance.yml"
    prefix:   /attendance

human_resource_daily_attendance:
    resource: "@HumanResourceBundle/Resources/config/routing/dailyattendance.yml"
    prefix:   /daily-attendance

human_resource_leave_setup:
    resource: "@HumanResourceBundle/Resources/config/routing/leavesetup.yml"
    prefix:   /leave-setup

human_resource_payroll_setting:
    resource: "@HumanResourceBundle/Resources/config/routing/payrollsetting.yml"
    prefix:   /payroll-setting

human_resource_payroll_department:
    resource: "@HumanResourceBundle/Resources/config/routing/hrdepartment.yml"
    prefix:   /payroll-department

human_resource_employee_payroll:
    resource: "@HumanResourceBundle/Resources/config/routing/employeepayroll.yml"
    prefix:   /employee-payroll

human_resource_payroll:
    resource: "@HumanResourceBundle/Resources/config/routing/payroll.yml"
    prefix:   /payroll-generate

human_resource_homepage:
    path:     /hello/{name}
    defaults: { _controller: HumanResourceBundle:Default:index }
