api_ecommerce_setup:
    path:     /setup
    defaults: { _controller: BinduBundle:ApiEcommerce:setup }

api_ecommerce_setup_splash:
    path:     /splash
    defaults: { _controller: BinduBundle:ApiEcommerce:splash }

api_ecommerce_dashboard:
    path:     /dashboard
    defaults: { _controller: BinduBundle:ApiEcommerce:dashboard }

api_ecommerce_config:
    path:     /configuration
    defaults: { _controller: BinduBundle:ApiEcommerce:configuration }

api_ecommerce_portal_store:
    path:     /portal-store
    defaults: { _controller: BinduBundle:ApiEcommerce:portalStore }

api_ecommerce_sidebar_menu:
    path:     /sidebar-menu
    defaults: { _controller: BinduBundle:ApiEcommerce:menu }

api_ecommerce_page_menu:
    path:     /page-menu
    defaults: { _controller: BinduBundle:ApiEcommerce:pageMenu }

api_ecommerce_page_details:
    path:     /page
    defaults: { _controller: BinduBundle:ApiEcommerce:page }

api_ecommerce_home_feature_slider:
    path:     /home-feature-slider
    defaults: { _controller: BinduBundle:ApiEcommerce:homeFeatureSlider }

api_ecommerce_intro_slider:
    path:     /intro-slider
    defaults: { _controller: BinduBundle:ApiEcommerce:introSlider }

api_ecommerce_feature_widget_product:
    path:     /feature-widget-product
    defaults: { _controller: BinduBundle:ApiEcommerce:featureProduct }

api_ecommerce_all_feature_product:
    path:     /all-feature-product
    defaults: { _controller: BinduBundle:ApiEcommerce:allFeatureProducts }

api_ecommerce_item_details:
    path:     /product-details
    defaults: { _controller: BinduBundle:ApiEcommerce:productDetails }

api_ecommerce_item:
    path:     /product
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_global_search:
    path:     /search
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_search:
    path:     /product-search
    defaults: { _controller: BinduBundle:ApiEcommerce:product }

api_ecommerce_item_keyword_search:
    path:     /product-keyword-search
    defaults: { _controller: BinduBundle:ApiEcommerce:productKeyword }

api_ecommerce_item_category:
    path:     /feature-category
    defaults: { _controller: BinduBundle:ApiEcommerce:category }

api_ecommerce_feature_item:
    path:     /feature-product
    defaults: { _controller: BinduBundle:ApiEcommerce:featureProduct }

api_ecommerce_item_all_category:
    path:     /all-category
    defaults: { _controller: BinduBundle:ApiEcommerce:allCategory }

api_ecommerce_item_brand:
    path:     /feature-brand
    defaults: { _controller: BinduBundle:ApiEcommerce:brand }

api_ecommerce_item_all_brand:
    path:     /all-brand
    defaults: { _controller: BinduBundle:ApiEcommerce:allBrand }

api_ecommerce_item_promotion:
    path:     /promotion
    defaults: { _controller: BinduBundle:ApiEcommerce:promotion }

api_ecommerce_item_tag:
    path:     /tag
    defaults: { _controller: BinduBundle:ApiEcommerce:tag }

api_ecommerce_item_discount:
    path:     /discount
    defaults: { _controller: BinduBundle:ApiEcommerce:discount }

api_ecommerce_testimonial:
    path:     /testimonial
    defaults: { _controller: BinduBundle:ApiEcommerce:testimonial }


api_ecommerce_order:
    path:     /order-create
    defaults: { _controller: BinduBundle:ApiEcommerce:orderCreate }
    methods:  POST
    options:
            expose: true

api_ecommerce_upload_order:
    path:     /order-upload
    defaults: { _controller: BinduBundle:ApiEcommerce:orderUpload }
    methods:  POST
    options:
            expose: true

api_ecommerce_order_list:
    path:     /order-list
    defaults: { _controller: BinduBundle:ApiEcommerce:orderList }

api_ecommerce_process_order:
    path:     /process-order
    defaults: { _controller: BinduBundle:ApiEcommerce:processOrder }

api_ecommerce_order_details:
    path:     /order-details
    defaults: { _controller: BinduBundle:ApiEcommerce:orderDetails }

api_ecommerce_order_delete:
    path:     /order-delete
    defaults: { _controller: BinduBundle:ApiEcommerce:orderDelete }

api_ecommerce_related_product:
    path:     /related-product
    defaults: { _controller: BinduBundle:ApiEcommerce:relatedProduct }

api_ecommerce_time_period:
    path:     /order-time-period
    defaults: { _controller: BinduBundle:ApiEcommerce:orderTimePeriod }

api_ecommerce_order_location:
    path:     /order-location
    defaults: { _controller: BinduBundle:ApiEcommerce:orderDeliveryLocation }

api_ecommerce_mobile_account:
    path:     /mobile-account
    defaults: { _controller: BinduBundle:ApiEcommerce:mobileAccount }

api_ecommerce_login:
    path:     /user-login
    defaults: { _controller: BinduBundle:ApiEcommerce:userLogin }
    methods:  POST
    options:
        expose: true


api_ecommerce_registration:
    path:     /user-register
    defaults: { _controller: BinduBundle:ApiEcommerce:userRegister }
    methods:  POST
    options:
            expose: true

api_ecommerce_additional_address:
    path:     /customer-address
    defaults: { _controller: BinduBundle:ApiEcommerce:customerAddress }
    methods:  POST
    options:
            expose: true

api_ecommerce_update_registration:
    path:     /update-register
    defaults: { _controller: BinduBundle:ApiEcommerce:userUpdateProfile }
    methods:  POST
    options:
            expose: true