api_portal_contact:
    path:     /information
    defaults: { _controller: BinduBundle:ApiPortal:portalInformation }

api_portal_domain_list:
    path:     /domain-list
    defaults: { _controller: BinduBundle:ApiPortal:domainList }

api_portal_app:
    path:     /apps
    defaults: { _controller: BinduBundle:ApiPortal:apps }

api_portal_app_details:
    path:     /app-details
    defaults: { _controller: BinduBundle:ApiPortal:appDetails }

api_portal_app_customer:
    path:     /app-customer
    defaults: { _controller: BinduBundle:ApiPortal:appWiseCustomer }

api_portal_app_user_register:
    path:     /app-user-register
    defaults: { _controller: BinduBundle:ApiPortal:userRegister }
    methods:  POST
    options:
           expose: true
