<?php

namespace Setting\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdmissionCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionCommentRepository extends EntityRepository
{
    public function insertMessage($data)
    {

        $em = $this->_em;
        $id = $em->getRepository('SettingContentBundle:Admission')->find($data['id']);

        if($data){
            $entity = new AdmissionComment();
            $entity->setAdmission($id);
            $entity->setName($data['name']);
            $entity->setEmail($data['email']);
            $entity->setContent($data['content']);
            $em->persist($entity);
            $em->flush();
        }

    }

}
