<?php

namespace Setting\Bundle\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCommentRepository extends EntityRepository
{

    public function insertMessage($data)
    {

        $em = $this->_em;
        $id = $em->getRepository('SettingContentBundle:Blog')->find($data['id']);

        if($data){
            $entity = new BlogComment();
            $entity->setBlog($id);
            $entity->setName($data['name']);
            $entity->setEmail($data['email']);
            $entity->setContent($data['content']);
            $em->persist($entity);
            $em->flush();
        }

    }

}
