<?php

namespace Setting\Bundle\ContentBundle\Repository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFeatureContent($entity)
    {
        $user = $entity->getUser()->getId();
        $currDate = date('Y-m-d h:m:s');
        $limit = $entity->getUser()->getHomePage()->getShowingListing();
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where($qb->expr()->eq('a.status', 1))
            ->andWhere($qb->expr()->eq('a.user', $user))
            ->setMaxResults($limit)
            ->orderBy('a.created', 'DESC');

        return $qb->getQuery()->getResult();
    }


    public function findUserModuleContent($entity,$limit=5)
    {
        $user = $entity->getUser()->getId();
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where($qb->expr()->eq('a.status', 1))
            ->andWhere($qb->expr()->eq('a.user', $user))
            ->setMaxResults($limit)
            ->orderBy('a.created', 'DESC');

        return $qb->getQuery()->getResult();
    }

}
