<?php

namespace Setting\Bundle\ContentBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ContentBundle\Entity\HomeBlock;

/**
 * HomeBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeBlockRepository extends EntityRepository
{

    public function getMenuLists($globalOption){


        $em =$this->_em;
        $entity = $em->getRepository('SettingAppearanceBundle:Menu')->findBy(array('globalOption'=>$globalOption,'status'=>1),array('menu'=>'asc'));
        if($entity){
            return $entity;
        }else{
            return false;
        }
    }

    public function insertHomeBlock($data,$homePage)
    {

        $em =$this->_em;
        $i=0;
        if(!empty($data['blockName'])){
            foreach($data['blockName'] as $block ){

                $menuId = $data['menu'][$i];
                $icon = $data['icon'][$i];
                $menu = $em->getRepository('SettingAppearanceBundle:Menu')->findOneBy(array('id'=>$menuId));
                $icon = $em->getRepository('SettingToolBundle:Icon')->findOneBy(array('id'=>$icon));

                if( $data['blockId'][$i] > 0 and isset($data['blockName'][$i]) and !empty( $data['blockName'][$i])){
                    $id= $data['blockId'][$i];
                    $entity = $em->getRepository('SettingContentBundle:HomeBlock')->findOneBy(array('id'=>$id));
                    $entity->setHomePage($homePage);
                    $entity->setName($block);
                    $entity->setMenu($menu);
                    $entity->setIcon($icon);
                    $entity->setContent($data['content'][$i]);
                    $em->persist($entity);
                }elseif(isset($data['blockName'][$i]) and !empty( $data['blockName'][$i]) ){
                    $entity = new HomeBlock();
                    $entity->setHomePage($homePage);
                    $entity->setName($block);
                    $entity->setMenu($menu);
                    $entity->setIcon($icon);
                    $entity->setContent($data['content'][$i]);
                    $em->persist($entity);
                }


                $i++;
            }
            $em->flush();

        }

    }

}
