<?php

namespace Setting\Bundle\ContentBundle\Repository;
use Setting\Bundle\ContentBundle\Entity\NoticeBoard;
use Doctrine\ORM\EntityRepository;

/**
 * NoticeBoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeBoardRepository extends EntityRepository
{

    public function findFeatureContent($entity)
    {
        $user = $entity->getUser()->getId();
        $limit = $entity->getUser()->getHomePage()->getShowingListing();
        return $this->getEntityManager()
            ->createQuery('SELECT n FROM SettingContentBundle:NoticeBoard n WHERE n.status = 1 AND n.user ='.$user.' ORDER BY n.created DESC')
            ->setMaxResults($limit)
            ->getResult();
    }

    public function findUserModuleContent($entity)
    {
        $user = $entity->getUser()->getId();
        $limit = 5;
        $currDate = date('Y-m-d h:m:s');
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where($qb->expr()->eq('a.status', 1))
            ->andWhere($qb->expr()->eq('a.user', $user))
            ->andWhere('a.startDate > :startDate')
            ->setParameter('startDate', $currDate )
            ->setMaxResults($limit)
            ->orderBy('a.startDate', 'ASC');

        return $qb->getQuery()->getResult();
    }


}
