<?php

namespace Appstore\Bundle\DmsBundle\Repository;
use Appstore\Bundle\DmsBundle\Controller\InvoiceController;
use Appstore\Bundle\DmsBundle\Entity\AdmissionPatientDmsParticular;
use Appstore\Bundle\DmsBundle\Entity\DmsConfig;
use Appstore\Bundle\DmsBundle\Entity\DmsInvoice;
use Appstore\Bundle\DmsBundle\Entity\DmsInvoiceMedicine;
use Appstore\Bundle\DmsBundle\Entity\Invoice;
use Appstore\Bundle\DmsBundle\Entity\InvoiceDmsParticular;
use Appstore\Bundle\DmsBundle\Entity\DmsParticular;
use Core\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;


/**
 * DmsInvoiceParticularRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DmsInvoiceMedicineRepository extends EntityRepository
{


    public function defaultSetBeforeMedicine(DmsInvoice $invoice,DmsInvoice $lastObject)
    {
         $em = $this->_em;
         if(!empty($lastObject->getInvoiceMedicines())){

            /** @var DmsInvoiceMedicine $item */
            foreach($lastObject->getInvoiceMedicines() as $item ){
                $entity = new DmsInvoiceMedicine();
                $entity->setMedicineQuantity($item->getMedicineQuantity());
                $entity->setMedicineDose($item->getMedicineDose());
                $entity->setMedicineDoseTime($item->getMedicineDoseTime());
                $entity->setMedicineDuration($item->getMedicineDuration());
                $entity->setMedicineDurationType($item->getMedicineDurationType());
                $entity->setDmsInvoice($invoice);
                $entity->setMedicine($item->getMedicine());
                $em->persist($entity);
                $em->flush();
            }
        }

    }

    public function insertInvoiceMedicine(DmsInvoice $invoice, $data)
    {

        $em = $this->_em;
        $entity = new DmsInvoiceMedicine();

        if(!empty($data['medicineQuantity']) and $data['medicineQuantity'] != 'NaN'){
            $entity->setMedicineQuantity($em->getRepository('DmsBundle:DmsPrescriptionAttribute')->find($data['medicineQuantity'])->getNameBn());
        }
        if(!empty($data['medicineDose']) and $data['medicineDose'] != 'NaN'){
            $entity->setMedicineDose($em->getRepository('DmsBundle:DmsPrescriptionAttribute')->find($data['medicineDose'])->getNameBn());
        }
        if(!empty($data['medicineDoseTime']) and $data['medicineDoseTime'] != 'NaN'){
            $entity->setMedicineDoseTime($em->getRepository('DmsBundle:DmsPrescriptionAttribute')->find($data['medicineDoseTime'])->getNameBn());
        }
        if(!empty($data['medicineDurationType']) and $data['medicineDurationType'] != 'NaN'){
            $entity->setMedicineDurationType($em->getRepository('DmsBundle:DmsPrescriptionAttribute')->find($data['medicineDurationType'])->getNameBn());
        }
        if(!empty($data['medicineDuration'])){
            $entity->setMedicineDuration($data['medicineDuration']);
        }

        $entity->setDmsInvoice($invoice);
        if(!empty($data['medicineId'])) {
            $medicine = $this->_em->getRepository('MedicineBundle:MedicineBrand')->find($data['medicineId']);
            $entity->setMedicine($medicine);
        }elseif($data['medicine']){
            $entity->setMedicineName($data['medicine']);
        }
        $em->persist($entity);
        $em->flush();

    }


    public function getInvoiceMedicines(DmsInvoice $sales)
    {
        $entities = $sales->getInvoiceMedicines();
        $data = '';
        $date = '';
        $i = 1;
        /** @var $entity DmsInvoiceMedicine */
        foreach ($entities as $entity) {
            if($entity->getMedicine()){
                $medicine = $entity->getMedicine()->getMedicineForm().'. '.$entity->getMedicine()->getName() .' '.$entity->getMedicine()->getStrength();
            }else{
                $medicine = $entity->getMedicineName();
            }
            if($entity->getUpdated()->format('d-m-Y') != $date ){
                $date = $entity->getUpdated()->format('d-m-Y');
                $data .= '<tr><th colspan="6">'.$entity->getUpdated()->format('d-m-Y').'</th></tr>';
            }
            $data .= '<tr id="medicine-'.$entity->getId().'">';
            $data .= '<td class="numeric" >' . $i . '</td>';
            $data .= '<td class="numeric" >' . $medicine . '</td>';
            $data .= '<td class="numeric" >' . $entity->getMedicineQuantity(). '</td>';
            $data .= '<td class="numeric" >' . $entity->getMedicineDose() .'-'. $entity->getMedicineDoseTime() . '</td>';
            $data .= '<td class="numeric" >' . $entity->getMedicineDuration(). $entity->getMedicineDurationType() . '</td>';
            $data .= '<td class="numeric" >
            <a id="'.$entity->getId().'" data-id="'.$entity->getId().'" title="Are you sure went to delete ?" data-url="/dms/invoice/'. $entity->getId(). '/medicine-delete" href="javascript:" class="btn red mini deleteMedicine" ><i class="icon-trash"></i></a>
            </td>';
            $data .= '</tr>';
            $i++;
        }
        return $data;
    }

}
