inv_stock_adjustment:
    path:     /
    defaults: { _controller: "InventoryBundle:StockAdjustment:index" }

inv_stock_adjustment_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:StockAdjustment:new" }

inv_stock_adjustment_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:StockAdjustment:create" }
    methods:  POST

inv_stock_adjustment_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:StockAdjustment:delete" }

inv_stock_adjustment_approved:
    path:     /{id}/approved
    defaults: { _controller: "InventoryBundle:StockAdjustment:approved" }