inventory_barcode:
    path:     /
    defaults: { _controller: "InventoryBundle:Barcode:index" }

barcode_add:
    path:     /add
    defaults: { _controller: "InventoryBundle:Barcode:add" }

barcode_item_add:
    path:     /item-barcode
    defaults: { _controller: "InventoryBundle:Barcode:addItemBarcode" }

barcode_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Barcode:add" }


barcode_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Barcode:create" }
    options:
           expose: true

barcode_item_create:
    path:     /item-barcode-create
    defaults: { _controller: "InventoryBundle:Barcode:createItemBarcode" }
    options:
           expose: true

barcode_added:
    path:     /added
    defaults: { _controller: "InventoryBundle:Barcode:added" }
    options:
           expose: true

barcode_print:
    path:     /print
    defaults: { _controller: "InventoryBundle:Barcode:print" }
