inventory_branchinvoice:
    path:     /
    defaults: { _controller: "InventoryBundle:BranchInvoice:index" }

inventory_branchinvoice_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:BranchInvoice:show" }

inventory_branchinvoice_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:BranchInvoice:new" }

inventory_branchinvoice_edit:
    path:     /{code}/edit
    defaults: { _controller: "InventoryBundle:BranchInvoice:edit" }


inventory_branchinvoice_print:
    path:     /{id}/print
    defaults: { _controller: "InventoryBundle:BranchInvoice:invoicePrint" }

inventory_branchinvoice_pdf:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:BranchInvoice:pdf" }

inventory_branchinvoice_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:BranchInvoice:update" }
    methods:  [POST, PUT]

inventory_branchinvoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:BranchInvoice:delete" }

inventory_branchinvoice_item_delete:
    path:     /{id}/item-delete
    defaults: { _controller: "InventoryBundle:BranchInvoice:itemDelete" }

inventory_branchinvoice_item_approved:
    path:     /{id}/approved
    defaults: { _controller: "InventoryBundle:BranchInvoice:approve" }
