
inventory_branch_report_overview:
    path:     /branch-overview
    defaults: { _controller: "InventoryBundle:BranchReport:overview" }

inventory_branch_report_stock:
    path:     /branch-stock
    defaults: { _controller: "InventoryBundle:BranchReport:stock" }

inventory_branch_report_item_view:
    path:     /{item}/branch-item-view-details
    defaults: { _controller: "InventoryBundle:BranchReport:branchItemDetails" }

inventory_branch_report_item:
    path:     /branch-item-view
    defaults: { _controller: "InventoryBundle:BranchReport:stockItem" }

inventory_branch_report_barcode_item:
    path:     /branch-barcode-wise-item
    defaults: { _controller: "InventoryBundle:BranchReport:stockBarcode" }

inventory_branch_sales_item_view:
    path:     /{item}/branch-item-sales
    defaults: { _controller: "InventoryBundle:BranchReport:branchItemSales" }
    methods:  GET
    options:
            expose: true

inventory_branch_report_item_search:
    path:     /{item}/branch-stock-item-search
    defaults: { _controller: "InventoryBundle:BranchReport:branchStockItemDetails" }
    methods:  GET
    options:
            expose: true

inventory_branch_report_sales:
    path:     /branch-stock-sales-item
    defaults: { _controller: "InventoryBundle:BranchReport:branchSalesItem" }


inventory_branch_report_sales_item_search:
    path:     /{item}/branch-stock-sales-item-search
    defaults: { _controller: "InventoryBundle:BranchReport:branchSalesItemSearch" }
    methods:  GET
    options:
            expose: true

inventory_branch_report_sales_item_barcode_search:
    path:     /{barcode}/branch-stock-sales-item-barcode-search
    defaults: { _controller: "InventoryBundle:BranchReport:branchSalesItemBarcode" }
    methods:  GET
    options:
            expose: true

inventory_branch_wise_barcode_product_stock:
    path:     /{id}/branch-wise-barcode-product-stock
    defaults: { _controller: "InventoryBundle:BranchReport:branchWiseBarcodeProductStock" }
    methods:  GET
    options:
            expose: true
