inventory_category:
    path:     /
    defaults: { _controller: "InventoryBundle:CustomCategory:index" }

inventory_category_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:CustomCategory:show" }

inventory_category_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:CustomCategory:new" }

inventory_category_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:CustomCategory:create" }
    methods:  POST

inventory_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:CustomCategory:edit" }

inventory_category_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:CustomCategory:update" }
    methods:  [POST, PUT]

inventory_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:CustomCategory:delete" }

