colorsize:
    path:     /
    defaults: { _controller: "InventoryBundle:ColorSize:index" }

colorsize_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ColorSize:show" }

colorsize_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ColorSize:new" }

colorsize_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ColorSize:create" }
    methods:  POST

colorsize_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ColorSize:edit" }

colorsize_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ColorSize:update" }
    methods:  [POST, PUT]

colorsize_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ColorSize:delete" }

