inventory_damage:
    path:     /
    defaults: { _controller: "InventoryBundle:Damage:index" }

inventory_damage_item_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:Damage:search" }
    methods:  POST
    options:
            expose: true

inventory_damage_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "InventoryBundle:Damage:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

inventory_damage_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Damage:show" }

inventory_damage_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Damage:new" }

inventory_damage_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Damage:create" }
    methods:  POST

inventory_damage_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:Damage:edit" }

inventory_damage_print:
    path:     /{code}/print
    defaults: { _controller: "InventoryBundle:Damage:print" }

inventory_damage_due:
    path:     /{code}/due-payment
    defaults: { _controller: "InventoryBundle:Damage:duePayment" }

inventory_damage_item_update:
    path:     /Damage/item/update
    defaults: { _controller: "InventoryBundle:Damage:DamageItemUpdate" }
    methods:  POST
    options:
            expose: true

inventory_damage_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:Damage:approve" }
    options:
           expose: true

inventory_damage_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:Damage:update" }
    methods:  [POST, PUT]

inventory_damage_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Damage:delete" }

inventory_damageitem_delete:
    path:     /{Damage}/{DamageItem}/delete
    defaults: { _controller: "InventoryBundle:Damage:itemDelete" }