inventory_delivery:
    path:     /
    defaults: { _controller: "InventoryBundle:Delivery:index" }

inventory_delivery_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "InventoryBundle:Delivery:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

inventory_delivery_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Delivery:show" }

inventory_delivery_grn:
    path:     /delivery-grn
    defaults: { _controller: "InventoryBundle:Delivery:initialProductBranchDelivery" }
    methods:  POST

inventory_delivery_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Delivery:new" }

inventory_delivery_item:
    path:     /create
    defaults: { _controller: "InventoryBundle:Delivery:create" }
    methods:  POST
    options:
            expose: true

inventory_delivery_edit:
    path:     /{code}/invoice
    defaults: { _controller: "InventoryBundle:Delivery:edit" }

inventory_delivery_print:
    path:     /{id}/print
    defaults: { _controller: "InventoryBundle:Delivery:print" }

inventory_delivery_item_delete:
    path:     /{delivery}/{id}/item/delete
    defaults: { _controller: "InventoryBundle:Delivery:DeliveryItemDelete" }

inventory_delivery_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:Delivery:approve" }
    options:
           expose: true

inventory_delivery_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:Delivery:update" }
    methods:  [POST, PUT]

inventory_delivery_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Delivery:delete" }

