inventory_deliveryreturn:
    path:     /
    defaults: { _controller: "InventoryBundle:DeliveryReturn:index" }

inventory_deliveryreturn_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:DeliveryReturn:show" }

inventory_deliveryreturn_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:DeliveryReturn:new" }

inventory_deliveryreturn_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:DeliveryReturn:create" }
    methods:  POST

inventory_deliveryreturn_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:DeliveryReturn:edit" }


inventory_deliveryreturn_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:DeliveryReturn:approve" }
    options:
           expose: true

inventory_deliveryreturn_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:DeliveryReturn:update" }
    methods:  [POST, PUT]

inventory_deliveryreturn_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:DeliveryReturn:delete" }

