inventory_excelimproter:
    path:     /
    defaults: { _controller: "InventoryBundle:ExcelImporter:index" }

inventory_excelimproter_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "InventoryBundle:ExcelImporter:excelDataImport" }

inventory_excelimproter_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ExcelImporter:new" }

inventory_excelimproter_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ExcelImporter:create" }
    methods:  POST

inventory_excelimproter_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ExcelImporter:edit" }

inventory_excelimproter_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ExcelImporter:update" }
    methods:  [POST, PUT]

inventory_excelimproter_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ExcelImporter:delete" }


inventory_excelimproter_updated:
    path:     /{id}/data-updated
    defaults: { _controller: "InventoryBundle:ExcelImporter:updated" }

inventory_excelimproter_reset:
    path:     /{ic}/data-reseted
    defaults: { _controller: "InventoryBundle:ExcelImporter:reseted" }

inventory_excelimproter_restore:
    path:     /{ic}/data-restored
    defaults: { _controller: "InventoryBundle:ExcelImporter:restored" }
