inventory_foodproduct:
    path:     /
    defaults: { _controller: "InventoryBundle:FoodProduct:index" }

inventory_foodproduct_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:FoodProduct:show" }

inventory_foodproduct_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:FoodProduct:new" }

inventory_foodproduct_create:
    path:      /create
    defaults: { _controller: "InventoryBundle:FoodProduct:create" }
    methods:  POST
    options:
            expose: true

inventory_foodproduct_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:FoodProduct:edit" }

inventory_foodproduct_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:FoodProduct:update" }
    methods:  [POST, PUT]

inventory_foodproduct_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:FoodProduct:delete" }

inventory_vendoritem_status:
    path:     /{id}/web-status
    defaults: { _controller: "InventoryBundle:FoodProduct:webStatus" }

inventory_vendoritem_inline_update:
    path:     /inline-item-update
    defaults: { _controller: "InventoryBundle:PurchaseItem:inlineItemUpdate" }
    methods:  POST
    options:
            expose: true

inventory_vendoritem_gallery:
    path:     /{item}/upload
    defaults: { _controller: "InventoryBundle:FoodProduct:uploadItemImage" }
    options:
           expose: true