inventory_simple_stock_simple_stock:
    path:     /
    defaults: { _controller: "InventoryBundle:Item:index" }

inventory_simple_stock_inventory_simple_stock:
    path:     /
    defaults: { _controller: "InventoryBundle:Item:index" }

inventory_simple_stock_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Item:show" }

inventory_simple_stock_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Item:new" }

inventory_simple_stock_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Item:create" }
    methods:  POST

inventory_simple_stock_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:Item:edit" }


inventory_simple_stock_edit_web:
    path:     /{id}/edit-web
    defaults: { _controller: "InventoryBundle:Item:editWeb" }

inventory_simple_stock_web_status:
    path:     /{id}/inventory_simple_stock-web-status
    defaults: { _controller: "InventoryBundle:Item:webStatus" }

inventory_simple_stock_inventory_simple_stock_web_price:
    path:     /update-web-price
    defaults: { _controller: "InventoryBundle:Item:updateWebPrice" }
    methods:  POST
    options:
            expose: true

inventory_simple_stock_gallery:
    path:     /{inventory_simple_stock}/upload
    defaults: { _controller: "InventoryBundle:Item:uploadItemImage" }
    options:
           expose: true

inventory_simple_stock_status:
    path:     /{id}/status
    defaults: { _controller: "InventoryBundle:Item:status" }

inventory_simple_stock_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:Item:update" }
    methods:  [POST, PUT]

inventory_simple_stock_web_update:
    path:     /{id}/web-update
    defaults: { _controller: "InventoryBundle:Item:updateWeb" }
    methods:  [POST, PUT]

inventory_simple_stock_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Item:delete" }

inventory_simple_stock_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:Item:autoSearch" }
    options:
           expose: true

inventory_simple_stock_search_all:
    path:     /all-search
    defaults: { _controller: "InventoryBundle:Item:autoSearchItemAll" }
    options:
           expose: true

inventory_simple_stock_inventory_simple_stock_inline_update:
    path:     /{vendor}/vendor-inventory_simple_stock
    defaults: { _controller: "InventoryBundle:Item:vendorItem" }
    options:
           expose: true

inventory_simple_stock_price:
    path:      /price
    defaults: { _controller: "InventoryBundle:Item:price" }
    methods:  [POST]
