itemcolor:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemColor:index" }

inventory_itemcolor_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:ItemColor:autoSearch" }
    options:
            expose: true

inventory_itemcolor_name:
    path:      /{color}/color-name
    defaults: { _controller: "InventoryBundle:ItemColor:searchItemColorName" }
    options:
            expose: true

itemcolor_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemColor:show" }

itemcolor_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemColor:new" }

itemcolor_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemColor:create" }
    methods:  POST

itemcolor_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemColor:edit" }

itemcolor_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemColor:update" }
    methods:  [POST, PUT]

itemcolor_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemColor:delete" }

