itemunit:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemUnit:index" }

inventory_itemunit_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:ItemUnit:autoSearch" }
    options:
            expose: true

inventory_itemunit_name:
    path:      /{size}/size-name
    defaults: { _controller: "InventoryBundle:ItemUnit:searchItemUnitName" }
    options:
            expose: true

itemunit_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemUnit:show" }

itemunit_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemUnit:new" }

itemunit_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemUnit:create" }
    methods:  POST

itemunit_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemUnit:edit" }

itemunit_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemUnit:update" }
    methods:  [POST, PUT]

itemunit_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemUnit:delete" }
    methods:  [POST, DELETE]
