itembrand:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemBrand:index" }

inventory_itembrand_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:ItemBrand:autoSearch" }
    options:
            expose: true

inventory_itembrand_name:
    path:      /{brand}/brand-name
    defaults: { _controller: "InventoryBundle:ItemBrand:searchItemBrandName" }
    options:
            expose: true

itembrand_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemBrand:show" }

itembrand_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemBrand:new" }

itembrand_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemBrand:create" }
    methods:  POST

itembrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemBrand:edit" }

itembrand_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemBrand:update" }
    methods:  [POST, PUT]

itembrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemBrand:delete" }
