itemattribute:
    path:     /
    defaults: { _controller: "InventoryBundle:ItemAttribute:index" }

itemattribute_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:ItemAttribute:show" }

itemattribute_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:ItemAttribute:new" }

itemattribute_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:ItemAttribute:create" }
    methods:  POST

itemattribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:ItemAttribute:edit" }

itemattribute_status:
    path:     /{id}/status
    defaults: { _controller: "InventoryBundle:ItemAttribute:status" }

itemattribute_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:ItemAttribute:update" }
    methods:  [POST, PUT]

itemattribute_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:ItemAttribute:delete" }
    methods:  [POST, DELETE]
