prepurchaseitem:
    path:     /
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:index" }

prepurchaseitem_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:show" }

prepurchaseitem_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:new" }

prepurchaseitem_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:create" }
    methods:  POST

prepurchaseitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:edit" }


prepurchaseitem_status:
    path:     /{id}/status
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:status" }

prepurchaseitem_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:update" }
    methods:  [POST, PUT]

prepurchaseitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PrePurchaseItem:delete" }
