inventory_purchaseitem:
    path:     /
    defaults: { _controller: "InventoryBundle:PurchaseItem:index" }

inventory_purchaseitem_multi_add:
    path:     /{purchase}/multi-add
    defaults: { _controller: "InventoryBundle:PurchaseItem:multiAdd" }

inventory_purchaseitem_multi_insert:
    path:     /{purchase}/multi-insert
    defaults: { _controller: "InventoryBundle:PurchaseItem:multiInsert" }
    methods:  POST

inventory_purchaseitem_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PurchaseItem:show" }

inventory_purchaseitem_new:
    path:     /{purchase}/new
    defaults: { _controller: "InventoryBundle:PurchaseItem:new" }

inventory_purchaseitem_create:
    path:     /{purchase}/create
    defaults: { _controller: "InventoryBundle:PurchaseItem:create" }
    methods:  POST

inventory_purchaseitem_inline_update:
    path:     /inline-update
    defaults: { _controller: "InventoryBundle:PurchaseItem:inlineUpdate" }
    methods:  POST
    options:
            expose: true

inventory_purchaseitem_serialno_update:
    path:     /inline-serialno-update
    defaults: { _controller: "InventoryBundle:PurchaseItem:inlineSerialUpdate" }
    methods:  POST
    options:
            expose: true

inventory_purchaseitem_inline_item_update:
    path:     /inline-item-update
    defaults: { _controller: "InventoryBundle:PurchaseItem:inlineItemUpdate" }
    methods:  POST
    options:
            expose: true

inventory_purchaseitem_search:
    path:     /item-search
    defaults: { _controller: "InventoryBundle:PurchaseItem:searchAutoComplete" }
    options:
            expose: true

inventory_barcode_name:
    path:     /{barcode}/barcode-name
    defaults: { _controller: "InventoryBundle:PurchaseItem:searchName" }
    options:
            expose: true

inventory_purchaseitem_barcode:
    path:     /{id}/update-barcode
    defaults: { _controller: "InventoryBundle:PurchaseItem:updateBarcode" }
    options:
            expose: true

inventory_purchaseitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PurchaseItem:edit" }

inventory_purchaseitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PurchaseItem:delete" }

inventory_purchaseitem_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PurchaseItem:update" }
    methods:  [POST, PUT]



