inventory_purchasereturn:
    path:     /
    defaults: { _controller: "InventoryBundle:PurchaseReturn:index" }

inventory_purchasereturn_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PurchaseReturn:show" }

inventory_purchasereturn_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:PurchaseReturn:new" }

inventory_purchasereturn_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:PurchaseReturn:create" }
    methods:  POST

inventory_purchasereturn_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PurchaseReturn:edit" }

inventory_purchasereturn_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:PurchaseReturn:approve" }
    options:
           expose: true

inventory_purchasereturn_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PurchaseReturn:update" }
    methods:  [POST, PUT]

inventory_purchasereturn_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PurchaseReturn:delete" }
    options:
            expose: true

inventory_purchasereturnitem_delete:
    path:     /{purchaseReturn}/{purchaseReturnItem}/item-delete
    defaults: { _controller: "InventoryBundle:PurchaseReturn:deleteItem" }
    options:
            expose: true

inventory_purchasereturn_item_replace:
    path:     /replace
    defaults: { _controller: "InventoryBundle:PurchaseReturn:replace" }
    methods:  POST
    options:
            expose: true

inventory_purchasereturn_item_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:PurchaseReturn:search" }
    methods:  [POST, PUT]
    options:
            expose: true

inventory_purchasereturn_item_update:
    path:     /purchase-return-item-update
    defaults: { _controller: "InventoryBundle:PurchaseReturn:purchaseReturnItemUpdate" }
    methods:  POST
    options:
            expose: true
