purchaseorder:
    path:     /
    defaults: { _controller: "InventoryBundle:PurchaseOrder:index" }

purchaseorder_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PurchaseOrder:show" }

purchaseorder_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:PurchaseOrder:new" }

purchaseorder_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:PurchaseOrder:create" }
    methods:  POST

purchaseorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PurchaseOrder:edit" }

purchaseorder_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PurchaseOrder:update" }
    methods:  [POST, PUT]

purchaseorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PurchaseOrder:delete" }
    methods:  [POST, DELETE]

purchaseorder_status:
    path:     /{id}/status
    defaults: { _controller: "InventoryBundle:PurchaseOrder:edit" }