inventory_purchasesimple:
    path:     /
    defaults: { _controller: "InventoryBundle:PurchaseSimple:index" }

inventory_purchasesimple_serial:
    path:     /serial
    defaults: { _controller: "InventoryBundle:PurchaseSimple:processSerialNo" }

inventory_purchasesimple_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:PurchaseSimple:show" }

inventory_purchasesimple_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:PurchaseSimple:new" }

inventory_purchasesimple_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:PurchaseSimple:edit" }

inventory_purchasesimple_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "InventoryBundle:PurchaseSimple:reverse" }

inventory_purchasesimple_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:PurchaseSimple:update" }
    methods:  [POST, PUT]

inventory_purchasesimple_create:
    path:     /{purchase}/create
    defaults: { _controller: "InventoryBundle:PurchaseSimple:createPurchaseItem" }
    methods:  POST

inventory_purchasesimple_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:PurchaseSimple:approve" }

inventory_purchasesimple_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:PurchaseSimple:delete" }

approved_inventory_purchasesimple_deleted:
    path:     /{id}/approved-inventory_purchasesimple-deleted
    defaults: { _controller: "InventoryBundle:PurchaseSimple:approvedPurchaseDeleted" }

inventory_purchasesimple_edit_approve:
    path:     /{id}/edit-approve
    defaults: { _controller: "InventoryBundle:PurchaseSimple:editApprove" }


inventory_purchasesimple_update_approve:
    path:      /{id}/update-approve
    defaults: { _controller: "InventoryBundle:PurchaseSimple:updateApprove" }
    methods:  [POST, PUT]

inventory_purchasesimple_create_stock_item:
    path:      /create-new-stock-item
    defaults: { _controller: "InventoryBundle:PurchaseSimple:createStockItem" }
    methods:  [POST, PUT]


inventory_purchasesimple_item_delete:
    path:     /{purchase}/{id}/purchase-simple-item-delete
    defaults: { _controller: "InventoryBundle:PurchaseSimple:purchaseItemDelete" }


inventory_grn_search:
    path:     /inventory_purchasesimple-auto-search
    defaults: { _controller: "InventoryBundle:PurchaseSimple:autoSearch" }
    options:
           expose: true

inventory_grn_name:
    path:     /{grn}/inventory_purchasesimple-search-name
    defaults: { _controller: "InventoryBundle:PurchaseSimple:searchName" }
    options:
           expose: true

inventory_purchasesimple_inline_item_update:
    path:     /inline-item-update
    defaults: { _controller: "InventoryBundle:PurchaseSimple:inlineUpdate" }
    methods:  POST
    options:
        expose: true

inventory_purchasesimple_barcode_insert:
    path:     /{id}/barcode-item-insert
    defaults: { _controller: "InventoryBundle:PurchaseSimple:barcodeItemInsert" }
    methods:  POST
    options:
        expose: true