
inventory_report_overview:
    path:     /overview
    defaults: { _controller: "InventoryBundle:Report:overview" }

inventory_report_till_stock:
    path:     /till-stock
    defaults: { _controller: "InventoryBundle:Report:tillStock" }

inventory_report_periodic_stock:
    path:     /periodic-stock
    defaults: { _controller: "InventoryBundle:Report:periodicStock" }

inventory_report_operational_stock:
    path:     /operational-stock
    defaults: { _controller: "InventoryBundle:Report:operationalStock" }

inventory_report_group_stock:
    path:     /group-stock
    defaults: { _controller: "InventoryBundle:Report:groupStock" }

inventory_report_stock:
    path:     /{group}/stock
    defaults: { _controller: "InventoryBundle:Report:stock" }

inventory_report_stock_item:
    path:     /stock-item
    defaults: { _controller: "InventoryBundle:Report:stockItem" }

inventory_report_purchase:
    path:     /purchase
    defaults: { _controller: "InventoryBundle:Report:purchase" }

inventory_report_purchase_overview:
    path:     /purchase-overview
    defaults: { _controller: "InventoryBundle:Report:purchaseOverview" }

inventory_report_sales_item:
    path:     /sales-item
    defaults: { _controller: "InventoryBundle:Report:salesStockItem" }

inventory_report_sales_item_details:
    path:     /sales-item-details
    defaults: { _controller: "InventoryBundle:Report:salesItemDetails" }

inventory_report_sales_user_target:
    path:     /user-sales-mothly-target
    defaults: { _controller: "InventoryBundle:Report:monthlyUserSales" }

inventory_report_sales:
    path:     /sales-transaction
    defaults: { _controller: "InventoryBundle:Report:salesTransaction" }

inventory_report_monthly_sales:
    path:     /monthly-sales
    defaults: { _controller: "InventoryBundle:Report:monthlySales" }

inventory_report_daily_sales:
    path:     /daily-sales
    defaults: { _controller: "InventoryBundle:Report:dailySales" }

inventory_report_daily_sales_profit:
    path:     /daily-sales-profit
    defaults: { _controller: "InventoryBundle:Report:dailySalesProfit" }

inventory_report_monthly_sales_profit:
    path:     /monthly-sales-profit
    defaults: { _controller: "InventoryBundle:Report:monthlySalesProfit" }

inventory_report_sales_overview:
    path:     /sales-transaction-overview
    defaults: { _controller: "InventoryBundle:Report:salesTransactionOverview" }

inventory_report_sales_user:
    path:     /sales-user-overview
    defaults: { _controller: "InventoryBundle:Report:salesUser" }

