inventory_sales_barcode:
    path:     /
    defaults: { _controller: "InventoryBundle:Barcode:sales" }

inventory_sales_barcode_show:
    path:     /{invoice}/sales/show
    defaults: { _controller: "InventoryBundle:Barcode:salesShow" }

inventory_purchase_barcode:
    path:     /
    defaults: { _controller: "InventoryBundle:Barcode:purchase" }

inventory_purchase_barcode_show:
    path:     /
    defaults: { _controller: "InventoryBundle:Barcode:purchaseShow" }

