inventory_sales:
    path:     /
    defaults: { _controller: "InventoryBundle:Sales:index" }

inventory_sales_item:
    path:     /sales-item
    defaults: { _controller: "InventoryBundle:Sales:salesItem" }

inventory_sales_item_search:
    path:     /search
    defaults: { _controller: "InventoryBundle:Sales:search" }
    methods:  POST
    options:
            expose: true

inventory_sales_purchase_item_search:
    path:     /purchase-item-search
    defaults: { _controller: "InventoryBundle:Sales:searchPurchaseItem" }
    methods:  POST
    options:
            expose: true

inventory_sales_item_data:
    path:     /sales-item-data
    defaults: { _controller: "InventoryBundle:Sales:returnSalesData" }
    methods:  GET
    options:
            expose: true

inventory_sales_item_purchase:
    path:     /item-purchase-details
    defaults: { _controller: "InventoryBundle:Sales:itemPurchaseDetails" }
    methods:  POST
    options:
            expose: true

inventory_branch_stock_item:
    path:     /{item}/branch-stock-item-details
    defaults: { _controller: "InventoryBundle:Sales:branchStockItemDetails" }
    methods:  GET
    options:
            expose: true

inventory_sales_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Sales:show" }

inventory_sales_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Sales:new" }

inventory_sales_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:Sales:new" }


inventory_sales_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:Sales:edit" }

inventory_sales_print:
    path:     /{code}/print
    defaults: { _controller: "InventoryBundle:Sales:print" }

inventory_sales_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:Sales:invoicePrint" }

inventory_sales_print_chalan:
    path:     /{invoice}/chalan
    defaults: { _controller: "InventoryBundle:Sales:chalanPrint" }

inventory_sales_discount_update:
    path:     /discount-update
    defaults: { _controller: "InventoryBundle:Sales:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true

inventory_sales_item_update:
    path:     /item-update
    defaults: { _controller: "InventoryBundle:Sales:salesItemUpdate" }
    methods:  POST
    options:
            expose: true

inventory_sales_approve:
    path:     /{id}/approve
    defaults: { _controller: "InventoryBundle:Sales:approve" }
    options:
           expose: true

inventory_sales_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:Sales:update" }
    methods:  [POST, PUT]

inventory_sales_reset:
    path:     /{id}/reset
    defaults: { _controller: "InventoryBundle:Sales:reset" }

inventory_sales_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Sales:delete" }

inventory_sales_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "InventoryBundle:Sales:deleteEmptyInvoice" }

inventory_salesitem_delete:
    path:     /{sales}/{salesItem}/item-delete
    defaults: { _controller: "InventoryBundle:Sales:itemDelete" }

inventory_sales_item_serial_update:
    path:     /{salesItem}/update-serial-no
    defaults: { _controller: "InventoryBundle:Sales:itemSerialNoUpdate" }

inventory_sales_inline_update:
    path:     /sales/inline-update
    defaults: { _controller: "InventoryBundle:Sales:salesInlineUpdate" }
    methods:  POST
    options:
            expose: true

inventory_sales_inline_process_update:
    path:     /sales/inline-process-update
    defaults: { _controller: "InventoryBundle:Sales:salesInlineProcessUpdate" }
    methods:  POST
    options:
            expose: true

inventory_sales_inline_status_select:
    path:     /inline-status-select
    defaults: { _controller: "InventoryBundle:Sales:salesSelect" }
    options:
           expose: true

inventory_sales_mobile_update:
    path:     /sales/mobile-update
    defaults: { _controller: "InventoryBundle:Sales:salesInlineMobileUpdate" }
    methods:  POST
    options:
            expose: true

inventory_sales_invoice_search:
    path:     /sales-invoice-sesrch
    defaults: { _controller: "InventoryBundle:Sales:salesInvoiceSearch" }
    options:
           expose: true

inventory_sales_invoice_name:
    path:      /{invoice}/sales-invoice
    defaults: { _controller: "InventoryBundle:Sales:searchSalesInvoiceName" }
    options:
            expose: true