inventory_salesonline:
    path:     /
    defaults: { _controller: "InventoryBundle:SalesOnline:index" }

inventory_salesonline_customer:
    path:     /customer
    defaults: { _controller: "InventoryBundle:SalesOnline:customer" }

inventory_salesonline_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:SalesOnline:show" }

inventory_salesonline_show_preview:
    path:     /{id}/show-preview
    defaults: { _controller: "InventoryBundle:SalesOnline:showPreview" }
    methods:  GET
    options:
            expose: true

inventory_salesonline_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:SalesOnline:new" }

inventory_salesonline_edit:
    path:     /{code}/online
    defaults: { _controller: "InventoryBundle:SalesOnline:edit" }

inventory_online_pos_print_individual:
    path:     /{id}/online-pos-print-indivisual
    defaults: { _controller: "InventoryBundle:SalesOnline:onlinePosPrintIndividual" }

inventory_salesonline_posprint:
    path:     /online-pos-print
    defaults: { _controller: "InventoryBundle:SalesOnline:onlinePosPrint" }
    methods:  [POST, PUT]
    options:
            expose: true

inventory_salesonline_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:SalesOnline:update" }
    methods:  [POST, PUT]

inventory_salesonline_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:SalesOnline:invoicePrint" }

inventory_online_sales_reverse:
    path:     /{invoice}/invoice-reverse
    defaults: { _controller: "InventoryBundle:SalesOnline:reverse" }

inventory_online_invoice_group_approve:
    path:     /invoice-group-approve
    defaults: { _controller: "InventoryBundle:SalesOnline:invoiceGroupApproved" }

inventory_salesonline_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "InventoryBundle:SalesOnline:deleteEmptyInvoice" }

inventory_salesonline_discount_update:
    path:     /sales/discount-update
    defaults: { _controller: "InventoryBundle:SalesOnline:salesDiscountUpdate" }
    methods:  POST
    options:
            expose: true

inventory_salesonline_item_create:
    path:     /{id}/create-item
    defaults: { _controller: "InventoryBundle:SalesOnline:createItem" }
    methods:  POST
    options:
            expose: true