inventory_salesgeneral:
    path:     /
    defaults: { _controller: "InventoryBundle:SalesGeneral:index" }

inventory_salesgeneral_customer:
    path:     /customer
    defaults: { _controller: "InventoryBundle:SalesGeneral:customer" }

inventory_salesgeneral_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:SalesGeneral:show" }

inventory_salesgeneral_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:SalesGeneral:new" }

inventory_salesgeneral_edit:
    path:     /{code}/pos
    defaults: { _controller: "InventoryBundle:SalesGeneral:edit" }

inventory_salesgeneral_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:SalesGeneral:update" }
    methods:  [POST, PUT]

inventory_salesgeneral_print_invoice:
    path:     /{invoice}/invoice
    defaults: { _controller: "InventoryBundle:SalesGeneral:invoicePrint" }

inventory_salesgeneral_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "InventoryBundle:SalesGeneral:deleteEmptyInvoice" }