inventory_salesimport:
    path:     /
    defaults: { _controller: "InventoryBundle:SalesImport:index" }

inventory_salesimport_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "InventoryBundle:SalesImport:excelDataImport" }

inventory_salesimport_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:SalesImport:new" }

inventory_salesimport_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:SalesImport:create" }
    methods:  POST

inventory_salesimport_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:SalesImport:edit" }

inventory_salesimport_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:SalesImport:update" }
    methods:  [POST, PUT]

inventory_salesimport_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:SalesImport:delete" }


inventory_salesimport_updated:
    path:     /{id}/data-updated
    defaults: { _controller: "InventoryBundle:SalesImport:updated" }

inventory_salesimport_reset:
    path:     /{ic}/data-reseted
    defaults: { _controller: "InventoryBundle:SalesImport:reseted" }

inventory_salesimport_restore:
    path:     /{ic}/data-restored
    defaults: { _controller: "InventoryBundle:SalesImport:restored" }
