inventory_sales_user:
    path:     /
    defaults: { _controller: "DomainUserBundle:SalesUser:index" }

inventory_sales_user_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:SalesUser:create" }



