inventory_stockitem:
    path:     /
    defaults: { _controller: "InventoryBundle:StockItem:index" }
    options:
        expose: true

inventory_stockitem_short_list:
    path:     /item-short-list
    defaults: { _controller: "InventoryBundle:StockItem:itemShortList" }


inventory_stockitem_show:
    path:     /{item}/show
    defaults: { _controller: "InventoryBundle:StockItem:show" }

inventory_stockitem_print:
    path:     /print
    defaults: { _controller: "InventoryBundle:StockItem:print" }

inventory_barcode_branch_stock:
    path:     /barcode-wise-branch-stock
    defaults: { _controller: "InventoryBundle:StockItem:barcodeBranchStock" }

inventory_barcode_stock:
    path:     /barcode-wise-stock
    defaults: { _controller: "InventoryBundle:StockItem:barcodeStock" }

inventory_barcode_wise_branch_stock:
    path:     /{barcode}/single-barcode-wise-branch-stock
    defaults: { _controller: "InventoryBundle:StockItem:singleBarcodeBranchStock" }
    methods:  GET
    options:
            expose: true