inventory_warehouse:
    path:     /
    defaults: { _controller: "InventoryBundle:WareHouse:index" }

inventory_warehouse_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:WareHouse:show" }

inventory_warehouse_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:WareHouse:new" }

inventory_warehouse_create:
    path:     /create
    defaults: { _controller: "InventoryBundle:WareHouse:create" }
    methods:  POST

inventory_warehouse_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:WareHouse:edit" }

inventory_warehouse_update:
    path:     /{id}/update
    defaults: { _controller: "InventoryBundle:WareHouse:update" }
    methods:  [POST, PUT]

inventory_warehouse_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:WareHouse:delete" }
    methods:  [POST, DELETE]
