mobile_home:
    path:     /{subdomain}
    defaults: { _controller: BinduBundle:Mobile:index }

mobile_contact:
    path:     /{subdomain}/contact
    defaults: { _controller: BinduBundle:Mobile:contact }

mobile_email_receive:
    path:     /{subdomain}/email-receive
    defaults: { _controller: BinduBundle:Mobile:contact }

mobile_content_page:
    path:     /{subdomain}/{slug}
    defaults: { _controller: BinduBundle:Mobile:content }
