hms_accessories_purchase:
    path:     /
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:index" }

hms_accessories_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:show" }

hms_accessories_purchase_new:
    path:     /new
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:new" }

hms_accessories_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:edit" }

hms_accessories_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:update" }
    methods:  [POST, PUT]

hms_accessories_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:edit" }


hms_accessories_purchase_approve:
    path:     /{id}/approve
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:approve" }

hms_accessories_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:delete" }

hms_accessories_purchase_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:particularSearch" }


hms_accessories_purchase_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:addParticular" }
    methods:  POST
    options:
            expose: true

hms_accessories_purchase_discount_update:
    path:     /purchase/dicount-update
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

hms_accessories_purchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:approved" }


hms_accessories_purchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:invoiceParticularDelete" }

hms_accessories_purchase_print_invoice:
    path:     /{id}/print
    defaults: { _controller: "HospitalBundle:AccessoriesPurchase:invoicePrint" }