election_expensecategory:
    path:     /
    defaults: { _controller: "ElectionBundle:ExpenseCategory:index" }

election_expensecategory_show:
    path:     /{id}/show
    defaults: { _controller: "ElectionBundle:ExpenseCategory:show" }

election_expensecategory_new:
    path:     /new
    defaults: { _controller: "ElectionBundle:ExpenseCategory:new" }

election_expensecategory_create:
    path:     /create
    defaults: { _controller: "ElectionBundle:ExpenseCategory:create" }
    requirements: { _method: post }

election_expensecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElectionBundle:ExpenseCategory:edit" }

election_expensecategory_sorting:
    path:     /sorting
    defaults: { _controller: "ElectionBundle:ExpenseCategory:sorting" }


election_expensecategory_update:
    path:     /{id}/update
    defaults: { _controller: "ElectionBundle:ExpenseCategory:update" }
    requirements: { _method: post|put }

election_expensecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElectionBundle:ExpenseCategory:delete" }
    requirements: { _method: post|delete }


