election_config_manage:
    path:     /manage
    defaults: { _controller: "ElectionBundle::manage" }

election_config_update:
    path:     /update
    defaults: { _controller: "ElectionBundle:Config:update" }
    methods:  [POST, PUT]


