election_member:
    path:     /
    defaults: { _controller: "ElectionBundle:Member:index" }

election_member_import_updated:
    path:     /import-updated
    defaults: { _controller: "ElectionBundle:Member:memberImportUpdated" }

election_member_generate_idcard:
    path:     /generate-id-card
    defaults: { _controller: "ElectionBundle:Member:generateCard" }


election_member_search:
    path:     /search
    defaults: { _controller: "ElectionBundle:Member:autoSearch" }
    options:
            expose: true

election_member_name:
    path:      /{name}/name
    defaults: { _controller: "ElectionBundle:Member:searchName" }
    options:
            expose: true

election_member_new:
    path:     /new
    defaults: { _controller: "ElectionBundle:Member:new" }

election_member_create:
    path:     /create
    defaults: { _controller: "ElectionBundle:Member:create" }
    methods:  POST

election_member_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElectionBundle:Member:edit" }

election_member_show:
    path:     /{id}/show
    defaults: { _controller: "ElectionBundle:Member:show" }

election_member_update:
    path:     /{id}/update
    defaults: { _controller: "ElectionBundle:Member:update" }
    methods:  [POST, PUT]

election_member_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElectionBundle:Member:delete" }

election_member_family:
    path:     /{id}/add-family
    defaults: { _controller: "ElectionBundle:Member:family" }

election_member_export_csv:
    path:     /member-export-csv
    defaults: { _controller: "ElectionBundle:Member:memberExportToCsv" }

election_member_family_delete:
    path:     /{id}/family-member-delete
    defaults: { _controller: "ElectionBundle:Member:familyMemberDelete" }

election_member_family_create:
    path:     /{id}/family-member-create
    defaults: { _controller: "ElectionBundle:Member:addFamilyMember" }
    methods:  POST
    options:
            expose: true

