election_particular:
    path:     /
    defaults: { _controller: "ElectionBundle:Particular:index" }

election_particular_search:
    path:     /search
    defaults: { _controller: "ElectionBundle:Particular:autoSearch" }
    options:
            expose: true

election_particular_name:
    path:      /{particular}/particular-name
    defaults: { _controller: "ElectionBundle:Particular:searchParticularName" }
    options:
            expose: true

election_particular_create:
    path:     /create
    defaults: { _controller: "ElectionBundle:Particular:create" }
    methods:  POST

election_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElectionBundle:Particular:edit" }

election_particular_update:
    path:     /{id}/update
    defaults: { _controller: "ElectionBundle:Particular:update" }
    methods:  [POST, PUT]

election_particular_status:
    path:     /{id}/status
    defaults: { _controller: "ElectionBundle:Particular:status" }

election_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElectionBundle:Particular:delete" }
