election_sms:
    path:     /
    defaults: { _controller: "ElectionBundle:Sms:index" }

election_member_sms:
    path:     /{id}/member
    defaults: { _controller: "ElectionBundle:Sms:member" }

election_event_sms:
    path:     /{id}/event
    defaults: { _controller: "ElectionBundle:Sms:event" }

election_committee_sms:
    path:     /{id}/committee
    defaults: { _controller: "ElectionBundle:Sms:committee" }

election_votecenter_sms:
    path:     /{id}/vote-center
    defaults: { _controller: "ElectionBundle:Sms:voteCenter" }

election_sms_new:
    path:     /new
    defaults: { _controller: "ElectionBundle:Sms:new" }

election_sms_show:
    path:     /{id}/show
    defaults: { _controller: "ElectionBundle:Sms:show" }
    options:
            expose: true

election_sms_search:
    path:     /search
    defaults: { _controller: "ElectionBundle:Sms:autoSearch" }
    options:
            expose: true

election_sms_name:
    path:      /{particular}/particular-name
    defaults: { _controller: "ElectionBundle:Sms:searchSmsName" }
    options:
            expose: true

election_sms_create:
    path:     /create
    defaults: { _controller: "ElectionBundle:Sms:create" }
    methods:  POST

election_sms_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElectionBundle:Sms:edit" }

election_sms_update:
    path:     /{id}/update
    defaults: { _controller: "ElectionBundle:Sms:update" }
    methods:  [POST, PUT]

election_sms_status:
    path:     /{id}/status
    defaults: { _controller: "ElectionBundle:Sms:status" }

election_sms_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElectionBundle:Sms:delete" }

election_bulk_sms:
    path:     /{id}/bluk
    defaults: { _controller: "ElectionBundle:Sms:bulkSms" }


