ajax_product_modal:
    path:     /product-modal/{subdomain}/{item}
    defaults: { _controller: FrontendBundle:Ajax:productModal }

ajax_product_inline_cart:
    path:     /cart/inline-item-cart/{subdomain}/{product}
    defaults: { _controller: FrontendBundle:Ajax:productInlineCart }
    methods:  GET
    options:
           expose: true

ajax_product_single_cart:
    path:     /single-cart/{subdomain}/{product}
    defaults: { _controller: FrontendBundle:Ajax:productAddSingleCart }

ajax_product_medicine_cart:
    path:     /single-medicine-cart/{subdomain}/{product}
    defaults: { _controller: FrontendBundle:Ajax:productAddMedicineCart }
    methods:  GET
    options:
            expose: true

ajax_inline_item_load:
    path:     /inline-sub-product-load/{subdomain}/{product}
    defaults: { _controller: FrontendBundle:Ajax:inlineSubProduct }

