index:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index}

frontend_institute:
    path:     /institute
    defaults: { _controller: FrontendBundle:Default:education }
    requirements: { _method: get }

frontend_admission:
    path:     /institute/admission
    defaults: { _controller: FrontendBundle:Module:admission }
    requirements: { _method: get }


frontend_institute_subdomain:
    path:     /institute/{subdomain}
    defaults: { _controller: FrontendBundle:Default:instituteDetail }

frontend_module:
    path:     /institute/{module}
    defaults: { _controller: FrontendBundle:Module:module }

frontend_subdomain_module:
    path:     /institute/{subdomain}/{module}
    defaults: { _controller: FrontendBundle:Module:subdomainModule }

frontend_subdomain_content:
    path:     /institute/{subdomain}/{slug}
    defaults: { _controller: FrontendBundle:Module: subdomainContent }


frontend_subdomain_module_content:
    path:     /institute/{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:Module:subdomainModuleContent }
    requirements: { _method: get }

frontend_subdomain_module_download:
    path:     /institute/{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:Module:subdomainModuleFileDownload }

frontend_scholarship:
    path:     /scholarship
    defaults: { _controller: FrontendBundle:Default:scholarship }

frontend_scholarship_details:
    path:     /scholarship/{slug}
    defaults: { _controller: FrontendBundle:Default:scholarship }


frontend_studyabroad:
    path:     /studyabroad
    defaults: { _controller: FrontendBundle:Default:studyabroad }

frontend_tutor:
    path:     /tutor
    defaults: { _controller: FrontendBundle:Default:tutor }

frontend_tutor_subdomain:
    path:     /tutor/{subdomain}
    defaults: { _controller: FrontendBundle:Default:tutorDetails }

frontend_vendor:
    path:     /vendor
    defaults: { _controller: FrontendBundle:Default:vendor }

frontend_page:
    path:     /slug
    defaults: { _controller: FrontendBundle:Default:vendor }

frontend_newsletter:
    path:     /newsletter
    defaults: { _controller: FrontendBundle:Default:createNewsletter }