index:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:index}

education_institute:
    path:     /institute
    defaults: { _controller: FrontendBundle:Default:education }
    requirements: { _method: get }

education_admission:
    path:     /institute/admission
    defaults: { _controller: FrontendBundle:Module:admission }
    requirements: { _method: get }


education_institute_subdomain:
    path:     /institute/{subdomain}
    defaults: { _controller: FrontendBundle:Default:instituteDetail }

education_module:
    path:     /institute/{module}
    defaults: { _controller: FrontendBundle:Module:module }

education_subdomain_module:
    path:     /institute/{subdomain}/{module}
    defaults: { _controller: FrontendBundle:Module:subdomainModule }

education_subdomain_content:
    path:     /institute/{subdomain}/{slug}
    defaults: { _controller: FrontendBundle:Module: subdomainContent }


education_subdomain_module_content:
    path:     /institute/{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:Module:subdomainModuleContent }
    requirements: { _method: get }

education_subdomain_module_download:
    path:     /institute/{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:Module:subdomainModuleFileDownload }

education_scholarship:
    path:     /scholarship
    defaults: { _controller: FrontendBundle:Default:scholarship }

education_scholarship_details:
    path:     /scholarship/{slug}
    defaults: { _controller: FrontendBundle:Default:scholarship }


education_studyabroad:
    path:     /studyabroad
    defaults: { _controller: FrontendBundle:Default:studyabroad }

education_tutor:
    path:     /tutor
    defaults: { _controller: FrontendBundle:Default:tutor }

education_tutor_subdomain:
    path:     /tutor/{subdomain}
    defaults: { _controller: FrontendBundle:Default:tutorDetails }

education_vendor:
    path:     /vendor
    defaults: { _controller: FrontendBundle:Default:vendor }

education_page:
    path:     /slug
    defaults: { _controller: FrontendBundle:Default:vendor }

education_newsletter:
    path:     /newsletter
    defaults: { _controller: FrontendBundle:Default:createNewsletter }