webservice:
    path:     /
    defaults: { _controller: FrontendBundle:WebService:index }

webservice_module_page:
    path:     /{subdomain}/{module}/{slug}
    defaults: { _controller: FrontendBundle:WebServiceModule:modulePage }

webservice_contact:
    path:     /{subdomain}/contact
    defaults: { _controller: FrontendBundle:WebServiceModule:contact }

webservice_product:
    path:     /{subdomain}/product
    defaults: { _controller: FrontendBundle:WebServiceProduct:product }

webservice_customer_register:
    path:     /{subdomain}/register
    defaults: { _controller: FrontendBundle:WebServiceCustomer:register }

webservice_customer_create:
    path:     /{subdomain}/customer-registration-create
    defaults: { _controller: FrontendBundle:WebServiceCustomer:create }


webservice_customer_confirm:
    path:     /{subdomain}/customer-registration-confirm
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }


webservice_customer_login:
    path:     /{subdomain}/customer-login-check
    defaults: { _controller: UserBundle:Security:domainLogin }

webservice_login:
    path:     /{subdomain}/customer-login
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_otp:
    path:     /{subdomain}/customer-otp-check
    defaults: { _controller: FrontendBundle:WebServiceCustomer:confirm }

webservice_module:
    path:     /{subdomain}/{module}
    defaults: { _controller: FrontendBundle:WebServiceModule:module }

