pos_homepage:
    path:     /hello/{name}
    defaults: { _controller: PosBundle:Default:index }

pos_android:
    resource: "@PosBundle/Resources/config/routing/android.yml"
    prefix:   /android

pos_desktop:
    resource: "@PosBundle/Resources/config/routing/pos.yml"
    prefix:   /desktop