<?php

namespace Appstore\Bundle\ElectionBundle\Repository;
use Appstore\Bundle\DomainUserBundle\Entity\NotificationConfig;
use Appstore\Bundle\ElectionBundle\Entity\ElectionMember;
use Appstore\Bundle\ElectionBundle\Entity\ElectionMemberFamily;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;

/**
 * ElectionMemberFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionMemberFamilyRepository extends EntityRepository
{

	public function getFamilyMember(ElectionMember $member)
	{
		$entities = $member->getFamilyMembers();
		$data = '';
		$i = 1;

		/* @var $entity ElectionMemberFamily */

		foreach ($entities as $entity) {
			$data .= "<tr id='remove-{$entity->getId()}'>";
			$data .= "<td>{$i}</td>";
			$data .= "<td>{$entity->getName()}</td>";
			$data .= "<td>{$entity->getMobile()}</td>";
			$data .= "<td>{$entity->getNid()}</td>";
			$data .= "<td>{$entity->getRelation()}</td>";
			$data .= "<td><a data-id='{$entity->getId()}' data-url='/election/member/{$entity->getId()}/family-member-delete' href='javascript:' class='btn red mini delete' ><i class='icon-trash'></i></a></td>";
			$data .= '</tr>';
			$i++;
		}
		return $data;
	}
}
