<?php

namespace Appstore\Bundle\ElectionBundle\Repository;
use Appstore\Bundle\DomainUserBundle\Entity\NotificationConfig;
use Appstore\Bundle\ElectionBundle\Entity\ElectionSetup;
use Doctrine\ORM\EntityRepository;
use Setting\Bundle\ToolBundle\Entity\GlobalOption;

/**
 * ElectionVoteCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElectionSetupRepository extends EntityRepository
{
	public function insertTotalVote(ElectionSetup $entity)
	{

		$data = $this->totalVoteCenterUpdate($entity);
		$entity->setVoteCenter((int)$data['totalVoteCenter']);
		$entity->setTotalVoter((int)$data['totalVoter']);
		$entity->setMaleVoter((int)$data['maleVoter']);
		$entity->setFemaleVoter((int)$data['femaleVoter']);
		$entity->setOtherVoter((int)$data['otherVoter']);
	    $this->_em->persist($entity);
		$this->_em->flush();
		return $entity;

	}

	private function totalVoteCenterUpdate(ElectionSetup $setup){

		$qb = $this->_em->createQueryBuilder();
		$qb->from('ElectionBundle:ElectionVoteCenter','e');
		$qb->select('COUNT(e.id) as totalVoteCenter, SUM(e.maleVoter) as maleVoter, SUM(e.femaleVoter) as femaleVoter, SUM(e.otherVoter) as otherVoter, SUM(e.totalVoter) as totalVoter ');
		$qb->where('e.electionSetup ='.$setup->getId());
		$result  = $qb->getQuery()->getOneOrNullResult();
		return $result;
	}

	public function updateTotalVote(ElectionSetup $entity,$data)
	{
		$entity->setResultTotalVote((int)$data['resultTotalVote']);
		$entity->setResultInvalidVote((int)$data['resultInvalidVote']);
		$entity->setResultMaleVote((int)$data['resultMaleVote']);
		$entity->setResultFemaleVote((int)$data['resultFemaleVote']);
		$entity->setResultOtherVote((int)$data['resultOtherVote']);
		$entity->setActiveVoteCenter($this->castVoteCenter($entity,'Active'));
		$entity->setHoldVoteCenter($this->castVoteCenter($entity,'Hold'));
		$entity->setRejectedVoteCenter($this->castVoteCenter($entity,'Rejected'));
		$entity->setResultVoteCenter($entity->getActiveVoteCenter() + $entity->getHoldVoteCenter() + $entity->getRejectedVoteCenter());
		$this->_em->persist($entity);
		$this->_em->flush();
		return $entity;

	}

	public function castVoteCenter(ElectionSetup $setup, $process = '')
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->from('ElectionBundle:ElectionVoteCenter','e');
		$qb->addSelect('COUNT(e.process) as totalVoteCenter');
		$qb->where('e.electionSetup ='.$setup->getId());
		$qb->andWhere('e.process = :process');
		$qb->setParameter('process', $process);
		$result  = $qb->getQuery()->getOneOrNullResult();
		return $result['totalVoteCenter'];
	}

}
