advertisment:
    path:     /
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:index" }

advertisment_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:show" }

advertisment_new:
    path:     /new
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:new" }

advertisment_create:
    path:     /create
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:create" }
    methods:  POST

advertisment_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:edit" }

advertisment_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:status" }

advertisment_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:update" }
    methods:  [POST, PUT]

advertisment_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAdvertismentBundle:Advertisment:delete" }
    methods:  [POST, DELETE]
