
inventory_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customerInventory.yml"
    prefix:   /inventory/customer

restaurant_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customerrestaurant.yml"
    prefix:   /restaurant/customer

hms_customer:
    resource: "@DomainUserBundle/Resources/config/routing/hms_customer.yml"
    prefix:   /hms/patient

domain_sms:
    resource: "@DomainUserBundle/Resources/config/routing/sms.yml"
    prefix:   /association/sms

domain_notification:
    resource: "@DomainUserBundle/Resources/config/routing/notificationconfig.yml"
    prefix:   /sms/notification

domain_employee_branch:
    resource: "@DomainUserBundle/Resources/config/routing/employee_branch.yml"
    prefix:   /hr/branch-employee

domain_branch:
    resource: "@DomainUserBundle/Resources/config/routing/branches.yml"
    prefix:   /hr/branch

domain_store:
    resource: "@DomainUserBundle/Resources/config/routing/store.yml"
    prefix:   /hr/store

domain_customer_import:
    resource: "@DomainUserBundle/Resources/config/routing/gpcustomerimport.yml"
    prefix:   /hr/customer-import

domain_user_customer:
    resource: "@DomainUserBundle/Resources/config/routing/customer.yml"
    prefix:   /crm

domain_user_association:
    resource: "@DomainUserBundle/Resources/config/routing/association.yml"
    prefix:   /crm/association

domain_user_notepad:
    resource: "@DomainUserBundle/Resources/config/routing/notepad.yml"
    prefix:   /notepad

domain_user_domain:
    resource: "@DomainUserBundle/Resources/config/routing/domainuser.yml"
    prefix:   /hr/employee

domain_agent_user:
    resource: "@DomainUserBundle/Resources/config/routing/agent.yml"
    prefix:   /hr/agent

domain_agent_payment:
    resource: "@DomainUserBundle/Resources/config/routing/agentpayment.yml"
    prefix:   /hr/agent-payment
