business_stock_adjustment:
    path:     /
    defaults: { _controller: "BusinessBundle:StockAdjustment:index" }

business_stock_adjustment_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:StockAdjustment:new" }

business_stock_adjustment_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:StockAdjustment:create" }
    methods:  POST

business_stock_adjustment_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:StockAdjustment:delete" }

business_stock_adjustment_approved:
    path:     /{id}/approved
    defaults: { _controller: "BusinessBundle:StockAdjustment:approved" }