business_area:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessArea:index" }

business_area_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessArea:create" }
    methods:  POST

business_area_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:BusinessArea:edit" }

business_area_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:BusinessArea:update" }
    methods:  [POST, PUT]

business_area_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessArea:delete" }

business_area_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessArea:status" }

