business_brand:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessBrand:index" }

business_brand_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessBrand:create" }
    methods:  POST

business_brand_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:BusinessBrand:edit" }

business_brand_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:BusinessBrand:update" }
    methods:  [POST, PUT]

business_brand_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessBrand:delete" }

business_brand_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessBrand:status" }

