business_category:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessCategory:index" }

business_category_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessCategory:create" }
    methods:  POST

business_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:BusinessCategory:edit" }

business_category_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:BusinessCategory:update" }
    methods:  [POST, PUT]

business_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessCategory:delete" }

business_category_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessCategory:status" }

business_category_sorted:
    path:     /category-sorted
    defaults: { _controller: "BusinessBundle:BusinessCategory:sorted" }

