business_config_manage:
    path:     /manage
    defaults: { _controller: "BusinessBundle:BusinessConfig:manage" }


business_config_update:
    path:     /update
    defaults: { _controller: "BusinessBundle:BusinessConfig:update" }
    methods:  [POST, PUT]

