business_courier:
    path:     /
    defaults: { _controller: "BusinessBundle:Courier:index" }

business_courier_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:Courier:create" }
    methods:  POST

business_courier_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Courier:edit" }

business_courier_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Courier:update" }
    methods:  [POST, PUT]

business_courier_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Courier:delete" }

business_courier_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessArea:status" }

