business_distribution_return:
    path:     /
    defaults: { _controller: "BusinessBundle:DistributionReturn:index" }

business_distribution_return_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:DistributionReturn:show" }

business_distribution_return_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:DistributionReturn:new" }

business_distribution_return_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:DistributionReturn:create" }
    methods:  [POST]

business_distribution_return_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:DistributionReturn:edit" }

business_distribution_return_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:DistributionReturn:update" }
    methods:  [POST]

business_distribution_return_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:DistributionReturn:edit" }

business_distribution_return_approved:
    path:     /{id}/approved
    defaults: { _controller: "BusinessBundle:DistributionReturn:approved" }

business_distribution_return_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:DistributionReturn:delete" }

business_distribution_vendor_select:
    path:     /vendor-selection
    defaults: { _controller: "BusinessBundle:DistributionReturn:vendorSelect" }
    options:
           expose: true

business_distribution_vendor_update:
    path:     /{id}/vendor-purchase-return-update
    defaults: { _controller: "BusinessBundle:DistributionReturn:vendorUpdate" }
    methods:  POST
    options:
            expose: true

