business_invoice_distribution_invoice_return:
    path:     /{invoice}/invoice-item-return
    defaults: { _controller: "BusinessBundle:Distributor:salesReturnItem" }
    methods:  POST
    options:
            expose: true

business_invoice_distribution_store_payment:
    path:     /{invoice}/store-payment
    defaults: { _controller: "BusinessBundle:Distributor:storePayment" }
    methods:  POST
    options:
            expose: true

business_invoice_distribution_store_create:
    path:     /store-create
    defaults: { _controller: "BusinessBundle:Distributor:storeCreate" }
    methods:  POST
    options:
        expose: true

business_invoice_distributor_ledger_delete:
    path:     /{invoice}/{id}/delete-ledger
    defaults: { _controller: "BusinessBundle:Distributor:deleteLedger" }

business_invoice_distribution_store_balance:
    path:     /store-balance
    defaults: { _controller: "BusinessBundle:Distributor:storeBalance" }
    methods:  GET
    options:
        expose: true

business_invoice_distribution_return_item_delete:
    path:     /{invoice}/{id}/return-item-delete
    defaults: { _controller: "BusinessBundle:Distributor:deleteReturnItem" }


business_invoice_distribution:
    path:     /{id}/add-distribution
    defaults: { _controller: "BusinessBundle:Distributor:addDistribution" }
    methods:  POST
    options:
        expose: true

business_invoice_distribution_delete:
    path:     /{invoice}/{id}/distribution-delete
    defaults: { _controller: "BusinessBundle:Distributor:invoiceDistributionDelete" }

business_invoice_distribution_item_update:
    path:     /sales-distribution-item-update
    defaults: { _controller: "BusinessBundle:Distributor:invoiceDistributionItemUpdate" }
    methods:  POST
    options:
        expose: true

business_invoice_distributor_approve:
    path:     /{id}/approve
    defaults: { _controller: "BusinessBundle:Distributor:approve" }

