association_invoice_create:
       path:     /invoice-create
       defaults: { _controller: "CustomerBundle:Business:create" }
       methods:  [POST]


association_invoice_new:
       path:     /{customer}/invoice-create
       defaults: { _controller: "CustomerBundle:Business:new" }


