business_invoice:
    path:     /
    defaults: { _controller: "BusinessBundle:Invoice:index" }

business_invoice_condition:
    path:     /condition
    defaults: { _controller: "BusinessBundle:Invoice:invoiceCondition" }

business_invoice_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:Invoice:show" }

business_invoice_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:Invoice:new" }

business_invoice_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Invoice:edit" }

business_invoice_customer_update:
    path:     /invoice-customer-update
    defaults: { _controller: "BusinessBundle:Invoice:customerUpdate" }
    options:
            expose: true

business_invoice_customermobile_update:
    path:     /invoice-customer-mobile-update
    defaults: { _controller: "BusinessBundle:Invoice:customerMobileUpdate" }
    options:
            expose: true

business_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "BusinessBundle:Invoice:particularSearch" }
    options:
            expose: true

business_invoice_particular_search:
    path:     /invoice-particular-search
    defaults: { _controller: "BusinessBundle:Invoice:autoParticularSearch" }
    options:
            expose: true

business_item_unit_search:
    path:     /item-unit-search
    defaults: { _controller: "BusinessBundle:Invoice:autoUnitSearch" }
    options:
            expose: true

business_invoice_event:
    path:     /{id}/event
    defaults: { _controller: "BusinessBundle:Invoice:addEvent" }
    methods:  POST
    options:
            expose: true


business_invoice_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "BusinessBundle:Invoice:addParticular" }
    methods:  POST
    options:
            expose: true

business_invoice_discount_update:
    path:     /dicount-update
    defaults: { _controller: "BusinessBundle:Invoice:invoiceDiscountUpdate" }
    methods:  POST
    options:
            expose: true

business_invoice_accessories_add:
    path:     /{invoice}/stock-accessories
    defaults: { _controller: "BusinessBundle:Invoice:addAccessories" }
    methods:  POST
    options:
            expose: true

business_invoice_commission_add:
    path:     /{invoice}/sales-commission
    defaults: { _controller: "BusinessBundle:Invoice:addParticularCommission" }
    methods:  POST
    options:
            expose: true

business_invoice_banner_sign:
    path:     /{invoice}/stock-banner-sign
    defaults: { _controller: "BusinessBundle:Invoice:bannerSign" }
    methods:  POST
    options:
            expose: true

business_invoice_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "BusinessBundle:Invoice:approve" }

business_invoice_received:
    path:     /{id}/invoice-received
    defaults: { _controller: "BusinessBundle:Invoice:received" }

business_invoice_returned:
    path:     /{id}/invoice-returned
    defaults: { _controller: "BusinessBundle:Invoice:returned" }


business_invoice_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Invoice:update" }
    methods:  [POST, PUT]

business_invoice_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Invoice:delete" }


business_invoice_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "BusinessBundle:Invoice:invoiceParticularDelete" }

business_invoice_print:
    path:     /{id}/print
    defaults: { _controller: "BusinessBundle:Invoice:invoicePrint" }

business_invoice_posprint:
    path:     /{id}/pos-print
    defaults: { _controller: "BusinessBundle:Invoice:posPrint" }

business_invoice_chalan:
    path:     /{id}/chalan
    defaults: { _controller: "BusinessBundle:Invoice:invoiceChalan" }


business_invoice_empty_delete:
    path:     /delete/empty-invoice
    defaults: { _controller: "BusinessBundle:Invoice:deleteEmptyInvoice" }

business_invoice_commission_process:
    path:     /commission-process
    defaults: { _controller: "BusinessBundle:Invoice:commissionProcess" }


business_invoice_item_update:
    path:     /sales-item-update
    defaults: { _controller: "BusinessBundle:Invoice:invoiceItemUpdate" }
    methods:  POST
    options:
        expose: true

business_invoice_customer_search:
    path:     /invoice-customer-search
    defaults: { _controller: "BusinessBundle:Invoice:invoiceCustomerSelect" }
    methods:  GET
    options:
        expose: true

business_invoice_customer_inline_update:
    path:     /invoice-customer-inline-update
    defaults: { _controller: "BusinessBundle:Invoice:invoiceCustomerInlineUpdate" }
    methods:  POST
    options:
        expose: true

