business_itemimporter:
    path:     /
    defaults: { _controller: "BusinessBundle:ItemImporter:index" }

business_itemimporter_migration:
    path:     /{id}/data-migration
    defaults: { _controller: "BusinessBundle:ItemImporter:excelDataImport" }

business_itemimporter_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:ItemImporter:new" }

business_itemimporter_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:ItemImporter:create" }
    methods:  POST

business_itemimporter_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:ItemImporter:edit" }

business_itemimporter_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:ItemImporter:update" }
    methods:  [POST, PUT]

business_itemimporter_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:ItemImporter:delete" }


business_itemimporter_updated:
    path:     /{id}/data-updated
    defaults: { _controller: "BusinessBundle:ItemImporter:updated" }

business_itemimporter_reset:
    path:     /{ic}/data-reseted
    defaults: { _controller: "BusinessBundle:ItemImporter:reseted" }

business_itemimporter_restore:
    path:     /{ic}/data-restored
    defaults: { _controller: "BusinessBundle:ItemImporter:restored" }
