business_marketing:
    path:     /
    defaults: { _controller: "BusinessBundle:Marketing:index" }

business_marketing_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:Marketing:create" }
    methods:  POST

business_marketing_sales_target:
    path:     /sales-target
    defaults: { _controller: "BusinessBundle:Marketing:updateSalesTarget" }
    methods:  POST

business_marketing_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Marketing:edit" }

business_marketing_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Marketing:update" }
    methods:  [POST, PUT]

business_marketing_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Marketing:delete" }

business_marketing_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessArea:status" }

