business_particular:
    path:     /
    defaults: { _controller: "DmsBundle:Particular:index" }

business_particular_create:
    path:     /create
    defaults: { _controller: "DmsBundle:Particular:create" }
    methods:  POST

business_particular_edit:
    path:     /{id}/edit
    defaults: { _controller: "DmsBundle:Particular:edit" }

business_particular_update:
    path:     /{id}/update
    defaults: { _controller: "DmsBundle:Particular:update" }
    methods:  [POST, PUT]

business_particular_delete:
    path:     /{id}/delete
    defaults: { _controller: "DmsBundle:Particular:delete" }

business_particular_status:
    path:     /{id}/status
    defaults: { _controller: "DmsBundle:Particular:status" }