business_product:
    path:     /
    defaults: { _controller: "BusinessBundle:Product:index" }

business_product_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:Product:create" }
    methods:  POST

business_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:Product:edit" }

business_product_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Product:update" }
    methods:  [POST, PUT]

business_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:Product:delete" }

business_product_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:Product:status" }

business_product_inline:
    path:     /inline-update
    defaults: { _controller: "BusinessBundle:Product:inlineUpdate" }