business_production:
    path:     /
    defaults: { _controller: "BusinessBundle:Production:index" }

business_post_production:
    path:     /{id}/post
    defaults: { _controller: "BusinessBundle:Production:postProduction" }

business_pre_production:
    path:     /{id}/pre
    defaults: { _controller: "BusinessBundle:Production:preProduction" }

business_production_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Production:productionUpdate" }
    methods:  [POST, PUT]

business_pre_production_create:
    path:     /{item}/pre-production-create
    defaults: { _controller: "BusinessBundle:Production:preProductionCreate" }
    methods:  [POST]

business_pre_production_update:
    path:     /{id}/pre-production-update
    defaults: { _controller: "BusinessBundle:Production:preProductionUpdate" }
    methods:  [POST, PUT]

business_pre_production_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:Production:show" }

business_pre_production_delete:
    path:     /{particular}/{id}/delete
    defaults: { _controller: "BusinessBundle:Production:delete" }

business_production_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "BusinessBundle:Production:particularSearch" }


business_production_particular_add:
    path:     /{id}/particular-add
    defaults: { _controller: "BusinessBundle:Production:addParticular" }
    methods:  POST
    options:
            expose: true

business_production_approve:
    path:     /{id}/approve
    defaults: { _controller: "BusinessBundle:Production:approved" }
    options:
            expose: true

