business_purchase_return:
    path:     /
    defaults: { _controller: "BusinessBundle:PurchaseReturn:index" }

business_purchase_return_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:PurchaseReturn:show" }

business_purchase_return_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:PurchaseReturn:new" }

business_purchase_return_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:PurchaseReturn:create" }
    methods:  [POST]

business_purchase_return_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:PurchaseReturn:edit" }

business_purchase_return_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:PurchaseReturn:update" }
    methods:  [POST]

business_purchase_return_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:PurchaseReturn:edit" }

business_purchase_return_approved:
    path:     /{id}/approved
    defaults: { _controller: "BusinessBundle:PurchaseReturn:approved" }

business_purchase_return_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:PurchaseReturn:delete" }

business_purchase_vendor_select:
    path:     /vendor-selection
    defaults: { _controller: "BusinessBundle:PurchaseReturn:vendorSelect" }
    options:
           expose: true

business_purchase_vendor_update:
    path:     /{id}/vendor-purchase-return-update
    defaults: { _controller: "BusinessBundle:PurchaseReturn:vendorUpdate" }
    methods:  POST
    options:
            expose: true

