business_reverse:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessReverse:index" }

business_purchase_reverse:
    path:     /{id}/purchase
    defaults: { _controller: "BusinessBundle:Purchase:reverse" }

business_sales_reverse:
    path:     /{id}/sales
    defaults: { _controller: "BusinessBundle:Invoice:invoiceReverse" }

business_reverse_show:
    path:     /{id}/show
    defaults: { _controller: "BusinessBundle:BusinessReverse:show" }

