business_stock_transfer:
    path:     /
    defaults: { _controller: "BusinessBundle:Production:index" }

business_post_transfer:
    path:     /{id}/post
    defaults: { _controller: "BusinessBundle:Production:postProduction" }

business_pre_transfer:
    path:     /{id}/pre
    defaults: { _controller: "BusinessBundle:Production:preProduction" }

business_transfer_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:Production:productionUpdate" }
    methods:  [POST, PUT]

business_transfer_create:
    path:     /{item}/pre-production-create
    defaults: { _controller: "BusinessBundle:Production:preProductionCreate" }
    methods:  [POST]

business_transfer_delete:
    path:     /{particular}/{id}/delete
    defaults: { _controller: "BusinessBundle:Production:delete" }

business_transfer_particular_search:
    path:     /{id}/particular-search
    defaults: { _controller: "BusinessBundle:Production:particularSearch" }


business_transfer_particular_add:
    path:     /{id}/particular-add
    defaults: { _controller: "BusinessBundle:Production:addParticular" }
    methods:  POST
    options:
            expose: true

