business_store_ledger:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessStoreLedger:index" }

business_store_ledger_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:BusinessStoreLedger:new" }

business_store_ledger_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessStoreLedger:create" }
    methods:  POST

business_store_ledger_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessStoreLedger:delete" }

business_store_ledger_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessStoreLedger:status" }
