business_store:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessStore:index" }

business_store_new:
    path:     /new
    defaults: { _controller: "BusinessBundle:BusinessStore:new" }

business_store_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessStore:create" }
    methods:  POST

business_store_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:BusinessStore:edit" }

business_store_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:BusinessStore:update" }
    methods:  [POST, PUT]

business_store_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessStore:delete" }

business_store_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessStore:status" }

