business_wearhouse:
    path:     /
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:index" }

business_wearhouse_create:
    path:     /create
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:create" }
    methods:  POST

business_wearhouse_edit:
    path:     /{id}/edit
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:edit" }

business_wearhouse_update:
    path:     /{id}/update
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:update" }
    methods:  [POST, PUT]

business_wearhouse_delete:
    path:     /{id}/delete
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:delete" }

business_wearhouse_status:
    path:     /{id}/status
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:status" }

business_wearhouse_sorted:
    path:     /category-sorted
    defaults: { _controller: "BusinessBundle:BusinessWearHouse:sorted" }

