product_product_productreview:
    resource: "@ProductProductBundle/Resources/config/routing/productreview.yml"
    prefix:   /productreview

product_product_collection:
    resource: "@ProductProductBundle/Resources/config/routing/collection.yml"
    prefix:   /collection

product_product_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProductProductBundle:Default:index }

ProductProductBundle_product:
    resource: "@ProductProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

ProductProductBundle_category:
    resource: "@ProductProductBundle/Resources/config/routing/category.yml"
    prefix:   /category

ProductProductBundle_categorygrouping:
        resource: "@ProductProductBundle/Resources/config/routing/categorygrouping.yml"
        prefix:   /categorygrouping
