parameters:
#    product_product.example.class: Product\Bundle\ProductBundle\Example

services:
#    product_product.example:
#        class: %product_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
