setting_tool_sms:
    resource: "@SettingToolBundle/Resources/config/routing/smssender.yml"
    prefix:   /sms/sender-sms

setting_tool_invoicemodule:
    resource: "@SettingToolBundle/Resources/config/routing/invoicemodule.yml"
    prefix:   /domain/invoicemodule

setting_tool_sidebar:
    resource: "@SettingToolBundle/Resources/config/routing/sidebar.yml"
    prefix:   /domain/sidebar

setting_tool_designation:
    resource: "@SettingToolBundle/Resources/config/routing/designation.yml"
    prefix:   /admin/designation

setting_tool_color:
    resource: "@SettingToolBundle/Resources/config/routing/color.yml"
    prefix:   /admin/color

setting_tool_testimonial:
    resource: "@SettingToolBundle/Resources/config/routing/applicationtestimonial.yml"
    prefix:   /admin/testimonial

setting_tool_size:
    resource: "@SettingToolBundle/Resources/config/routing/size.yml"
    prefix:   /admin/size

setting_tool_hms_cateory:
    resource: "@SettingToolBundle/Resources/config/routing/category.yml"
    prefix:   /admin/hms-category

setting_tool_invoicesmsemail:
    resource: "@SettingToolBundle/Resources/config/routing/invoicesmsemail.yml"
    prefix:   /sms/invoice-sms-email

setting_tool_smsbulk:
    resource: "@SettingToolBundle/Resources/config/routing/smsbulk.yml"
    prefix:   /sms/bulk-sms

setting_tool_bankaccount:
    resource: "@SettingToolBundle/Resources/config/routing/portalbankaccount.yml"
    prefix:   /admin/bank

setting_tool_bkash:
    resource: "@SettingToolBundle/Resources/config/routing/portalmobilebankaccount.yml"
    prefix:   /admin/mobile-bank

setting_tool_applicationpricing:
    resource: "@SettingToolBundle/Resources/config/routing/applicationpricing.yml"
    prefix:   /admin/applicationpricing

setting_tool_domain:
    resource: "@SettingToolBundle/Resources/config/routing/domain.yml"
    prefix:   /admin/domain

setting_tool_tools_smspricing:
    resource: "@SettingToolBundle/Resources/config/routing/smsemailpricing.yml"
    prefix:   /admin/smspricing

setting_tool_adstool:
    resource: "@SettingToolBundle/Resources/config/routing/adstool.yml"
    prefix:   /admin/adstool

setting_tool_theme:
    resource: "@SettingToolBundle/Resources/config/routing/theme.yml"
    prefix:   /admin/theme

setting_tool_templating:
    resource: "@SettingToolBundle/Resources/config/routing/templating.yml"
    prefix:   /vendor/templating

setting_tool_barcode:
    resource: "@SettingToolBundle/Resources/config/routing/barcode.yml"
    prefix:   /barcode

setting_tool_appmodule:
    resource: "@SettingToolBundle/Resources/config/routing/appmodule.yml"
    prefix:   /admin/appmodule

setting_tool_mobileicon:
    resource: "@SettingToolBundle/Resources/config/routing/mobileicon.yml"
    prefix:   /domain/mobileicon

setting_tool_footersetting:
    resource: "@SettingToolBundle/Resources/config/routing/footersetting.yml"
    prefix:   /domain/footersetting

setting_tool_institutelevel:
    resource: "@SettingToolBundle/Resources/config/routing/institutelevel.yml"
    prefix:   /domain/institutelevel

setting_tool_course:
    resource: "@SettingToolBundle/Resources/config/routing/course.yml"
    prefix:   /domain/course

setting_tool_branding:
    resource: "@SettingToolBundle/Resources/config/routing/branding.yml"
    prefix:   /admin/branding

setting_tool_homepage:
    path:     /hello/{name}
    defaults: { _controller: SettingToolBundle:Default:index }

SettingToolBundle_syndicate:
        resource: "@SettingToolBundle/Resources/config/routing/syndicate.yml"
        prefix:   /admin/syndicate

SettingToolBundle_globaloption:
        resource: "@SettingToolBundle/Resources/config/routing/globaloption.yml"
        prefix:   /domain/globaloption

SettingToolBundle_webtheme:
        resource: "@SettingToolBundle/Resources/config/routing/webtheme.yml"
        prefix:   /webtheme

SettingToolBundle_mobiletheme:
        resource: "@SettingToolBundle/Resources/config/routing/mobiletheme.yml"
        prefix:   /mobiletheme

SettingToolBundle_sitesetting:
        resource: "@SettingToolBundle/Resources/config/routing/sitesetting.yml"
        prefix:   /admin/sitesetting

SettingToolBundle_syndicatemodule:
        resource: "@SettingToolBundle/Resources/config/routing/syndicatemodule.yml"
        prefix:   /admin/syndicatemodule

SettingToolBundle_module:
        resource: "@SettingToolBundle/Resources/config/routing/module.yml"
        prefix:   /admin/module

SettingToolBundle_transaction_method:
        resource: "@SettingToolBundle/Resources/config/routing/transactionmethod.yml"
        prefix:   /admin/transaction-method

SettingToolBundle_medicine:
        resource: "@SettingToolBundle/Resources/config/routing/medicineimport.yml"
        prefix:   /admin/medicine-import

SettingToolBundle_medicinebrand:
        resource: "@SettingToolBundle/Resources/config/routing/medicinebrand.yml"
        prefix:   /admin/medicine-brand

SettingToolBundle_taxtarrif_upload:
        resource: "@SettingToolBundle/Resources/config/routing/tarrif_upload.yml"
        prefix:   /admin/tariff-upload

SettingToolBundle_taxtarrif:
        resource: "@SettingToolBundle/Resources/config/routing/tariff.yml"
        prefix:   /admin/tax-tariff


