setting_content_sponsor:
    resource: "@SettingContentBundle/Resources/config/routing/sponsor.yml"
    prefix:    /website/sponsor

setting_content_client:
    resource: "@SettingContentBundle/Resources/config/routing/client.yml"
    prefix:    /website/client

setting_content_portfolio:
    resource: "@SettingContentBundle/Resources/config/routing/portfolio.yml"
    prefix:    /website/portfolio

setting_content_category:
    resource: "@SettingContentBundle/Resources/config/routing/modulecategory.yml"
    prefix:    /website/category

setting_content_service:
    resource: "@SettingContentBundle/Resources/config/routing/service.yml"
    prefix:    /website/service

setting_content_product:
    resource: "@SettingContentBundle/Resources/config/routing/product.yml"
    prefix:    /website/product

setting_content_mallconnect:
    resource: "@SettingContentBundle/Resources/config/routing/mallconnect.yml"
    prefix:   /website/mallconnect

setting_content_mallshop:
    resource: "@SettingContentBundle/Resources/config/routing/mallshop.yml"
    prefix:   /website/mallshop

setting_content_faq:
    resource: "@SettingContentBundle/Resources/config/routing/faq.yml"
    prefix:   /website/faq

setting_content_mail:
    resource: "@SettingContentBundle/Resources/config/routing/emailbox.yml"
    prefix:   /website/mail

setting_content_siteslider:
    resource: "@SettingContentBundle/Resources/config/routing/siteslider.yml"
    prefix:   /admin/siteslider

setting_content_sitecontent:
    resource: "@SettingContentBundle/Resources/config/routing/sitecontent.yml"
    prefix:   /admin/sitecontent

setting_content_sitetestimonial:
    resource: "@SettingContentBundle/Resources/config/routing/sitetestimonial.yml"
    prefix:   /admin/site-testimonial

setting_content_siteteam:
    resource: "@SettingContentBundle/Resources/config/routing/siteteam.yml"
    prefix:   /admin/site-team

SettingContentBundle_homeslider:
    resource: "@SettingContentBundle/Resources/config/routing/homeslider.yml"
    prefix:   /website/homeslider


SettingContentBundle_homepage:
    resource: "@SettingContentBundle/Resources/config/routing/homepage.yml"
    prefix:   /website/homepage

SettingContentBundle_contactpage:
    resource: "@SettingContentBundle/Resources/config/routing/contactpage.yml"
    prefix:   /website/contactpage

SettingContentBundle_page:
    resource: "@SettingContentBundle/Resources/config/routing/page.yml"
    prefix:   /website/page

SettingContentBundle_news:
    resource: "@SettingContentBundle/Resources/config/routing/news.yml"
    prefix:   /website/news

SettingContentBundle_blackout:
    resource: "@SettingContentBundle/Resources/config/routing/blackout.yml"
    prefix:   /website/blackout

SettingContentBundle_eventcalender:
    resource: "@SettingContentBundle/Resources/config/routing/eventcalender.yml"
    prefix:   /website/eventcalender

SettingContentBundle_classroutine:
    resource: "@SettingContentBundle/Resources/config/routing/classroutine.yml"
    prefix:   /website/classroutine

SettingContentBundle_blog:
    resource: "@SettingContentBundle/Resources/config/routing/blog.yml"
    prefix:   /website/blog

SettingContentBundle_team:
    resource: "@SettingContentBundle/Resources/config/routing/team.yml"
    prefix:   /website/team

SettingContentBundle_testimonial:
    resource: "@SettingContentBundle/Resources/config/routing/testimonial.yml"
    prefix:   /website/testimonial

SettingContentBundle_timeline:
    resource: "@SettingContentBundle/Resources/config/routing/timeline.yml"
    prefix:   /website/timeline

SettingContentBundle_branch:
    resource: "@SettingContentBundle/Resources/config/routing/branch.yml"
    prefix:   /website/branch

SettingContentBundle_syndicatecontent:
    resource: "@SettingContentBundle/Resources/config/routing/syndicatecontent.yml"
    prefix:   /website/syndicatecontent

SettingContentBundle_admission:
    resource: "@SettingContentBundle/Resources/config/routing/admission.yml"
    prefix:   /website/admission

SettingContentBundle_event:
    resource: "@SettingContentBundle/Resources/config/routing/event.yml"
    prefix:   /website/event

SettingContentBundle_noticeboard:
    resource: "@SettingContentBundle/Resources/config/routing/noticeboard.yml"
    prefix:   /website/noticeboard

SettingContentBundle_contactmessage:
    resource: "@SettingContentBundle/Resources/config/routing/contactmessage.yml"
    prefix:   /website/contactmessage

SettingContentBundle_admissioncomment:
    resource: "@SettingContentBundle/Resources/config/routing/admissioncomment.yml"
    prefix:   /website/admissioncomment

SettingContentBundle_blogcomment:
    resource: "@SettingContentBundle/Resources/config/routing/blogcomment.yml"
    prefix:   /website/blogcomment

