parameters:
#    setting_content.example.class: Setting\Bundle\ContentBundle\Example

services:
#    setting_content.example:
#        class: %setting_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

