medicine_medicine_brand:
    resource: "@MedicineBundle/Resources/config/routing/medicine.yml"
    prefix:   /drug

medicine_medicine_user:
    resource: "@MedicineBundle/Resources/config/routing/medicineuser.yml"
    prefix:   /drug-user

medicine_medicine_company:
    resource: "@MedicineBundle/Resources/config/routing/medicinecompany.yml"
    prefix:   /drug-company

medicine_medicine_config:
    resource: "@MedicineBundle/Resources/config/routing/config.yml"
    prefix:   /config

medicine_medicine_stock:
    resource: "@MedicineBundle/Resources/config/routing/stock.yml"
    prefix:   /stock

medicine_medicine_adjustment:
    resource: "@MedicineBundle/Resources/config/routing/adjustment.yml"
    prefix:   /stock-adjustment

medicine_medicine_sales_user:
    resource: "@MedicineBundle/Resources/config/routing/salesuser.yml"
    prefix:   /sales-user

medicine_medicine_minimum_stock:
    resource: "@MedicineBundle/Resources/config/routing/medicineminimumstock.yml"
    prefix:   /medicine-minimum-stock

medicine_medicine_sales:
    resource: "@MedicineBundle/Resources/config/routing/sales.yml"
    prefix:   /sales

medicine_medicine_sales_temporary:
    resource: "@MedicineBundle/Resources/config/routing/salestemporary.yml"
    prefix:   /sales-temporary

medicine_medicine_purchase:
    resource: "@MedicineBundle/Resources/config/routing/purchase.yml"
    prefix:   /purchase

medicine_medicine_prepurchase:
    resource: "@MedicineBundle/Resources/config/routing/prepurchase.yml"
    prefix:   /pre-purchase

medicine_medicine_stockhouse:
    resource: "@MedicineBundle/Resources/config/routing/stockhouse.yml"
    prefix:   /stock-wear-house

medicine_medicine_instantpurchase:
    resource: "@MedicineBundle/Resources/config/routing/instantpurchase.yml"
    prefix:   /instant-purchase

medicine_medicine_vendor:
    resource: "@MedicineBundle/Resources/config/routing/vendor.yml"
    prefix:   /vendor

medicine_medicine_damage:
    resource: "@MedicineBundle/Resources/config/routing/damage.yml"
    prefix:   /damage

medicine_medicine_purchase_return:
    resource: "@MedicineBundle/Resources/config/routing/purchasereturn.yml"
    prefix:   /purchase-return

medicine_medicine_transfer:
    resource: "@MedicineBundle/Resources/config/routing/medicinetransfer.yml"
    prefix:   /medicine-transfer

medicine_medicine_sales_return:
    resource: "@MedicineBundle/Resources/config/routing/salesreturn.yml"
    prefix:   /sales-return

medicine_medicine_particular:
    resource: "@MedicineBundle/Resources/config/routing/particular.yml"
    prefix:   /particular

medicine_medicine_report:
    resource: "@MedicineBundle/Resources/config/routing/report.yml"
    prefix:   /report

medicine_medicine_reverse:
    resource: "@MedicineBundle/Resources/config/routing/reverse.yml"
    prefix:   /reverse

medicine_import:
    resource: "@MedicineBundle/Resources/config/routing/medicinestockimport.yml"
    prefix:   /medicine-stock-import

medicine_homepage:
    path:     /
    defaults: { _controller: MedicineBundle:Default:index }

medicine_update_expiration:
    path:     /update-expiration-medicine
    defaults: { _controller: MedicineBundle:Default:updateExpirationMedicine }

medicine_particular_migration:
    path:     /copy-particular-migration
    defaults: { _controller: MedicineBundle:Default:copyToMedicineParticular }

medicine_stock_migration:
    path:     /copy-stock-migration
    defaults: { _controller: MedicineBundle:Default:copyToMedicineStock }

medicine_ecommerce_migration:
    path:     /copy-ecommerce-migration
    defaults: { _controller: MedicineBundle:Default:copyStockToEcommerce }

medicine_vendor_migration:
    path:     /copy-vendor-migration
    defaults: { _controller: MedicineBundle:Default:copyToMedicineVendor }

medicine_report_vendor_sales:
    path:     /vendor-purchase-sales
    defaults: { _controller: "MedicineBundle:Default:vendorCustomerAccount" }

medicine_update_remaining_quantity:
    path:     /update-remaining-quantity
    defaults: { _controller: "MedicineBundle:Default:updateRemainingQuantity" }

medicine_report_vendor_sales_medicine:
    path:     /vendor-purchase-sales-medicine
    defaults: { _controller: "MedicineBundle:Default:vendorCustomerMedicine" }

medicine_report_vendor_payment_receive:
    path:     /{vendor}/vendor-payment-receive
    defaults: { _controller: "MedicineBundle:Default:vendorPaymentReceive" }

medicine_group_purchase_reverse:
    path:     /group/purchase/reverse
    defaults: { _controller: "MedicineBundle:Purchase:groupReverse" }

medicine_group_purchase_approved:
    path:      /group/purchase/approved
    defaults: { _controller: "MedicineBundle:Purchase:groupApproved" }

medicine_group_sales_reverse:
    path:     /group/sales/reverse
    defaults: { _controller: "MedicineBundle:Sales:groupReverse" }

medicine_group_sales_approved:
    path:      /group/sales/approved
    defaults: { _controller: "MedicineBundle:Sales:groupApproved" }





