parameters:
#    setting_location.example.class: Setting\Bundle\LocationBundle\Example

services:
#    setting_location.example:
#        class: %setting_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
