admissioncomment:
    path:     /
    defaults: { _controller: "SettingContentBundle:AdmissionComment:index" }

admissioncomment_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:AdmissionComment:show" }

admissioncomment_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:AdmissionComment:new" }

admissioncomment_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:AdmissionComment:create" }
    requirements: { _method: post }

admissioncomment_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:AdmissionComment:edit" }

admissioncomment_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:AdmissionComment:update" }
    requirements: { _method: post|put }

admissioncomment_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:AdmissionComment:delete" }
    requirements: { _method: post|delete }
