admission:
    path:     /
    defaults: { _controller: "SettingContentBundle:Admission:index" }

admission_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Admission:show" }

admission_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Admission:new" }

admission_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Admission:create" }
    requirements: { _method: post }

admission_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Admission:edit" }

admission_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Admission:update" }
    requirements: { _method: post|put }

admission_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Admission:delete" }
    requirements: { _method: post|delete }

admission_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Admission:status" }

admission_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle:Admission:printList" }

admission_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:Admission:pdfList" }

admission_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:Admission:exportList" }

admission_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:Admission:printDetails" }

admission_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:Admission:pdfDetails" }

admission_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:Admission:import" }

admission_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:Admission:exportDetails" }
