blackout:
    path:     /
    defaults: { _controller: "SettingContentBundle:Blackout:index" }

blackout_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Blackout:show" }

blackout_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Blackout:new" }

blackout_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Blackout:create" }
    requirements: { _method: post }

blackout_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Blackout:edit" }

blackout_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Blackout:update" }
    requirements: { _method: post|put }

blackout_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Blackout:delete" }
    requirements: { _method: post|delete }
