blogcomment:
    path:     /
    defaults: { _controller: "SettingContentBundle:BlogComment:index" }

blogcomment_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:BlogComment:show" }

blogcomment_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:BlogComment:new" }

blogcomment_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:BlogComment:create" }
    requirements: { _method: post }

blogcomment_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:BlogComment:edit" }

blogcomment_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:BlogComment:update" }
    requirements: { _method: post|put }

blogcomment_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:BlogComment:delete" }
    requirements: { _method: post|delete }
