blog:
    path:     /
    defaults: { _controller: "SettingContentBundle:Blog:index" }

blog_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Blog:show" }

blog_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Blog:new" }

blog_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Blog:create" }
    requirements: { _method: post }

blog_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Blog:edit" }

blog_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Blog:update" }
    requirements: { _method: post|put }

blog_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Blog:delete" }


blog_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Blog:status" }

