classroutine:
    path:     /
    defaults: { _controller: "SettingContentBundle:ClassRoutine:index" }

classroutine_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:ClassRoutine:show" }

classroutine_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:ClassRoutine:new" }

classroutine_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:ClassRoutine:create" }
    requirements: { _method: post }

classroutine_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:ClassRoutine:edit" }

classroutine_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:ClassRoutine:update" }
    requirements: { _method: post|put }

classroutine_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:ClassRoutine:delete" }
    requirements: { _method: post|delete }
