contactmessage:
    path:     /
    defaults: { _controller: "SettingContentBundle:ContactMessage:index" }

contactmessage_archive:
    path:     /archive
    defaults: { _controller: "SettingContentBundle:ContactMessage:archive" }


contactmessage_update:
    path:     /update
    defaults: { _controller: "SettingContentBundle:ContactMessage:update" }
    requirements: { _method: post }


contactmessage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:ContactMessage:delete" }
