contactpage:
    path:     /
    defaults: { _controller: "SettingContentBundle:ContactPage:index" }

contactpage_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:ContactPage:show" }

contactpage_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:ContactPage:new" }

contactpage_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:ContactPage:create" }
    requirements: { _method: post }

contactpage_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:ContactPage:edit" }

contactpage_modify:
    path:     /modify
    defaults: { _controller: "SettingContentBundle:ContactPage:modify" }

contactpage_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:ContactPage:update" }
    requirements: { _method: post|put }

contactpage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:ContactPage:delete" }
    requirements: { _method: post|delete }
