mail:
    path:     /
    defaults: { _controller: "SettingContentBundle:EmailBox:index" }

mail_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:EmailBox:show" }

mail_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:EmailBox:new" }

mail_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:EmailBox:create" }
    methods:  POST

mail_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:EmailBox:edit" }

mail_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:EmailBox:update" }
    methods:  [POST, PUT]

mail_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:EmailBox:delete" }
    methods:  [POST, DELETE]
