eventcalender:
    path:     /
    defaults: { _controller: "SettingContentBundle:EventCalender:index" }

eventcalender_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:EventCalender:show" }

eventcalender_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:EventCalender:new" }

eventcalender_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:EventCalender:create" }
    requirements: { _method: post }

eventcalender_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:EventCalender:edit" }

eventcalender_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:EventCalender:update" }
    requirements: { _method: post|put }

eventcalender_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:EventCalender:delete" }
    requirements: { _method: post|delete }
