homepage_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:HomePage:edit" }

homepage_modify:
    path:     /modify
    defaults: { _controller: "SettingContentBundle:HomePage:modify" }

homepage_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:HomePage:update" }
    requirements: { _method: post|put }

homepage_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:HomePage:delete" }

