homeslider:
    path:     /
    defaults: { _controller: "SettingContentBundle:HomeSlider:index" }

homeslider_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:HomeSlider:show" }

homeslider_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:HomeSlider:new" }

homeslider_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:HomeSlider:create" }
    methods:  POST

homeslider_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:HomeSlider:edit" }

homeslider_modify:
    path:     /modify
    defaults: { _controller: "SettingContentBundle:HomeSlider:modify" }

homeslider_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:HomeSlider:update" }
    methods:  [POST, PUT]

homeslider_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:HomeSlider:delete" }

homeslider_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:HomeSlider:status" }

homeslider_sorting:
    path:     /sorting
    defaults: { _controller: "SettingContentBundle:HomeSlider:sorting" }

homeslider_sorted:
    path:     /sorted
    defaults: { _controller: "SettingContentBundle:HomeSlider:sorted" }
