mallshop:
    path:     /
    defaults: { _controller: "SettingContentBundle:MallShop:index" }

mallshop_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:MallShop:show" }

mallshop_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:MallShop:new" }

mallshop_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:MallShop:create" }
    methods:  POST

mallshop_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:MallShop:edit" }

mallshop_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:MallShop:status" }

mallshop_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:MallShop:update" }
    methods:  [POST, PUT]

mallshop_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:MallShop:delete" }
