mallconnect:
    path:     /
    defaults: { _controller: "SettingContentBundle:MallConnect:index" }

mallconnect_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:MallConnect:show" }

mallconnect_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:MallConnect:new" }

mallconnect_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:MallConnect:create" }
    methods:  POST

mallconnect_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:MallConnect:edit" }

mallconnect_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:MallConnect:status" }

mallconnect_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:MallConnect:update" }
    methods:  [POST, PUT]

mallconnect_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:MallConnect:delete" }
