modulecategory:
    path:     /
    defaults: { _controller: "SettingContentBundle:ModuleCategory:index" }

modulecategory_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:ModuleCategory:show" }

modulecategory_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:ModuleCategory:new" }

modulecategory_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:ModuleCategory:create" }
    methods:  POST

modulecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:ModuleCategory:edit" }

modulecategory_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:ModuleCategory:status" }

modulecategory_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:ModuleCategory:update" }
    methods:  [POST, PUT]

modulecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:ModuleCategory:delete" }
