pages_delete:
    path:     listing/delete
    defaults: { _controller: "SettingContentBundle:Page:listingDelete" }

page:
    path:     /
    defaults: { _controller: "SettingContentBundle:Page:index" }

page_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Page:show" }

page_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Page:new" }

page_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Page:create" }
    requirements: { _method: post }

page_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Page:edit" }

page_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Page:update" }
    requirements: { _method: post|put }

page_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Page:delete" }

page_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Page:status" }

page_meta_delete:
    path:     /{id}/meta-delete
    defaults: { _controller: "SettingContentBundle:Page:metaDelete" }
    options:
       expose: true

page_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle:Page:printList" }

page_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:Page:pdfList" }

page_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:Page:exportList" }

page_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:Page:printDetails" }

page_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:Page:pdfDetails" }

page_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:Page:import" }

page_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:Page:exportDetails" }

