portfolio:
    path:     /
    defaults: { _controller: "SettingContentBundle:Portfolio:index" }

portfolio_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Portfolio:show" }

portfolio_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Portfolio:new" }

portfolio_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Portfolio:create" }
    methods:  POST

portfolio_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Portfolio:edit" }

portfolio_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Portfolio:status" }

portfolio_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Portfolio:update" }
    methods:  [POST, PUT]

portfolio_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Portfolio:delete" }

