product:
    path:     /
    defaults: { _controller: "SettingContentBundle:Product:index" }

product_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Product:new" }

product_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Product:create" }
    methods:  POST

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Product:edit" }

product_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Product:status" }

product_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Product:update" }
    methods:  [POST, PUT]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Product:delete" }

product_copy:
    path:     /{id}/product-copy
    defaults: { _controller: "SettingContentBundle:Product:copy" }

