sitecontent:
    path:     /
    defaults: { _controller: "SettingContentBundle:SiteContent:index" }

sitecontent_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:SiteContent:show" }

sitecontent_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:SiteContent:new" }

sitecontent_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:SiteContent:create" }
    methods:  POST

sitecontent_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:SiteContent:edit" }

sitecontent_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:SiteContent:status" }

sitecontent_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:SiteContent:update" }
    methods:  [POST, PUT]

sitecontent_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:SiteContent:delete" }
    methods:  [POST, DELETE]
