sitetestimonial:
    path:     /
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:index" }

sitetestimonial_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:show" }

sitetestimonial_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:new" }

sitetestimonial_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:create" }
    methods:  POST

sitetestimonial_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:edit" }

sitetestimonial_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:status" }

sitetestimonial_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:update" }
    methods:  [POST, PUT]

sitetestimonial_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:SiteTestimonial:delete" }

