siteteam:
    path:     /
    defaults: { _controller: "SettingContentBundle:SiteTeam:index" }

siteteam_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:SiteTeam:show" }

siteteam_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:SiteTeam:new" }

siteteam_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:SiteTeam:create" }
    methods:  POST

siteteam_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:SiteTeam:edit" }

siteteam_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:SiteTeam:status" }

siteteam_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:SiteTeam:update" }
    methods:  [POST, PUT]

siteteam_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:SiteTeam:delete" }

