siteslider:
    path:     /
    defaults: { _controller: "SettingContentBundle:SiteSlider:index" }

siteslider_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:SiteSlider:show" }

siteslider_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:SiteSlider:new" }

siteslider_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:SiteSlider:create" }
    methods:  POST

siteslider_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:SiteSlider:edit" }

siteslider_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:SiteSlider:status" }

siteslider_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:SiteSlider:update" }
    methods:  [POST, PUT]

siteslider_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:SiteSlider:delete" }
    methods:  [POST, DELETE]

siteslider_sorting:
    path:     /sorting
    defaults: { _controller: "SettingContentBundle:SiteSlider:sorting" }
siteslider_sorted:
    path:     /sorted
    defaults: { _controller: "SettingContentBundle:SiteSlider:sorted" }

