sponsor:
    path:     /
    defaults: { _controller: "SettingContentBundle:Sponsor:index" }

sponsor_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Sponsor:show" }

sponsor_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Sponsor:new" }

sponsor_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Sponsor:create" }
    methods:  POST

sponsor_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Sponsor:edit" }

sponsor_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Sponsor:status" }

sponsor_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Sponsor:update" }
    methods:  [POST, PUT]

sponsor_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Sponsor:delete" }

