syndicatecontent:
    path:     /
    defaults: { _controller: "SettingContentBundle:SyndicateContent:index" }

syndicatecontent_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:SyndicateContent:show" }

syndicatecontent_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:SyndicateContent:new" }

syndicatecontent_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:SyndicateContent:create" }
    requirements: { _method: post }

syndicatecontent_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:SyndicateContent:edit" }

syndicatecontent_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:SyndicateContent:update" }
    requirements: { _method: post|put }

syndicatecontent_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:SyndicateContent:delete" }
    requirements: { _method: post|delete }
