team:
    path:     /
    defaults: { _controller: "SettingContentBundle:Team:index" }

team_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Team:show" }

team_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Team:new" }

team_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Team:create" }
    requirements: { _method: post }

team_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Team:edit" }

team_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Team:update" }
    requirements: { _method: post|put }

team_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Team:delete" }

team_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Team:status" }

