testimonial:
    path:     /
    defaults: { _controller: "SettingContentBundle:Testimonial:index" }

testimonial_show:
    path:     /{id}/show
    defaults: { _controller: "SettingContentBundle:Testimonial:show" }

testimonial_new:
    path:     /new
    defaults: { _controller: "SettingContentBundle:Testimonial:new" }

testimonial_create:
    path:     /create
    defaults: { _controller: "SettingContentBundle:Testimonial:create" }
    requirements: { _method: post }

testimonial_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingContentBundle:Testimonial:edit" }

testimonial_update:
    path:     /{id}/update
    defaults: { _controller: "SettingContentBundle:Testimonial:update" }
    requirements: { _method: post|put }

testimonial_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingContentBundle:Testimonial:delete" }


testimonial_status:
    path:     /{id}/status
    defaults: { _controller: "SettingContentBundle:Testimonial:status" }


