<?php

namespace Setting\Bundle\AppearanceBundle\Service;

use Doctrine\ORM\EntityManager;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Doctrine\ORM\EntityRepository;
use Doctrine\DBAL\Connection;


use Setting\Bundle\AppearanceBundle\Entity\ModuleSetup;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * RequestManager
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ModuleManager

{

    /**
     * @var EntityManager
     */
    protected  $em;
    /**
     * @var \Doctrine\Bundle\DoctrineBundle\Registry
     */
    private $doctrine;

    public function  __construct(Registry $doctrine)
    {
        $this->doctrine = $doctrine;
        $this->em = $doctrine->getManager();
    }



    public  function setupModule($user)
    {

        $entity = new ModuleSetup();
        if($user){

            $entity->setUser($user);
            $this->em->persist($entity);
            $this->em->flush();
        }

    }

}
