accountbank:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountBank:index" }

accountbank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountBank:show" }

accountbank_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountBank:new" }

accountbank_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountBank:create" }
    methods:  POST

accountbank_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountBank:edit" }

accountbank_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountBank:update" }
    methods:  [POST, PUT]

accountbank_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountBank:approve" }
    options:
           expose: true

accountbank_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountBank:inlineUpdate" }


accountbank_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountBank:delete" }
    options:
           expose: true
