account_sales:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountSales:index" }

account_sales_outstanding:
    path:     /customer-outstanding
    defaults: { _controller: "AccountingBundle:AccountSales:customerOutstanding" }

account_sales_customer_summary:
    path:     /customer-summary
    defaults: { _controller: "AccountingBundle:AccountSales:customerSummary" }

account_sales_user_summary:
    path:     /user-outstanding
    defaults: { _controller: "AccountingBundle:AccountSales:userSummary" }

account_sales_return:
    path:     /return
    defaults: { _controller: "AccountingBundle:AccountSales:salesReturn" }

account_sales_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountSales:new" }

account_sales_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountSales:create" }
    methods:  POST

account_sales_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountSales:edit" }

account_sales_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountSales:salesReverse" }

account_sales_due:
    path:     /{sales}/due-payment
    defaults: { _controller: "AccountingBundle:AccountSales:duePayment" }

account_sales_print:
    path:     /{id}/print-payment
    defaults: { _controller: "AccountingBundle:AccountSales:print" }

account_sales_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountSales:update" }
    methods:  [POST, PUT]

account_sales_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountSales:approve" }
    options:
           expose: true

account_sales_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountSales:inlineUpdate" }

account_sales_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountSales:delete" }
    options:
           expose: true

business_receive_print:
    path:     /{id}/sales-receive-print
    defaults: { _controller: "AccountingBundle:AccountSales:salesPrint" }

business_payment_print:
    path:     /{id}/sales-payment-print
    defaults: { _controller: "AccountingBundle:AccountSales:purchasePrint" }