account_onlineorder:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:index" }

account_onlineorder_return:
    path:     /return
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:salesReturn" }

account_onlineorder_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:show" }

account_onlineorder_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:new" }

account_onlineorder_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:create" }
    methods:  POST

account_onlineorder_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:edit" }

account_onlineorder_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:update" }
    methods:  [POST, PUT]

account_onlineorder_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:approve" }
    options:
           expose: true

account_onlineorder_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:inlineUpdate" }

account_onlineorder_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountOnlineOrder:delete" }
    options:
           expose: true
