account_loan:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountLoan:index" }

account_loan_outstanding:
    path:     /loan-outstanding
    defaults: { _controller: "AccountingBundle:AccountLoan:loanOutstanding" }

account_loan_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountLoan:new" }

account_loan_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountLoan:create" }
    methods:  POST

account_loan_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountLoan:loanReverse" }

account_loan_print:
    path:     /{id}/print-payment
    defaults: { _controller: "AccountingBundle:AccountLoan:print" }

account_loan_approve:
    path:     /{id}/loan-approve
    defaults: { _controller: "AccountingBundle:AccountLoan:approve" }
    options:
           expose: true

account_loan_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountLoan:inlineUpdate" }

account_loan_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountLoan:delete" }
    options:
           expose: true


account_loanuser:
    path:     /user
    defaults: { _controller: "AccountingBundle:AccountLoanUser:index" }

account_loanuser_new:
    path:     /user-new
    defaults: { _controller: "AccountingBundle:AccountLoanUser:new" }

account_loanuser_create:
    path:     /user-create
    defaults: { _controller: "AccountingBundle:AccountLoanUser:create" }
    methods:  POST

account_loanuser_edit:
    path:     /{id}/user-edit
    defaults: { _controller: "AccountingBundle:AccountLoanUser:edit" }

account_loanuser_delete:
    path:     /{id}/user-delete
    defaults: { _controller: "AccountingBundle:AccountLoanUser:deleteUser" }

account_loanuser_update:
    path:     /{id}/user-update
    defaults: { _controller: "AccountingBundle:AccountLoanUser:update" }
    methods:  [POST, PUT]
