account_sales_business:
    path:     /sales
    defaults: { _controller: "AccountingBundle:AccountBusiness:sales" }

account_business_balancesheet:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:BusinessReport:balanceSheet" }

account_business_income:
    path:     /income
    defaults: { _controller: "AccountingBundle:BusinessReport:income" }

account_business_income_monthly:
    path:     /income-monthly
    defaults: { _controller: "AccountingBundle:BusinessReport:monthlyIncome" }

account_sales_business_new:
    path:     /sales-receive
    defaults: { _controller: "AccountingBundle:AccountBusiness:salesNew" }

account_sales_business_due:
    path:     /{sales}/sales-receive
    defaults: { _controller: "AccountingBundle:AccountBusiness:duePayment" }

account_sales_business_create:
    path:     /sales-receive-create
    defaults: { _controller: "AccountingBundle:AccountBusiness:salesCreate" }

account_sales_business_update:
    path:     /{id}/sales-receive-update
    defaults: { _controller: "AccountingBundle:AccountBusiness:duePaymentUpdate" }

account_purchase_business:
    path:     /purchase
    defaults: { _controller: "AccountingBundle:AccountBusiness:purchase" }

account_purchase_business_new:
    path:     /purchase-new
    defaults: { _controller: "AccountingBundle:AccountBusiness:purchaseNew" }

account_purchase_business_reverse:
    path:     /purchase-reverse
    defaults: { _controller: "AccountingBundle:AccountBusiness:purchaseReverse" }

account_purchase_business_create:
    path:     /purchase-create
    defaults: { _controller: "AccountingBundle:AccountBusiness:purchaseCreate" }

account_sales_business_approve:
    path:     /{id}/business-payment-approve
    defaults: { _controller: "AccountingBundle:AccountBusiness:salesApprove" }
    options:
           expose: true