account_purchase:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountPurchase:index" }

account_purchase_outstanding:
    path:     /vendor-outstanding
    defaults: { _controller: "AccountingBundle:AccountPurchase:vendorOutstanding" }

account_purchase_return:
    path:     /purchase-return
    defaults: { _controller: "AccountingBundle:AccountPurchase:purchaseReturn" }

account_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountPurchase:show" }

account_purchase_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountPurchase:new" }

account_purchase_payment:
    path:     /payment
    defaults: { _controller: "AccountingBundle:Purchase:payment" }

account_purchase_payment_create:
    path:     /payment-create
    defaults: { _controller: "AccountingBundle:Purchase:paymentCreate" }
    methods:  POST

account_purchase_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountPurchase:create" }
    methods:  POST

account_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountPurchase:edit" }

account_purchase_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountPurchase:purchaseReverse" }


account_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountPurchase:update" }
    methods:  [POST, PUT]

account_purchase_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountPurchase:approve" }
    options:
           expose: true

account_purchase_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountPurchase:inlineUpdate" }


account_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountPurchase:delete" }
    options:
           expose: true

account_purchase_vendor_search:
    path:     /search
    defaults: { _controller: "AccountingBundle:AccountPurchase:autoSearch" }
    options:
            expose: true

account_purchase_vendor_name:
    path:      /{vendor}/vendor-name
    defaults: { _controller: "AccountingBundle:AccountPurchase:searchVendorName" }
    options:
            expose: true


