report_balance:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:Report:balance" }

report_balance_pdf:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:Report:balance" }

report_income:
    path:     /income
    defaults: { _controller: "AccountingBundle:Report:income" }

report_income_hospital:
    path:     /hms-income
    defaults: { _controller: "AccountingBundle:Report:hmsIncome" }

report_monthly_income:
    path:     /monthly-income
    defaults: { _controller: "AccountingBundle:Report:monthlyIncome" }

report_monthly_income_pdf:
    path:     /monthly-income-pdf
    defaults: { _controller: "AccountingBundle:Report:monthlyIncomePdf" }

report_income_pdf:
    path:     /income-pdf
    defaults: { _controller: "AccountingBundle:Report:pdfIncome" }

report_income_print:
    path:     /income-print
    defaults: { _controller: "AccountingBundle:Report:printIncome" }

account_bank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountBank:show" }

report_journal_user_summary:
    path:     /journal-user-base-dabit-credit
    defaults: { _controller: "AccountingBundle:Report:monthlyIncome" }

report_journal_account_head_summary:
    path:     /income-pdf
    defaults: { _controller: "AccountingBundle:Report:pdfIncome" }

report_journal_transaction_summary:
    path:     /income-print
    defaults: { _controller: "AccountingBundle:Report:printIncome" }

report_expenditure_summary:
    path:     /expenditure-account-head-summary
    defaults: { _controller: "AccountingBundle:Report:expenditureSummary" }

report_expenditure_category:
    path:     /expenditure-category
    defaults: { _controller: "AccountingBundle:Report:expenditureCategory" }

report_expenditure_details:
    path:     /expenditure
    defaults: { _controller: "AccountingBundle:Report:expenditureDetails" }

report_purchase_expenditure_summary:
    path:     /expenditure-purchase-head-summary
    defaults: { _controller: "AccountingBundle:Report:expenditurePurchaseSummary" }

report_purchase_expenditure_head:
    path:     /expenditure-purchase-head
    defaults: { _controller: "AccountingBundle:Report:expenditurePurchaseHead" }

report_purchase_expenditure_details:
    path:     /expenditure-purchase
    defaults: { _controller: "AccountingBundle:Report:expenditurePurchaseDetails" }

report_sales_board:
    path:     /sales-board
    defaults: { _controller: "AccountingBundle:Report:salesBoard" }

report_sales_customer_summary:
    path:     /customer-summary
    defaults: { _controller: "AccountingBundle:Report:customerSales" }

report_sales_user_summary:
    path:     /user-outstanding
    defaults: { _controller: "AccountingBundle:Report:userSummary" }

report_sales_customer_sms:
    path:     /{id}/customer-sms
    defaults: { _controller: "AccountingBundle:Report:customerOutstandingSms" }
