accounthead:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountHead:index" }

accounthead_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountHead:show" }

accounthead_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountHead:new" }

accounthead_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountHead:create" }
    methods:  POST

accounthead_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountHead:edit" }

accounthead_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountHead:update" }
    methods:  [POST, PUT]

accounthead_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountHead:delete" }
    methods:  [POST, DELETE]

accounthead_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountHead:inlineUpdate" }

account_sub_account_select:
    path:     /{id}/sub-account-select
    defaults: { _controller: "AccountingBundle:AccountHead:subAccountSelect" }
    options:
            expose: true

accounthead_parent_select:
    path:     /parent-select
    defaults: { _controller: "AccountingBundle:AccountHead:parentSelect" }

