accountmobilebank:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountMobileBank:index" }

accountmobilebank_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountMobileBank:show" }

accountmobilebank_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountMobileBank:new" }

accountmobilebank_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountMobileBank:create" }
    methods:  POST

accountmobilebank_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountMobileBank:edit" }

accountmobilebank_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountMobileBank:update" }
    methods:  [POST, PUT]

accountmobilebank_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountMobileBank:approve" }
    options:
           expose: true

accountmobilebank_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountMobileBank:inlineUpdate" }


accountmobilebank_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountMobileBank:delete" }
    options:
           expose: true
