account_sales_hotel:
    path:     /sales
    defaults: { _controller: "AccountingBundle:AccountHotel:sales" }

account_hotel_income:
    path:     /income
    defaults: { _controller: "AccountingBundle:HotelReport:income" }

account_hotel_income_monthly:
    path:     /income-monthly
    defaults: { _controller: "AccountingBundle:HotelReport:monthlyIncome" }

account_sales_hotel_new:
    path:     /sales-receive
    defaults: { _controller: "AccountingBundle:AccountHotel:salesNew" }

account_sales_hotel_due:
    path:     /{sales}/sales-receive
    defaults: { _controller: "AccountingBundle:AccountHotel:duePayment" }

account_sales_hotel_create:
    path:     /sales-receive-create
    defaults: { _controller: "AccountingBundle:AccountHotel:salesCreate" }

account_sales_hotel_update:
    path:     /{id}/sales-receive-update
    defaults: { _controller: "AccountingBundle:AccountHotel:duePaymentUpdate" }

account_purchase_hotel:
    path:     /purchase
    defaults: { _controller: "AccountingBundle:AccountHotel:purchase" }

account_purchase_hotel_outstanding:
    path:     /vendor-outstanding
    defaults: { _controller: "AccountingBundle:AccountHotel:vendorOutstanding" }

account_sales_hotel_outstanding:
    path:     /customer-outstanding
    defaults: { _controller: "AccountingBundle:AccountHotel:customerOutstanding" }

account_sales_hotel_ledger:
    path:     /customer-ledger
    defaults: { _controller: "AccountingBundle:AccountHotel:customerLedger" }

account_purchase_hotel_new:
    path:     /purchase-new
    defaults: { _controller: "AccountingBundle:AccountHotel:purchaseNew" }

account_purchase_hotel_reverse:
    path:     /purchase-reverse
    defaults: { _controller: "AccountingBundle:AccountHotel:purchaseReverse" }

account_purchase_hotel_create:
    path:     /purchase-create
    defaults: { _controller: "AccountingBundle:AccountHotel:purchaseCreate" }

account_sales_hotel_approve:
    path:     /{id}/business-payment-approve
    defaults: { _controller: "AccountingBundle:AccountHotel:salesApprove" }
    options:
           expose: true