account_sales_medicine:
    path:     /sales
    defaults: { _controller: "AccountingBundle:AccountMedicine:sales" }

account_medicine_income:
    path:     /medicine-income
    defaults: { _controller: "AccountingBundle:MedicineReport:income" }

account_medicine_income_monthly:
    path:     /medicine-income-monthly
    defaults: { _controller: "AccountingBundle:MedicineReport:monthlyIncome" }

account_sales_medicine_new:
    path:     /sales-receive
    defaults: { _controller: "AccountingBundle:AccountMedicine:salesNew" }

account_sales_medicine_due:
    path:     /{sales}/sales-receive
    defaults: { _controller: "AccountingBundle:AccountMedicine:duePayment" }

account_sales_medicine_create:
    path:     /sales-receive-create
    defaults: { _controller: "AccountingBundle:AccountMedicine:salesCreate" }

account_sales_medicine_update:
    path:     /{id}/sales-receive-update
    defaults: { _controller: "AccountingBundle:AccountMedicine:duePaymentUpdate" }

account_purchase_medicine:
    path:     /purchase
    defaults: { _controller: "AccountingBundle:AccountMedicine:purchase" }

account_purchase_medicine_outstanding:
    path:     /vendor-outstanding
    defaults: { _controller: "AccountingBundle:AccountMedicine:vendorOutstanding" }

account_sales_medicine_outstanding:
    path:     /customer-outstanding
    defaults: { _controller: "AccountingBundle:AccountMedicine:customerOutstanding" }

account_purchase_medicine_new:
    path:     /purchase-new
    defaults: { _controller: "AccountingBundle:AccountMedicine:purchaseNew" }

account_purchase_medicine_create:
    path:     /purchase-create
    defaults: { _controller: "AccountingBundle:AccountMedicine:purchaseCreate" }


account_sales_medicine_approve:
    path:     /{id}/medicine-payment-approve
    defaults: { _controller: "AccountingBundle:AccountMedicine:salesApprove" }
    options:
           expose: true

account_sales_medicine_reverse:
    path:     /{id}/sales-reverse
    defaults: { _controller: "AccountingBundle:AccountMedicine:salesMedicineReverse" }


account_purchase_medicine_reverse:
    path:     /{id}/purchase-reverse
    defaults: { _controller: "AccountingBundle:AccountMedicine:purchaseMedicineReverse" }