account_salesadjustment:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:index" }

account_salesadjustment_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:new" }

account_salesadjustment_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:create" }
    methods:  POST

account_salesadjustment_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:reverse" }

account_salesadjustment_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:approve" }
    options:
           expose: true

account_salesadjustment_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:inlineUpdate" }

account_salesadjustment_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountSalesAdjustment:delete" }
    options:
           expose: true


