account_voucher:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountVoucher:index" }

account_voucher_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountVoucher:new" }

account_voucher_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountVoucher:edit" }

account_voucher_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountVoucher:show" }

account_voucher_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountVoucher:update" }
    methods:  [POST, PUT]

account_voucher_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "AccountingBundle:AccountVoucher:addParticular" }
    methods:  POST
    options:
            expose: true

account_voucher_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:AccountVoucher:status" }

account_voucher_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountVoucher:delete" }


account_voucher_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "AccountingBundle:AccountVoucher:approved" }

account_voucher_item_approve:
    path:     /{id}/item-approve
    defaults: { _controller: "AccountingBundle:AccountVoucher:itemApprove" }

account_voucher_particular_delete:
    path:     /{invoice}/{id}/item-delete
    defaults: { _controller: "AccountingBundle:AccountVoucher:invoiceParticularDelete" }

