account_user:
    path:     /
    defaults: { _controller: "AccountingBundle:User:index" }


account_user_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:User:show" }

account_user_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:User:new" }

account_user_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:User:create" }
    methods:  POST

account_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:User:edit" }

account_user_user_mode:
    path:     /{id}/change-user-mode
    defaults: { _controller: "AccountingBundle:User:changeUserMode" }

account_user_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:User:update" }
    methods:  [POST, PUT]

account_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:User:delete" }
    options:
           expose: true

