account_sales_restaurant:
    path:     /sales
    defaults: { _controller: "AccountingBundle:AccountRestaurant:sales" }

account_purchase_restaurant:
    path:     /purchase
    defaults: { _controller: "AccountingBundle:AccountRestaurant:purchase" }

account_purchase_restaurant_new:
    path:     /purchase-new
    defaults: { _controller: "AccountingBundle:AccountRestaurant:purchaseNew" }

account_purchase_restaurant_create:
    path:     /purchase-create
    defaults: { _controller: "AccountingBundle:AccountRestaurant:purchaseCreate" }

