account_customer:
    path:     /
    defaults: { _controller: "AccountingBundle:Customer:index" }

account_customer_restore:
    path:     /customer-restore
    defaults: { _controller: "AccountingBundle:Customer:restoreCustomer" }

account_customer_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:Customer:show" }

account_customer_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:Customer:new" }

account_customer_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:Customer:create" }
    methods:  POST

account_customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:Customer:edit" }

account_customer_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:Customer:update" }
    methods:  [POST, PUT]

account_customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:Customer:delete" }
    options:
           expose: true

account_customer_search:
    path:     /customer-search
    defaults: { _controller: "AccountingBundle:Customer:autoSearch" }
    options:
            expose: true

account_customer_name:
    path:      /{customer}/customer-name
    defaults: { _controller: "AccountingBundle:Customer:searchCustomerName" }
    options:
           expose: true

account_customer_code_search:
    path:     /customer-code-search
    defaults: { _controller: "AccountingBundle:Customer:autoCodeSearch" }
    options:
            expose: true

account_customer_code:
    path:      /{customer}/customer-code
    defaults: { _controller: "AccountingBundle:Customer:searchCode" }
    options:
           expose: true

account_location_search:
    path:     /location-search
    defaults: { _controller: "AccountingBundle:Customer:autoLocationSearch" }
    options:
            expose: true

account_location_name:
    path:      /{location}/location-name
    defaults: { _controller: "AccountingBundle:Customer:searchLocationName" }
    options:
           expose: true

account_customer_auto_name_search:
    path:     /customer-auto-name-search
    defaults: { _controller: "AccountingBundle:Customer:searchAutoCompleteName" }
    options:
           expose: true

account_customer_ledger:
    path:     /customer-ledger
    defaults: { _controller: "AccountingBundle:AccountSales:getCustomerLedger" }
    options:
           expose: true

account_customer_sales_ledger:
    path:     /customer-sales-ledger
    defaults: { _controller: "AccountingBundle:AccountSales:getCustomerSalesLedger" }
    options:
           expose: true


