account_sales_hospital:
    path:     /sales
    defaults: { _controller: "AccountingBundle:AccountHospital:sales" }

account_sales_hospital_new:
    path:     /sales-new
    defaults: { _controller: "AccountingBundle:AccountHospital:purchaseNew" }

account_purchase_hospital:
    path:     /purchase
    defaults: { _controller: "AccountingBundle:AccountHospital:purchase" }

account_purchase_hospital_new:
    path:     /purchase-new
    defaults: { _controller: "AccountingBundle:AccountHospital:purchaseNew" }

account_purchase_hospital_create:
    path:     /purchase-create
    defaults: { _controller: "AccountingBundle:AccountHospital:purchaseCreate" }

