account_journal:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountJournal:index" }

account_journal_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:AccountJournal:show" }

account_journal_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountJournal:new" }

account_journal_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountJournal:create" }
    methods:  POST

account_journal_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountJournal:journalReverse" }

account_journal_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountJournal:approve" }
    options:
           expose: true

account_journal_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountJournal:inlineUpdate" }


account_journal_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountJournal:delete" }
    options:
           expose: true

account_journal_approve_delete:
    path:     /{id}/approve-delete
    defaults: { _controller: "AccountingBundle:AccountJournal:approveDelete" }
    options:
           expose: true

account_journal_pdf:
    path:     /report-pdf
    defaults: { _controller: "AccountingBundle:AccountJournal:journalPdf" }

account_journal_excel:
    path:     /report-excel
    defaults: { _controller: "AccountingBundle:AccountJournal:journalExcel" }

