account_banktransaction:
    path:     /
    defaults: { _controller: "AccountingBundle:Transaction:index" }

account_banktransaction_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:Transaction:show" }

account_banktransaction_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:transaction:new" }

