account_cashreconciliation:
    path:     /
    defaults: { _controller: "AccountingBundle:CashReconciliation:index" }

account_cashreconciliation_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:CashReconciliation:new" }

account_cashreconciliation_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:CashReconciliation:create" }
    methods:  POST

account_cashreconciliation_add:
    path:     /{id}/add
    defaults: { _controller: "AccountingBundle:CashReconciliation:add" }
    methods:  GET
    options:
           expose: true

account_cashreconciliation_meta_update:
    path:     /{id}/meta-update
    defaults: { _controller: "AccountingBundle:CashReconciliation:metaUpdate" }
    methods:  GET
    options:
           expose: true

account_cashreconciliation_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:CashReconciliation:edit" }

account_cashreconciliation_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:CashReconciliation:show" }

account_cashreconciliation_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:CashReconciliation:journalReverse" }


account_cashreconciliation_pdf:
    path:     /{id}/pdf-download
    defaults: { _controller: "AccountingBundle:CashReconciliation:reportDownload" }

account_cashreconciliation_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:CashReconciliation:delete" }
    options:
           expose: true

account_cashreconciliation_meta_delete:
    path:     /{id}/meta-delete
    defaults: { _controller: "AccountingBundle:CashReconciliation:metaDelete" }
    options:
           expose: true

account_cashreconciliation_approve_delete:
    path:     /{id}/approve-delete
    defaults: { _controller: "AccountingBundle:CashReconciliation:approveDelete" }
    options:
           expose: true
