account_condition:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountCondition:index" }

account_condition_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountCondition:new" }

account_condition_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountCondition:create" }
    methods:  POST

account_condition_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:AccountCondition:edit" }

account_condition_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:AccountCondition:update" }
    methods:  [POST, PUT]

account_condition_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountCondition:delete" }
    options:
           expose: true

account_condition_ledger:
    path:     /ledger
    defaults: { _controller: "AccountingBundle:AccountCondition:ledger" }

account_condition_ledger_new:
    path:     /ledger/new
    defaults: { _controller: "AccountingBundle:AccountCondition:ledgerNew" }

account_condition_ledger_create:
    path:     /ledger/create
    defaults: { _controller: "AccountingBundle:AccountCondition:createLedger" }
    methods:  POST

account_condition_ledger_approve:
    path:     /{id}/ledger/payment-approve
    defaults: { _controller: "AccountingBundle:AccountCondition:approve" }
    options:
        expose: true

account_condition_ledger_inline:
    path:     /ledger/inline-update
    defaults: { _controller: "AccountingBundle:AccountCondition:inlineUpdate" }

account_condition_ledger_delete:
    path:     /{id}/ledger/delete
    defaults: { _controller: "AccountingBundle:AccountCondition:deleteLedger" }
    options:
        expose: true