account_double_entry:
    path:     /
    defaults: { _controller: "AccountingBundle:DoubleEntry:index" }

account_double_entry_item:
    path:     /entry-item
    defaults: { _controller: "AccountingBundle:DoubleEntry:journalDetails" }

account_double_entry_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:DoubleEntry:show" }

account_double_entry_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:DoubleEntry:new" }

account_double_entry_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:DoubleEntry:create" }
    methods:  POST

account_double_entry_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:DoubleEntry:edit" }

account_double_entry_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:DoubleEntry:update" }

account_double_entry_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:DoubleEntry:approve" }
    options:
           expose: true

account_double_entry_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:DoubleEntry:inlineUpdate" }


account_double_entry_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:DoubleEntry:delete" }
    options:
           expose: true

account_double_entry_approve_delete:
    path:     /{id}/approve-delete
    defaults: { _controller: "AccountingBundle:DoubleEntry:approveDelete" }
    options:
           expose: true

account_double_entry_item_delete:
    path:     /{id}/entry-item-delete
    defaults: { _controller: "AccountingBundle:DoubleEntry:itemDelete" }
    options:
           expose: true

account_double_entry_pdf:
    path:     /report-pdf
    defaults: { _controller: "AccountingBundle:DoubleEntry:journalPdf" }

account_double_entry_excel:
    path:     /report-pdf
    defaults: { _controller: "AccountingBundle:DoubleEntry:journalExcel" }

account_double_entry_approve_reset:
    path:     /approve-journal-reset
    defaults: { _controller: "AccountingBundle:DoubleEntry:approveJournalReset" }

