expensecategory:
    path:     /
    defaults: { _controller: "AccountingBundle:ExpenseCategory:index" }

expensecategory_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:ExpenseCategory:show" }

expensecategory_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:ExpenseCategory:new" }

expensecategory_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:ExpenseCategory:create" }
    requirements: { _method: post }

expensecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:ExpenseCategory:edit" }

expensecategory_status:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:ExpenseCategory:status" }

expensecategory_sorting:
    path:     /sorting
    defaults: { _controller: "AccountingBundle:ExpenseCategory:sorting" }

expensecategory_sorted:
    path:     /sorted
    defaults: { _controller: "AccountingBundle:ExpenseCategory:sorted" }

expensecategory_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:ExpenseCategory:update" }
    requirements: { _method: post|put }

expensecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:ExpenseCategory:delete" }
    requirements: { _method: post|delete }

expensecategory_feature:
   path:     /feature
   defaults: { _controller: "AccountingBundle:ExpenseCategory:feature" }
   requirements: { _method: post }

