account_expense_purchase:
    path:     /
    defaults: { _controller: "AccountingBundle:Purchase:index" }

account_expense_purchase_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:Purchase:new" }

account_expense_purchase_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:Purchase:edit" }

account_expense_purchase_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:Purchase:show" }

account_expense_purchase_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:Purchase:update" }
    methods:  [POST, PUT]

account_expense_purchase_particular_add:
    path:     /{invoice}/particular-add
    defaults: { _controller: "AccountingBundle:Purchase:addParticular" }
    methods:  POST
    options:
            expose: true


account_expense_purchase_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:Purchase:status" }

account_expense_purchase_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:Purchase:delete" }


account_expense_purchase_approved:
    path:     /{id}/invoice-approved
    defaults: { _controller: "AccountingBundle:Purchase:approved" }

account_expense_purchase_item_approve:
    path:     /{id}/item-approve
    defaults: { _controller: "AccountingBundle:Purchase:itemApprove" }

account_expense_purchase_particular_delete:
    path:     /{invoice}/{id}/particular-delete
    defaults: { _controller: "AccountingBundle:Purchase:invoiceParticularDelete" }

