journal_voucher:
    path:     /
    defaults: { _controller: "AccountingBundle:JournalVoucher:index" }

journal_voucher_item:
    path:     /entry-item
    defaults: { _controller: "AccountingBundle:JournalVoucher:journalDetails" }

journal_voucher_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:JournalVoucher:show" }

journal_voucher_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:JournalVoucher:new" }

journal_voucher_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:JournalVoucher:create" }
    methods:  POST

journal_voucher_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:JournalVoucher:edit" }

journal_voucher_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:JournalVoucher:update" }

journal_voucher_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:JournalVoucher:approve" }
    options:
           expose: true

journal_voucher_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:JournalVoucher:inlineUpdate" }


journal_voucher_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:JournalVoucher:delete" }
    options:
           expose: true

journal_voucher_approve_delete:
    path:     /{id}/approve-delete
    defaults: { _controller: "AccountingBundle:JournalVoucher:approveDelete" }
    options:
           expose: true

journal_voucher_item_delete:
    path:     /{id}/entry-item-delete
    defaults: { _controller: "AccountingBundle:JournalVoucher:itemDelete" }
    options:
           expose: true

journal_voucher_pdf:
    path:     /report-pdf
    defaults: { _controller: "AccountingBundle:JournalVoucher:journalPdf" }

journal_voucher_approve_reset:
    path:     /approve-journal-reset
    defaults: { _controller: "AccountingBundle:JournalVoucher:approveJournalReset" }

journal_voucher_print:
    path:     /{id}/print
    defaults: { _controller: "AccountingBundle:JournalVoucher:print" }