account_paymentsalary_employee:
    path:     /salaery-employee
    defaults: { _controller: "AccountingBundle:PaymentSalary:salaryEmployee" }

account_paymentsalary:
    path:     /
    defaults: { _controller: "AccountingBundle:PaymentSalary:index" }

account_paymentsalary_show:
    path:     /{user}/show
    defaults: { _controller: "AccountingBundle:PaymentSalary:show" }

account_paymentsalary_new:
    path:     /{user}/new
    defaults: { _controller: "AccountingBundle:PaymentSalary:new" }

account_paymentsalary_create:
    path:     /{user}/create
    defaults: { _controller: "AccountingBundle:PaymentSalary:create" }
    methods:  POST

account_paymentsalary_edit:
    path:     /{user}/edit
    defaults: { _controller: "AccountingBundle:PaymentSalary:edit" }

account_paymentsalary_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:PaymentSalary:update" }
    methods:  [POST, PUT]

account_paymentsalary_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:PaymentSalary:delete" }

account_paymentsalary_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:PaymentSalary:approve" }
    options:
           expose: true
