account_pettycash:
    path:     /
    defaults: { _controller: "AccountingBundle:PettyCash:index" }

account_pettycash_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:PettyCash:show" }

account_pettycash_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:PettyCash:new" }

account_pettycash_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:PettyCash:create" }
    methods:  POST

account_pettycash_payment_return:
    path:     /payment-return
    defaults: { _controller: "AccountingBundle:PettyCash:payment" }
    methods:  POST
    options:
           expose: true

account_pettycash_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:PettyCash:approve" }
    options:
           expose: true

account_pettycash_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:PettyCash:inlineUpdate" }


account_pettycash_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:PettyCash:delete" }
    options:
           expose: true
