account_receive_print:
    path:     /{id}/sales-receive-print
    defaults: { _controller: "AccountingBundle:AccountPrint:salesPrint" }

account_payment_print:
    path:     /{id}/sales-payment-print
    defaults: { _controller: "AccountingBundle:AccountPrint:purchasePrint" }