account_profit:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountProfit:index" }

account_profit_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountProfit:new" }

account_profit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountProfit:delete" }

account_profit_download_profit:
    path:     /profit-pdf
    defaults: { _controller: "AccountingBundle:AccountProfit:downloadProfit" }

