account_purchasecommission:
    path:     /
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:index" }

account_purchasecommission_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:new" }

account_purchasecommission_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:create" }
    methods:  POST

account_purchasecommission_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:journalReverse" }

account_purchasecommission_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:approve" }
    options:
           expose: true

account_purchasecommission_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:inlineUpdate" }

account_purchasecommission_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:delete" }
    options:
           expose: true

account_purchasecommission_approve_delete:
    path:     /{id}/approve-delete
    defaults: { _controller: "AccountingBundle:AccountPurchaseCommission:approveDelete" }
    options:
           expose: true
