account_salarysetting:
    path:     /
    defaults: { _controller: "AccountingBundle:SalarySetting:index" }

account_salarysetting_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:SalarySetting:show" }

account_salarysetting_new:
    path:     /new
    defaults: { _controller: "AccountingBundle:SalarySetting:new" }

account_salarysetting_create:
    path:     /create
    defaults: { _controller: "AccountingBundle:SalarySetting:create" }
    methods:  POST

account_salarysetting_edit:
    path:     /{id}/edit
    defaults: { _controller: "AccountingBundle:SalarySetting:edit" }

account_salarysetting_update:
    path:     /{id}/update
    defaults: { _controller: "AccountingBundle:SalarySetting:update" }
    methods:  [POST, PUT]

account_salarysetting_delete:
    path:     /{id}/delete
    defaults: { _controller: "AccountingBundle:SalarySetting:delete" }

account_salarysetting_inline:
    path:     /inline-update
    defaults: { _controller: "AccountingBundle:SalarySetting:inlineUpdate" }

account_salarysetting_approve:
    path:     /{id}/payment-approve
    defaults: { _controller: "AccountingBundle:SalarySetting:approve" }
    options:
           expose: true

account_salarysetting_status:
    path:     /{id}/status
    defaults: { _controller: "AccountingBundle:SalarySetting:status" }
    options:
           expose: true

account_salarysetting_salaryAmount:
    path:     /salary-amount
    defaults: { _controller: "AccountingBundle:SalarySetting:salaryAmount" }
    options:
           expose: true