account_transaction:
    path:     /
    defaults: { _controller: "AccountingBundle:Transaction:index" }

account_transaction_show:
    path:     /{id}/show
    defaults: { _controller: "AccountingBundle:Transaction:show" }

account_transaction_cash_overview:
    path:     /cash-overview
    defaults: { _controller: "AccountingBundle:Transaction:transactionCashOverview" }

account_transaction_cash_summary:
    path:     /cash-summary
    defaults: { _controller: "AccountingBundle:Transaction:transactionSummary" }

account_transaction_cash_overview_pdf:
    path:     /cash-overview-pdf
    defaults: { _controller: "AccountingBundle:Transaction:transactionCashOverviewPdf" }

account_transaction_accountcash:
    path:     /all-account-cash
    defaults: { _controller: "AccountingBundle:Transaction:accountCash" }

account_transaction_cash:
    path:     /hand-cash
    defaults: { _controller: "AccountingBundle:Transaction:cash" }

account_transaction_bank:
    path:     /bank-cash
    defaults: { _controller: "AccountingBundle:Transaction:bank" }

account_transaction_mobilebank:
    path:     /mobile-cash
    defaults: { _controller: "AccountingBundle:Transaction:mobileBank" }

account_transaction_purchase_expense:
    path:     /transaction-purchase-expense
    defaults: { _controller: "AccountingBundle:Transaction:purchaseExpense" }

account_transaction_monthly:
    path:     /transaction-monthly
    defaults: { _controller: "AccountingBundle:Transaction:monthly" }

account_transaction_yearly:
    path:     /transaction-yearly
    defaults: { _controller: "AccountingBundle:Transaction:yearly" }


account_transaction_journal:
    path:     /journal
    defaults: { _controller: "AccountingBundle:Transaction:transactionJournal" }

account_trail_balance:
    path:     /trail-balance
    defaults: { _controller: "AccountingBundle:Transaction:trailBalance" }

account_balance_sheet:
    path:     /balance-sheet
    defaults: { _controller: "AccountingBundle:Transaction:balanceSheet" }


