appearancefeaturewidget:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:index" }

appearancefeaturewidget_sorting:
    path:     /sorting
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:sorting" }

appearancefeaturewidget_list_sorted:
    path:     /sorted-list
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:sortedList" }

appearancefeaturewidget_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:show" }

appearancefeaturewidget_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:new" }

appearancefeaturewidget_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:create" }
    methods:  POST

appearancefeaturewidget_feature:
    path:     /{id}/feature
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:feature" }

appearancefeaturewidget_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:edit" }

appearancefeaturewidget_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:update" }
    methods:  [POST, PUT]

appearancefeaturewidget_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:delete" }

appearancefeaturewidget_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:status" }

appearancefeaturewidget_resizing:
    path:     /resizing
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:resize" }

appearancefeaturewidget_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:FeatureWidget:sorted" }
