appearancewebsitewidget:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:index" }

appearancewebsitewidget_sorting:
    path:     /sorting
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:sorting" }

appearancewebsitewidget_list_sorted:
    path:     /sorted-list
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:sortedList" }

appearancewebsitewidget_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:show" }

appearancewebsitewidget_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:new" }

appearancewebsitewidget_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:create" }
    methods:  POST

appearancewebsitewidget_feature:
    path:     /{id}/feature
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:feature" }

appearancewebsitewidget_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:edit" }

appearancewebsitewidget_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:update" }
    methods:  [POST, PUT]

appearancewebsitewidget_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:delete" }

appearancewebsitewidget_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:status" }

appearancewebsitewidget_resizing:
    path:     /resizing
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:resize" }

appearancewebsitewidget_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:WebsiteWidget:sorted" }
