appearancefeature:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:Feature:index" }

appearancefeature_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:Feature:show" }

appearancefeature_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:Feature:new" }

appearancefeature_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:Feature:create" }
    methods:  POST

appearancefeature_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:Feature:edit" }

appearancefeature_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:Feature:update" }
    methods:  [POST, PUT]

appearancefeature_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:Feature:delete" }

appearancefeature_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:Feature:status" }

appearancefeature_resizing:
    path:     /resizing
    defaults: { _controller: "SettingAppearanceBundle:Feature:resize" }

appearancefeature_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:Feature:sorted" }
