ecommercetemplate:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:Template:index" }

ecommercetemplate_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:Template:show" }

ecommercetemplate_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:Template:new" }

ecommercetemplate_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:Template:create" }
    methods:  POST

ecommercetemplate_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:Template:edit" }

ecommercetemplate_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:Template:update" }
    methods:  [POST, PUT]

ecommercetemplate_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:Template:delete" }

ecommercetemplate_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:Template:status" }

ecommercetemplate_resizing:
    path:     /resizing
    defaults: { _controller: "SettingAppearanceBundle:Template:resize" }

ecommercetemplate_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:Template:sorted" }
