ecommercemenu:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:index" }

ecommercemenu_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:new" }

ecommercemenu_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:create" }
    methods:  POST

ecommercemenu_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:edit" }

ecommercemenu_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:update" }
    methods:  [POST, PUT]

ecommercemenu_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:delete" }


ecommercemenu_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:sorted" }

ecommercemenu_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:EcommerceMenu:status" }

