featurecategory:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:index" }

featurecategory_sorting:
    path:     /sorting
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:sorting" }

featurecategory_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:show" }

featurecategory_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:new" }

featurecategory_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:create" }
    methods:  POST

featurecategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:edit" }

featurecategory_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:update" }
    methods:  [POST, PUT]

featurecategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:delete" }

featurecategory_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:FeatureCategory:status" }
