featurebrand:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:index" }

featurebrand_sorting:
    path:     /sorting
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:sorting" }

featurebrand_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:show" }

featurebrand_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:new" }

featurebrand_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:create" }
    methods:  POST

featurebrand_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:edit" }

featurebrand_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:update" }
    methods:  [POST, PUT]

featurebrand_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:delete" }

featurebrand_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:FeatureBrand:status" }
