megamenu:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:index" }

megamenu_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:show" }

megamenu_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:new" }

megamenu_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:create" }
    methods:  POST

megamenu_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:edit" }

megamenu_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:update" }
    methods:  [POST, PUT]

megamenu_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:delete" }


megamenu_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:sorted" }

megamenu_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:MegaMenu:status" }

