menugroup:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:index" }

menugroup_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:show" }

menugroup_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:new" }

menugroup_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:create" }
    requirements: { _method: post }

menugroup_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:edit" }

menugroup_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:update" }
    requirements: { _method: post|put }

menugroup_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:delete" }
    requirements: { _method: post|delete }

menugroup_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:MenuGroup:status" }


