menucustom:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:index" }

menucustom_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:show" }

menucustom_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:new" }

menucustom_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:create" }
    methods:  POST

menucustom_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:edit" }

menucustom_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:update" }
    methods:  [POST, PUT]

menucustom_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:delete" }
    methods:  [POST, DELETE]

menucustom_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:MenuCustom:status" }