menu:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:Menu:menuManage" }

menu_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:Menu:update" }
    requirements: { _method: post|put }

menu_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:Menu:new" }

menu_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:Menu:create" }
    methods:  POST

menu_manage:
    path:     /manage
    defaults: { _controller: "SettingAppearanceBundle:Menu:menuManage" }

menu_modify:
    path:     /modify
    defaults: { _controller: "SettingAppearanceBundle:Menu:modify" }

menu_stopMenu:
    path:     /{id}/stopMenu
    defaults: { _controller: "SettingAppearanceBundle:Menu:stopMenu" }

menu_status:
    path:     /{globalOption}/{id}/status
    defaults: { _controller: "SettingAppearanceBundle:Menu:status" }


menu_reset:
    path:     /reset-default-menu
    defaults: { _controller: "SettingAppearanceBundle:Menu:resetMenu" }


