menugrouping:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:index" }

menugrouping_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:show" }

menugrouping_new:
    path:     /new/{id}/
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:new" }

menugrouping_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:create" }
    requirements: { _method: post }

menugrouping_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:edit" }

menugrouping_sorting:
    path:     /{menuGroup}/sorting
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:sorting" }

menugrouping_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:update" }
    requirements: { _method: post|put }

menugrouping_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:sorted" }
    requirements: { _method: post|put }

menugrouping_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:MenuGrouping:delete" }
    requirements: { _method: post|delete }
