sidebarwidget:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:index" }

sidebarwidget_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:new" }

sidebarwidget_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:create" }
    methods:  POST

sidebarwidget_edit:
    path:     /{id}/edit
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:edit" }

sidebarwidget_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:update" }
    methods:  [POST, PUT]

sidebarwidget_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:delete" }

sidebarwidget_status:
    path:     /{id}/status
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:status" }

sidebarwidget_sorted:
    path:     /sorted
    defaults: { _controller: "SettingAppearanceBundle:SidebarWidget:sorted" }
