templatecustomize:
    path:     /
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:index" }

templatecustomize_show:
    path:     /{id}/show
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:show" }

templatecustomize_new:
    path:     /new
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:new" }

templatecustomize_create:
    path:     /create
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:create" }
    methods:  POST

templatecustomize_edit:
    path:     /edit
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:edit" }

templatecustomize_ecommerce_edit:
    path:     /ecommerce-edit
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:ecommerceEdit" }

templatecustomize_reset:
    path:     /{id}/reset
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:reset" }

templatecustomize_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:update" }
    methods:  [POST, PUT]

templatecustomize_ecommerce_update:
    path:     /{id}/update
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:ecommerceUpdate" }
    methods:  [POST, PUT]

templatecustomize_delete:
    path:     /{id}/delete
    defaults: { _controller: "SettingAppearanceBundle:TemplateCustomize:delete" }
    methods:  [POST, DELETE]
