agentpayment:
    path:     /
    defaults: { _controller: "DomainUserBundle:AgentPayment:index" }

agentpayment_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:AgentPayment:show" }

agentpayment_invoice:
    path:     /invoice
    defaults: { _controller: "DomainUserBundle:AgentPayment:new" }

agentpayment_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:AgentPayment:create" }
    methods:  POST

agentpayment_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:AgentPayment:edit" }

agentpayment_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:AgentPayment:update" }
    methods:  [POST, PUT]

agentpayment_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:AgentPayment:delete" }
    methods:  [POST, DELETE]
