agent:
    path:     /
    defaults: { _controller: "DomainUserBundle:Agent:index" }

agent_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Agent:show" }

agent_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Agent:new" }

agent_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Agent:create" }
    methods:  POST

agent_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Agent:edit" }

agent_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Agent:update" }
    methods:  [POST, PUT]

agent_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Agent:delete" }
    methods:  [POST, DELETE]

agent_search:
    path:     /customer-search
    defaults: { _controller: "DomainUserBundle:Agent:autoSearch" }
    options:
            expose: true

agent_name:
    path:      /{customer}/customer-name
    defaults: { _controller: "DomainUserBundle:Agent:searchCustomerName" }
    options:
           expose: true

domain_location_search:
    path:     /location-search
    defaults: { _controller: "DomainUserBundle:Agent:autoLocationSearch" }
    options:
            expose: true

domain_location_name:
    path:      /{location}/location-name
    defaults: { _controller: "DomainUserBundle:Agent:searchLocationName" }
    options:
           expose: true