domain_association:
    path:     /member
    defaults: { _controller: "DomainUserBundle:Association:index" }

domain_association_member_show:
    path:     /{id}/association-member-show
    defaults: { _controller: "DomainUserBundle:Association:memberShow" }

domain_association_sms:
    path:     /sms
    defaults: { _controller: "DomainUserBundle:Association:index" }

domain_association_process:
    path:     /{id}/process
    defaults: { _controller: "DomainUserBundle:Association:process" }

domain_association_group_sms:
    path:     /group-sms
    defaults: { _controller: "DomainUserBundle:Association:groupSms" }

domain_association_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Association:show" }

domain_association_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Association:new" }

domain_association_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Association:create" }
    methods:  POST

domain_association_profile_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Association:edit" }

domain_association_profile_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Association:update" }
    methods:  [POST, PUT]

domain_association_profile_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Association:delete" }
    options:
           expose: true

domain_association_search:
    path:     /association-search
    defaults: { _controller: "DomainUserBundle:Association:autoSearch" }
    options:
            expose: true

domain_association_batch_select:
    path:     /association-batch-select
    defaults: { _controller: "DomainUserBundle:Association:batchSelect" }
    options:
            expose: true

domain_association_blood_select:
    path:     /association-blood-select
    defaults: { _controller: "DomainUserBundle:Association:bloodSelect" }
    options:
            expose: true

domain_association_inline_update:
    path:     /association-member-inline-update
    defaults: { _controller: "DomainUserBundle:Association:inlineUpdate" }
    options:
            expose: true

domain_association_name:
    path:      /{association}/association-name
    defaults: { _controller: "DomainUserBundle:Association:searchAssociationName" }
    options:
           expose: true

domain_association_code_search:
    path:     /association-code-search
    defaults: { _controller: "DomainUserBundle:Association:autoCodeSearch" }
    options:
            expose: true

domain_association_code:
    path:      /{association}/Association-code
    defaults: { _controller: "DomainUserBundle:Association:searchCode" }
    options:
           expose: true

domain_location_search:
    path:     /location-search
    defaults: { _controller: "DomainUserBundle:Association:autoLocationSearch" }
    options:
            expose: true

domain_location_name:
    path:      /{location}/location-name
    defaults: { _controller: "DomainUserBundle:Association:searchLocationName" }
    options:
           expose: true

domain_association_auto_name_search:
    path:     /association-auto-name-search
    defaults: { _controller: "DomainUserBundle:Association:searchAutoCompleteName" }
    options:
           expose: true

domain_association_ledger:
    path:     /association-ledger
    defaults: { _controller: "AccountingBundle:AccountSales:associationLedger" }
    options:
           expose: true

domain_association_invoice:
       path:     /invoice
       defaults: { _controller: "DomainUserBundle:Association:invoice" }

domain_association_invoice_new:
       path:     /{customer}/invoice-new
       defaults: { _controller: "DomainUserBundle:Association:invoiceNew" }

domain_association_invoice_create:
       path:     /{customer}/invoice-create
       defaults: { _controller: "DomainUserBundle:Association:invoiceCreate" }
       methods:  [POST]

domain_association_invoice_show:
    path:     /{id}/invoice-show
    defaults: { _controller: "DomainUserBundle:Association:invoiceShow" }

domain_association_invoice_edit:
    path:     /{id}/invoice-edit
    defaults: { _controller: "DomainUserBundle:Association:invoiceEdit" }


domain_association_invoice_update:
       path:     /{id}/invoice-update
       defaults: { _controller: "DomainUserBundle:Association:invoiceUpdate" }
       methods:  [POST,PUT]


domain_association_invoice_print:
    path:     /{id}/invoice-print
    defaults: { _controller: "DomainUserBundle:Association:invoicePrint" }




