domain_branches:
    path:     /
    defaults: { _controller: "DomainUserBundle:Branches:index" }

domain_branches_employee:
    path:     /{id}/branches-employee
    defaults: { _controller: "DomainUserBundle:Branches:branchesEmployee" }

domain_branches_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Branches:show" }

domain_branches_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Branches:new" }

domain_branches_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Branches:create" }
    methods:  POST

domain_branches_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Branches:edit" }

domain_branches_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Branches:update" }
    methods:  [POST, PUT]

domain_branches_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Branches:delete" }

domain_branches_search:
    path:     /search
    defaults: { _controller: "DomainUserBundle:Branches:autoSearch" }
    options:
            expose: true

domain_branches_name:
    path:      /{branch}/branch-name
    defaults: { _controller: "DomainUserBundle:Branches:searchBranchName" }
    options:
            expose: true

