restaurant_customer:
    path:     /
    defaults: { _controller: "DomainUserBundle:CustomerInventory:index" }

restaurant_customer_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:CustomerInventory:show" }

restaurant_customer_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:CustomerInventory:new" }

restaurant_customer_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:CustomerInventory:create" }
    methods:  POST

restaurant_customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:CustomerInventory:edit" }

restaurant_customer_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:CustomerInventory:update" }
    methods:  [POST, PUT]

restaurant_customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:CustomerInventory:delete" }
    methods:  [POST, DELETE]
