domain_customer:
    path:     /
    defaults: { _controller: "DomainUserBundle:Customer:index" }

domain_association_member:
    path:     /association-member
    defaults: { _controller: "DomainUserBundle:Customer:member" }

domain_association_member_show:
    path:     /{id}/association-member-show
    defaults: { _controller: "DomainUserBundle:Customer:memberShow" }

domain_customer_sms:
    path:     /sms
    defaults: { _controller: "DomainUserBundle:Customer:index" }

domain_customer_email:
    path:     /email
    defaults: { _controller: "DomainUserBundle:Customer:index" }

domain_customer_online:
    path:     /online
    defaults: { _controller: "DomainUserBundle:Customer:index" }

domain_customer_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Customer:show" }

domain_customer_rehab_show:
    path:     /{id}/rehab-show
    defaults: { _controller: "DomainUserBundle:Customer:rehab" }

domain_customer_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Customer:new" }

domain_customer_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Customer:create" }
    methods:  POST

domain_customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Customer:edit" }

domain_customer_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Customer:update" }
    methods:  [POST, PUT]

domain_customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Customer:delete" }
    options:
           expose: true

domain_customer_search:
    path:     /customer-search
    defaults: { _controller: "DomainUserBundle:Customer:autoSearch" }
    options:
            expose: true

domain_patient_search:
    path:     /patient-search
    defaults: { _controller: "DomainUserBundle:Customer:patientSearch" }
    options:
            expose: true

domain_patient_information:
    path:     /{id}/patient-information
    defaults: { _controller: "DomainUserBundle:Customer:patientInfo" }
    options:
        expose: true

domain_customer_name:
    path:      /{customer}/customer-name
    defaults: { _controller: "DomainUserBundle:Customer:searchCustomerName" }
    options:
           expose: true

domain_customer_code_search:
    path:     /customer-code-search
    defaults: { _controller: "DomainUserBundle:Customer:autoCodeSearch" }
    options:
            expose: true

domain_customer_code:
    path:      /{customer}/customer-code
    defaults: { _controller: "DomainUserBundle:Customer:searchCode" }
    options:
           expose: true

domain_location_search:
    path:     /location-search
    defaults: { _controller: "DomainUserBundle:Customer:autoLocationSearch" }
    options:
            expose: true

domain_location_name:
    path:      /{location}/location-name
    defaults: { _controller: "DomainUserBundle:Customer:searchLocationName" }
    options:
           expose: true

domain_customer_auto_name_search:
    path:     /customer-auto-name-search
    defaults: { _controller: "DomainUserBundle:Customer:searchAutoCompleteName" }
    options:
           expose: true

domain_customer_ledger:
    path:     /customer-ledger
    defaults: { _controller: "AccountingBundle:AccountSales:getCustomerLedger" }
    options:
           expose: true

domain_customer_sales_ledger:
    path:     /customer-sales-ledger
    defaults: { _controller: "AccountingBundle:AccountSales:getCustomerSalesLedger" }
    options:
           expose: true


