domain_user:
    path:     /
    defaults: { _controller: "DomainUserBundle:DomainUser:index" }

domain_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:DomainUser:show" }

domain_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:DomainUser:new" }

domain_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:DomainUser:create" }
    methods:  POST

domain_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:DomainUser:edit" }

domain_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:DomainUser:update" }
    methods:  [POST, PUT]

domain_update_profile:
    path:     /update-profile
    defaults: { _controller: "DomainUserBundle:DomainUser:updateProfile" }
    methods:  [POST, PUT]

domain_change_password:
    path:     /change-password
    defaults: { _controller: "UserBundle:ChangePassword:changePassword" }

domain_forget_password:
    path:     /{id}/forget-user-password
    defaults: { _controller: "DomainUserBundle:DomainUser:forgetPassword" }

domain_reset_password:
    path:     /{id}/reset-user-password
    defaults: { _controller: "DomainUserBundle:Resetting:resetForgetPassword" }
    methods:  [POST, PUT]


domain_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:DomainUser:delete" }

domain_print:
    path:     /print
    defaults: { _controller: "DomainUserBundle:DomainUser:new" }

domain_export:
    path:     /export
    defaults: { _controller: "DomainUserBundle:DomainUser:new" }

domain_pdf:
    path:     /pdf
    defaults: { _controller: "DomainUserBundle:DomainUser:new" }

domain_import:
    path:     /import
    defaults: { _controller: "DomainUserBundle:DomainUser:new" }

domain_user_search:
    path:     /search
    defaults: { _controller: "DomainUserBundle:DomainUser:autoSearch" }
    options:
            expose: true

domain_user_profilename_search:
    path:     /search-profile-name
    defaults: { _controller: "DomainUserBundle:DomainUser:autoSearchProfileName" }
    options:
        expose: true


domain_user_name:
    path:      /{user}/user-name
    defaults: { _controller: "DomainUserBundle:DomainUser:searchUserName" }
    options:
           expose: true

domain_edit_profile:
    path:     /edit-profile
    defaults: { _controller: "DomainUserBundle:DomainUser:editProfile" }

