domain_employee_branch:
    path:     /
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:index" }

domain_employee_branch_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:show" }

domain_employee_branch_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:new" }

domain_employee_branch_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:create" }
    methods:  POST

domain_employee_branch_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:edit" }

domain_employee_branch_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:update" }
    methods:  [POST, PUT]

domain_employee_branch_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:EmployeeBranch:delete" }



