domain_gp_customer_import:
    path:     /
    defaults: { _controller: "DomainUserBundle:GpCustomerImport:index" }

domain_gp_customer_import_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:GpCustomerImport:create" }
    methods:  POST

domain_gp_customer_import_migration:
    path:     /{id}/customer-migration
    defaults: { _controller: "DomainUserBundle:GpCustomerImport:excelDataImport" }


domain_gp_customer_import_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:GpCustomerImport:delete" }


