hms_customer:
    path:     /
    defaults: { _controller: "DomainUserBundle:CustomerHms:index" }

hms_customer_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:CustomerHms:show" }

hms_customer_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:CustomerHms:new" }

hms_customer_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:CustomerHms:create" }
    methods:  POST

hms_customer_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:CustomerHms:edit" }

hms_customer_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:CustomerHms:update" }
    methods:  [POST, PUT]

hms_customer_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:CustomerHms:delete" }

hms_customer_details:
    path:     /{mobile}/patient-details
    defaults: { _controller: "DomainUserBundle:CustomerHms:details" }