domain_notepad:
    path:     /
    defaults: { _controller: "DomainUserBundle:Notepad:index" }

domain_notepad_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Notepad:show" }

domain_notepad_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Notepad:new" }

domain_notepad_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Notepad:create" }
    methods:  POST

domain_notepad_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Notepad:edit" }

domain_notepad_insert:
    path:     /{id}/insert
    defaults: { _controller: "DomainUserBundle:Notepad:insert" }
    options:
            expose: true

domain_notepad_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Notepad:update" }
    methods:  [POST, PUT]

domain_notepad_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Notepad:delete" }

