domain_notificationconfig:
    path:     /
    defaults: { _controller: "DomainUserBundle:NotificationConfig:index" }

domain_notificationconfig_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:NotificationConfig:update" }
    methods:  [POST, PUT]




