domainuser_sms:
    path:     /
    defaults: { _controller: "DomainUserBundle:CustomerSms:index" }

domainuser_member_sms:
    path:     /{id}/member
    defaults: { _controller: "DomainUserBundle:CustomerSms:member" }

domainuser_event_sms:
    path:     /{id}/event
    defaults: { _controller: "DomainUserBundle:CustomerSms:event" }

domainuser_committee_sms:
    path:     /{id}/committee
    defaults: { _controller: "DomainUserBundle:CustomerSms:committee" }

domainuser_votecenter_sms:
    path:     /{id}/vote-center
    defaults: { _controller: "DomainUserBundle:CustomerSms:voteCenter" }

domainuser_sms_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:CustomerSms:new" }

domainuser_sms_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:CustomerSms:show" }
    options:
            expose: true

domainuser_sms_search:
    path:     /search
    defaults: { _controller: "DomainUserBundle:CustomerSms:autoSearch" }
    options:
            expose: true

domainuser_sms_name:
    path:      /{particular}/particular-name
    defaults: { _controller: "DomainUserBundle:CustomerSms:searchSmsName" }
    options:
            expose: true

domainuser_sms_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:CustomerSms:create" }
    methods:  POST

domainuser_sms_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:CustomerSms:edit" }

domainuser_sms_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:CustomerSms:update" }
    methods:  [POST, PUT]

domainuser_sms_status:
    path:     /{id}/status
    defaults: { _controller: "DomainUserBundle:CustomerSms:status" }

domainuser_sms_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:CustomerSms:delete" }

domainuser_bulk_sms:
    path:     /{id}/bluk
    defaults: { _controller: "DomainUserBundle:CustomerSms:bulkSms" }


