domain_store:
    path:     /
    defaults: { _controller: "DomainUserBundle:Store:index" }

domain_store_employee:
    path:     /{id}/branches-employee
    defaults: { _controller: "DomainUserBundle:Branches:branchesEmployee" }

domain_store_show:
    path:     /{id}/show
    defaults: { _controller: "DomainUserBundle:Branches:show" }

domain_store_new:
    path:     /new
    defaults: { _controller: "DomainUserBundle:Branches:new" }

domain_store_create:
    path:     /create
    defaults: { _controller: "DomainUserBundle:Branches:create" }
    methods:  POST

domain_store_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomainUserBundle:Branches:edit" }

domain_store_update:
    path:     /{id}/update
    defaults: { _controller: "DomainUserBundle:Branches:update" }
    methods:  [POST, PUT]

domain_store_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomainUserBundle:Branches:delete" }



