customer_domain_product:
    resource: "@CustomerBundle/Resources/config/routing/product.yml"
    prefix:   /{shop}/product


customer_domain:
    resource: "@CustomerBundle/Resources/config/routing/domain.yml"
    prefix:   /{shop}

customer_order_process:
    resource: "@CustomerBundle/Resources/config/routing/order.yml"
    prefix:   /{shop}/order

customer_order_wishlist:
    resource: "@CustomerBundle/Resources/config/routing/wishlist.yml"
    prefix:   /{shop}/wishlist

customer_order_inbox:
    resource: "@CustomerBundle/Resources/config/routing/inbox.yml"
    prefix:   /{shop}/inbox

customer_pre_order_process:
    resource: "@CustomerBundle/Resources/config/routing/preorder.yml"
    prefix:   /{shop}/pre-order

agent_client:
    resource: "@CustomerBundle/Resources/config/routing/agentclient.yml"
    prefix:   /agent

customer_website:
    resource: "@CustomerBundle/Resources/config/routing/customerweb.yml"
    prefix:   /{shop}/content

member_invoice:
    resource: "@CustomerBundle/Resources/config/routing/customerinvoice.yml"
    prefix:   /{shop}/invoice

member_profile:
    resource: "@CustomerBundle/Resources/config/routing/member.yml"
    prefix:   /{shop}/member

domain_business_dashboard:
   resource: "@CustomerBundle/Resources/config/routing/business.yml"
   prefix:   /{shop}/dashboard

domain_customer_homepage:
    path:     /{shop}/dashboard/
    defaults: { _controller: "CustomerBundle:Customer:index" }

domain_customer_domainpage:
    path:     /domaindas-hboard/
    defaults: { _controller: "CustomerBundle:Customer:customerDomain" }

customerweb_profile:
    path:     /{shop}/profile
    defaults: { _controller: "CustomerBundle:Profile:edit" }

customerweb_profile_update:
    path:      /{shop}/profile-update
    defaults: { _controller: "CustomerBundle:Profile:update" }
    methods:  [POST, PUT]



