categorygrouping:
    path:     /
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:index" }

categorygrouping_show:
    path:     /{id}/show
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:show" }

categorygrouping_new:
    path:     /new
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:new" }

categorygrouping_create:
    path:     /create
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:create" }
    requirements: { _method: post }

categorygrouping_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:edit" }

categorygrouping_update:
    path:     /{id}/update
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:update" }
    requirements: { _method: post|put }

categorygrouping_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductProductBundle:CategoryGrouping:delete" }
    requirements: { _method: post|delete }
