category:
    path:     /
    defaults: { _controller: "ProductProductBundle:Category:index" }

category_show:
    path:     /{id}/show
    defaults: { _controller: "ProductProductBundle:Category:show" }

category_new:
    path:     /new
    defaults: { _controller: "ProductProductBundle:Category:new" }

category_create:
    path:     /create
    defaults: { _controller: "ProductProductBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductProductBundle:Category:edit" }

category_status:
    path:     /{id}/status
    defaults: { _controller: "ProductProductBundle:Category:status" }

category_sorting:
    path:     /sorting
    defaults: { _controller: "ProductProductBundle:Category:sorting" }

category_sorted:
    path:     /sorted
    defaults: { _controller: "ProductProductBundle:Category:sorted" }

category_update:
    path:     /{id}/update
    defaults: { _controller: "ProductProductBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductProductBundle:Category:delete" }

category_feature:
   path:     /feature
   defaults: { _controller: "ProductProductBundle:Category:feature" }
   requirements: { _method: post }

