collection:
    path:     /
    defaults: { _controller: "ProductProductBundle:Collection:index" }

collection_show:
    path:     /{id}/show
    defaults: { _controller: "ProductProductBundle:Collection:show" }

collection_new:
    path:     /new
    defaults: { _controller: "ProductProductBundle:Collection:new" }

collection_create:
    path:     /create
    defaults: { _controller: "ProductProductBundle:Collection:create" }
    methods:  POST

collection_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductProductBundle:Collection:edit" }

collection_status:
    path:     /{id}/status
    defaults: { _controller: "ProductProductBundle:Collection:status" }

collection_update:
    path:     /{id}/update
    defaults: { _controller: "ProductProductBundle:Collection:update" }
    methods:  [POST, PUT]

collection_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductProductBundle:Collection:delete" }
    methods:  [POST, DELETE]
