productreview:
    path:     /
    defaults: { _controller: "ProductProductBundle:ProductReview:index" }

productreview_show:
    path:     /{id}/show
    defaults: { _controller: "ProductProductBundle:ProductReview:show" }

productreview_new:
    path:     /new
    defaults: { _controller: "ProductProductBundle:ProductReview:new" }

productreview_create:
    path:     /create
    defaults: { _controller: "ProductProductBundle:ProductReview:create" }
    methods:  POST

productreview_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductProductBundle:ProductReview:edit" }

productreview_update:
    path:     /{id}/update
    defaults: { _controller: "ProductProductBundle:ProductReview:update" }
    methods:  [POST, PUT]

productreview_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductProductBundle:ProductReview:delete" }
    methods:  [POST, DELETE]
