product:
    path:     /
    defaults: { _controller: "ProductProductBundle:Product:index" }

product_show:
    path:     /{id}/show
    defaults: { _controller: "ProductProductBundle:Product:show" }

product_new:
    path:     /new
    defaults: { _controller: "ProductProductBundle:Product:new" }

product_upload:
    path:     /upload
    defaults: { _controller: "ProductProductBundle:Product:uploadProduct" }
    requirements: { _method: post }

product_create:
    path:     /create
    defaults: { _controller: "ProductProductBundle:Product:create" }
    requirements: { _method: post }

product_insert:
    path:     /insert
    defaults: { _controller: "ProductProductBundle:Product:insert" }

product_multiinsert:
    path:     /multiinsert
    defaults: { _controller: "ProductProductBundle:Product:multiinsert" }
    requirements: { _method: post|put }

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductProductBundle:Product:edit" }

product_update:
    path:     /{id}/update
    defaults: { _controller: "ProductProductBundle:Product:update" }
    requirements: { _method: post|put }

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductProductBundle:Product:delete" }
    requirements: { _method: post|delete }

product_status:
    path:     /{id}/status
    defaults: { _controller: "ProductProductBundle:Product:status" }

product_duplicate:
    path:     /{id}/duplicate
    defaults: { _controller: "ProductProductBundle:Product:duplicate" }

product_discount:
    path:     /{user}/discount
    defaults: { _controller: "ProductProductBundle:Product:discount" }
    requirements: { _method: post }

product_print_list:
    path:     /print-list
    defaults: { _controller: "SettingContentBundle:Product:printList" }

product_pdf_list:
    path:     /pdf-list
    defaults: { _controller: "SettingContentBundle:Product:pdfList" }

product_export_list:
    path:     /export-list
    defaults: { _controller: "SettingContentBundle:Product:exportList" }

product_print:
    path:     /{id}/print-details
    defaults: { _controller: "SettingContentBundle:Product:printDetails" }

product_pdf:
    path:     /{id}/pdf-details
    defaults: { _controller: "SettingContentBundle:Product:pdfDetails" }

product_import:
    path:     /import
    defaults: { _controller: "SettingContentBundle:Product:import" }

product_export:
    path:     /{id}/export-details
    defaults: { _controller: "SettingContentBundle:Product:exportDetails" }





