ecommerce_category:
    path:     /
    defaults: { _controller: "EcommerceBundle:CustomCategory:index" }

ecommerce_category_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:CustomCategory:show" }

ecommerce_category_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:CustomCategory:new" }

ecommerce_category_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:CustomCategory:create" }
    methods:  POST

ecommerce_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:CustomCategory:edit" }

ecommerce_category_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:CustomCategory:update" }
    methods:  [POST, PUT]

ecommerce_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:CustomCategory:delete" }

ecommerce_category_status:
    path:     /{id}/status
    defaults: { _controller: "EcommerceBundle:CustomCategory:status" }

ecommerce_category_feature:
    path:     /{id}/feature
    defaults: { _controller: "EcommerceBundle:CustomCategory:feature" }

