ecommerce_courier:
    path:     /
    defaults: { _controller: "EcommerceBundle:CourierService:index" }

ecommerce_courier_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:CourierService:new" }

ecommerce_courier_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:CourierService:create" }
    methods:  POST

ecommerce_courier_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:CourierService:edit" }

ecommerce_courier_status:
    path:     /{id}/status
    defaults: { _controller: "EcommerceBundle:CourierService:status" }

ecommerce_courier_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:CourierService:update" }
    methods:  [POST, PUT]

ecommerce_courier_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:CourierService:delete" }

