customer_order:
    path:     /
    defaults: { _controller: "EcommerceBundle:Order:index" }

customer_order_archive:
    path:     /archive
    defaults: { _controller: "EcommerceBundle:Order:archive" }

customer_order_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:Order:new" }

customer_order_edit:
    path:     /edit/{id}
    defaults: { _controller: "EcommerceBundle:Order:edit" }

customer_order_payment:
    path:     /payment/{id}
    defaults: { _controller: "EcommerceBundle:Order:payment" }

customer_order_update_inline:
    path:     /order-process-inline
    defaults: { _controller: "EcommerceBundle:Order:inlineProcessUpdate" }

customer_order_data_source:
    path:     /order-process-sourcess
    defaults: { _controller: "EcommerceBundle:Order:orderProcessSource" }


customer_order_add_item:
    path:     /item-add-inline/{id}
    defaults: { _controller: "EcommerceBundle:Order:inlineItemAdd" }


customer_order_item_disable:
    path:     /item-disable-inline/{id}
    defaults: { _controller: "EcommerceBundle:Order:inlineDisable" }

customer_order_shipping_charge:
    path:     /order-shiping-charge-inline/{id}
    defaults: { _controller: "EcommerceBundle:Order:shippingCharge" }

customer_order_confirm:
    path:     /{id}/order-confirm
    defaults: { _controller: "EcommerceBundle:Order:confirm" }
    methods:  [GET, PUT]

customer_order_item_confirm:
    path:     /{order}/{id}/order-item-confirm
    defaults: { _controller: "EcommerceBundle:Order:confirmItem" }


customer_order_print_invoice:
    path:     /invoice-print/{id}
    defaults: { _controller: "EcommerceBundle:Order:print" }

customer_order_pdf_invoice:
    path:     /invoice-print/{id}
    defaults: { _controller: "EcommerceBundle:Order:pdf" }

customer_order_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:Order:show" }


customer_order_purchase_item_search:
    path:     /{id}/inline-purchase-item-search
    defaults: { _controller: "EcommerceBundle:Order:purchaseItemSelect" }
    options:
           expose: true

customer_order_purchase_item_add:
    path:     /{id}/inline-purchase-item-add
    defaults: { _controller: "EcommerceBundle:Order:purchaseItemAdd" }
    methods:  POST
    options:
            expose: true

customer_order_payment_confirm:
    path:     /{id}/{process}/payment-confirm
    defaults: { _controller: "EcommerceBundle:Order:confirmPayment" }

customer_order_invoice_archive:
    path:     /{id}/invoice-archive
    defaults: { _controller: "EcommerceBundle:Order:archiveProcess" }


customer_order_payment_delete:
    path:     /{id}/payment-delete
    defaults: { _controller: "EcommerceBundle:Order:paymentDelete" }


customer_order_ajax_update:
    path:      /{id}/order-ajax-update
    defaults: { _controller: "EcommerceBundle:Order:paymentAjaxUpdate" }
    methods:  [POST]
    options:
        expose: true

customer_order_ajax_payment:
    path:      /{id}/order-payment
    defaults: { _controller: "EcommerceBundle:Order:paymentProcess" }
    methods:  [POST]


order_stock_item_search:
    path:     /order-item-search
    defaults: { _controller: "EcommerceBundle:Order:autoSearch" }
    options:
            expose: true

ecommerce_customer_search:
    path:     /customer-search
    defaults: { _controller: "EcommerceBundle:Order:autoCustomerSearch" }
    options:
            expose: true

ecommerce_order_existing_customer:
    path:     /customer-existing
    defaults: { _controller: "EcommerceBundle:Order:orderUpdateCustomer" }
    options:
            expose: true

order_item_stock_details:
    path:     /{id}/order-medicine-item-details
    defaults: { _controller: "EcommerceBundle:Order:stockDetails" }
    options:
            expose: true

customer_order_item:
    path:     /{id}/customer-order-item
    defaults: { _controller: "EcommerceBundle:Order:orderItemAdd" }
    methods:  POST
    options:
            expose: true

customer_medicine_item_update:
    path:      /{order}/{id}/medicine-item-update
    defaults: { _controller: "EcommerceBundle:Order:itemUpdate" }
    methods:  GET
    options:
            expose: true

customer_medicine_item_delete:
    path:      /{order}/{id}/medicine-item-delete
    defaults: { _controller: "EcommerceBundle:Order:itemDelete" }

customer_order_attach_download:
    path:      /{id}/attach-download
    defaults: { _controller: "EcommerceBundle:Order:downloadAttachFile" }

